package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"

	gqlmodel "github.com/Cityboypenguin/SPACE-server/graph/model"
	"github.com/Cityboypenguin/SPACE-server/infra/scraper"
	"github.com/Cityboypenguin/SPACE-server/internal/auth"
	"github.com/Cityboypenguin/SPACE-server/internal/courseimport"
	"github.com/Cityboypenguin/SPACE-server/model"
	"github.com/Cityboypenguin/SPACE-server/repository"
	courseusecase "github.com/Cityboypenguin/SPACE-server/usecase/course"
)

// CreateAdministrator is the resolver for the createAdministrator field.
func (r *mutationResolver) CreateAdministrator(ctx context.Context, input gqlmodel.CreateAdministratorInput) (*gqlmodel.Administrator, error) {
	param := model.CreateAdministratorParam{
		Name:     input.Name,
		Email:    input.Email,
		Password: input.Password,
	}

	administrator, err := r.CreateAdministratorUseCase.Execute(ctx, param)
	if err != nil {
		return nil, err
	}

	return toGraphAdministrator(administrator), nil
}

// DeleteAdministrator is the resolver for the deleteAdministrator field.
func (r *mutationResolver) DeleteAdministrator(ctx context.Context, id string) (bool, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return false, err
	}

	numericID, err := decodeGraphID(ctx, "administrator", id)
	if err != nil {
		return false, fmt.Errorf("invalid administrator id")
	}

	deleted, err := r.DeleteAdministratorUseCase.Execute(ctx, numericID)
	if err != nil {
		return false, err
	}

	return deleted, nil
}

// UpdateAdministrator is the resolver for the updateAdministrator field.
func (r *mutationResolver) UpdateAdministrator(ctx context.Context, id string, input gqlmodel.UpdateAdministratorInput) (*gqlmodel.Administrator, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}

	numericID, err := decodeGraphID(ctx, "administrator", id)
	if err != nil {
		return nil, fmt.Errorf("invalid administrator id")
	}

	param := model.UpdateAdministratorParam{
		Name:     input.Name,
		Email:    input.Email,
		Password: input.Password,
	}

	admin, err := r.UpdateAdministratorUseCase.Execute(ctx, numericID, param)
	if err != nil {
		return nil, err
	}

	return toGraphAdministrator(admin), nil
}

// LoginAdministrator is the resolver for the loginAdministrator field.
func (r *mutationResolver) LoginAdministrator(ctx context.Context, input gqlmodel.LoginInput) (*gqlmodel.AdministratorAuthPayload, error) {
	result, err := r.LoginAdministratorUseCase.Execute(ctx, input.Email, input.Password)
	if err != nil {
		return nil, err
	}

	return &gqlmodel.AdministratorAuthPayload{
		Token:         result.AccessToken,
		RefreshToken:  result.RefreshToken,
		Administrator: toGraphAdministrator(result.Administrator),
	}, nil
}

// RefreshAdministratorToken is the resolver for the refreshAdministratorToken field.
func (r *mutationResolver) RefreshAdministratorToken(ctx context.Context, refreshToken string) (*gqlmodel.AdministratorAuthPayload, error) {
	result, err := r.RefreshAdministratorTokenUseCase.Execute(ctx, refreshToken)
	if err != nil {
		return nil, err
	}

	return &gqlmodel.AdministratorAuthPayload{
		Token:         result.AccessToken,
		RefreshToken:  result.RefreshToken,
		Administrator: toGraphAdministrator(result.Administrator),
	}, nil
}

// LogoutAdministrator is the resolver for the logoutAdministrator field.
func (r *mutationResolver) LogoutAdministrator(ctx context.Context, token string) (bool, error) {
	if err := r.LogoutAdministratorUseCase.Execute(ctx, token); err != nil {
		return false, err
	}
	return true, nil
}

// AdminRegisterTimetableEntry is the resolver for the adminRegisterTimetableEntry field.
func (r *mutationResolver) AdminRegisterTimetableEntry(ctx context.Context, userID string, courseID string) (*gqlmodel.TimetableEntry, error) {
	uID, err := decodeGraphID(ctx, "user", userID)
	if err != nil {
		return nil, err
	}
	cID, err := decodeGraphID(ctx, "course", courseID)
	if err != nil {
		return nil, err
	}

	t, err := r.AdminRegisterTimetableUseCase.Execute(ctx, uID, cID)
	if err != nil {
		return nil, err
	}

	c, err := r.GetCourseByIDUseCase.Execute(ctx, t.CourseID)
	if err != nil {
		return nil, err
	}

	return toGraphTimetableEntry(t, c), nil
}

// AdminRemoveTimetableEntry is the resolver for the adminRemoveTimetableEntry field.
func (r *mutationResolver) AdminRemoveTimetableEntry(ctx context.Context, id string, userID string) (bool, error) {
	tID, err := decodeGraphID(ctx, "timetable", id)
	if err != nil {
		return false, err
	}
	uID, err := decodeGraphID(ctx, "user", userID)
	if err != nil {
		return false, err
	}
	return r.AdminRemoveTimetableUseCase.Execute(ctx, tID, uID)
}

// AdminSetTimetableEntryColor is the resolver for the adminSetTimetableEntryColor field.
func (r *mutationResolver) AdminSetTimetableEntryColor(ctx context.Context, id string, userID string, color gqlmodel.TimetableEntryColor) (*gqlmodel.TimetableEntry, error) {
	tID, err := decodeGraphID(ctx, "timetable", id)
	if err != nil {
		return nil, err
	}
	uID, err := decodeGraphID(ctx, "user", userID)
	if err != nil {
		return nil, err
	}

	t, err := r.AdminSetTimetableEntryColorUseCase.Execute(ctx, tID, uID, string(color))
	if err != nil {
		return nil, err
	}

	c, err := r.GetCourseByIDUseCase.Execute(ctx, t.CourseID)
	if err != nil {
		return nil, err
	}

	return toGraphTimetableEntry(t, c), nil
}

// AdminSetUserTimetable is the resolver for the adminSetUserTimetable field.
func (r *mutationResolver) AdminSetUserTimetable(ctx context.Context, userID string, year int32, semester string, baselineEntryIDs []string, courseIDs []string) ([]*gqlmodel.TimetableEntry, error) {
	uID, err := decodeGraphID(ctx, "user", userID)
	if err != nil {
		return nil, err
	}

	baselineIDs := make([]int64, 0, len(baselineEntryIDs))
	for _, id := range baselineEntryIDs {
		numericID, err := decodeGraphID(ctx, "timetable", id)
		if err != nil {
			return nil, err
		}
		baselineIDs = append(baselineIDs, numericID)
	}

	cIDs := make([]int64, 0, len(courseIDs))
	for _, id := range courseIDs {
		numericID, err := decodeGraphID(ctx, "course", id)
		if err != nil {
			return nil, err
		}
		cIDs = append(cIDs, numericID)
	}

	entries, err := r.AdminReplaceTimetableUseCase.Execute(ctx, uID, int(year), semester, baselineIDs, cIDs)
	if err != nil {
		return nil, err
	}

	result := make([]*gqlmodel.TimetableEntry, 0, len(entries))
	for _, e := range entries {
		result = append(result, toGraphTimetableEntry(e.Timetable, e.Course))
	}
	return result, nil
}

// AdminDeleteQuestion is the resolver for the adminDeleteQuestion field.
func (r *mutationResolver) AdminDeleteQuestion(ctx context.Context, id string) (bool, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return false, err
	}

	numericID, err := decodeGraphID(ctx, "question", id)
	if err != nil {
		return false, fmt.Errorf("invalid question id")
	}

	return r.DeleteQuestionUseCase.Execute(ctx, numericID)
}

// AdminTriggerCourseImport is the resolver for the adminTriggerCourseImport field.
func (r *mutationResolver) AdminTriggerCourseImport(ctx context.Context, year int32) (*gqlmodel.CourseImportStatus, error) {
	claims, err := requireAdminAuth(ctx)
	if err != nil {
		return nil, err
	}
	status, err := r.CourseImportTracker.Start(int(year), func(bgCtx context.Context, reportProgress func(processed, total int)) (int, int, error) {
		bgCtx = auth.WithClaims(bgCtx, claims)
		knownDedupKeys, err := r.ListDedupKeysByYearUseCase.Execute(bgCtx, int(year))
		if err != nil {
			return 0, 0, err
		}

		sc, err := scraper.NewSenshuSyllabusScraper()
		if err != nil {
			return 0, 0, err
		}
		defer sc.Close()
		scraped, skippedRows, err := sc.FetchCourses(bgCtx, int(year), knownDedupKeys, reportProgress)
		if err != nil {
			return 0, skippedRows, err
		}
		result, err := r.ImportCoursesUseCase.Execute(bgCtx, scraped)
		if err != nil {
			return 0, skippedRows, err
		}
		return result.Imported, skippedRows + result.Skipped, nil
	})
	if err != nil {
		return nil, err
	}
	return toGraphCourseImportStatus(status), nil
}

// AdminCreateCourse is the resolver for the adminCreateCourse field.
func (r *mutationResolver) AdminCreateCourse(ctx context.Context, input gqlmodel.AdminCreateCourseInput) (*gqlmodel.Course, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}

	c, err := r.AdminCreateCourseUseCase.Execute(ctx, courseusecase.AdminCreateCourseParam{
		DayOfWeek:   input.DayOfWeek,
		Period:      int(input.Period),
		TeacherName: input.TeacherName,
		CourseName:  input.CourseName,
		Year:        int(input.Year),
		Semester:    input.Semester,
	})
	if err != nil {
		return nil, err
	}
	gqlCourse := toGraphCourse(c)
	gqlCourse.RegisteredCount = 0
	return gqlCourse, nil
}

// AdminDeleteCourse is the resolver for the adminDeleteCourse field.
func (r *mutationResolver) AdminDeleteCourse(ctx context.Context, id string) (bool, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return false, err
	}

	numericID, err := decodeGraphID(ctx, "course", id)
	if err != nil {
		return false, fmt.Errorf("invalid course id")
	}

	return r.AdminDeleteCourseUseCase.Execute(ctx, numericID)
}

// AdminUpdateUser is the resolver for the adminUpdateUser field.
func (r *mutationResolver) AdminUpdateUser(ctx context.Context, id string, input gqlmodel.UpdateUserInput) (*gqlmodel.UserAccount, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}

	if input.AccountID == nil || *input.AccountID == "" {
		return nil, fmt.Errorf("accountID は必須です")
	}
	if input.Name == nil || *input.Name == "" {
		return nil, fmt.Errorf("name は必須です")
	}
	if input.Email == nil || *input.Email == "" {
		return nil, fmt.Errorf("email は必須です")
	}

	numericID, err := decodeGraphID(ctx, "user", id)
	if err != nil {
		return nil, fmt.Errorf("invalid user id")
	}

	param := model.UpdateUserParam{
		AccountID: input.AccountID,
		Name:      input.Name,
		Email:     input.Email,
		Password:  input.Password,
	}

	user, err := r.UpdateUserUseCase.Execute(ctx, numericID, param, input.CurrentPassword, false)
	if err != nil {
		return nil, err
	}

	return toGraphUserAccount(user), nil
}

// AdminUpdateProfile is the resolver for the adminUpdateProfile field.
func (r *mutationResolver) AdminUpdateProfile(ctx context.Context, userID string, input gqlmodel.UpdateProfileInput) (*gqlmodel.Profile, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}

	numericUserID, err := decodeGraphID(ctx, "user", userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id")
	}

	param := model.UpdateProfileParam{
		Bio: input.Bio,
	}

	p, err := r.UpdateProfileUseCase.Execute(ctx, numericUserID, param)
	if err != nil {
		return nil, err
	}

	return r.graphProfile(ctx, p)
}

// AdminDeletePost is the resolver for the adminDeletePost field.
func (r *mutationResolver) AdminDeletePost(ctx context.Context, id string) (bool, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return false, err
	}

	numericID, err := decodeGraphID(ctx, "post", id)
	if err != nil {
		return false, fmt.Errorf("invalid post id")
	}

	return r.DeletePostUseCase.Execute(ctx, numericID, true)
}

// ToggleMaintenanceMode is the resolver for the toggleMaintenanceMode field.
func (r *mutationResolver) ToggleMaintenanceMode(ctx context.Context, enabled bool) (bool, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return false, err
	}
	if err := r.MaintenanceRepository.SetMaintenanceMode(ctx, enabled); err != nil {
		return false, err
	}
	r.MaintenanceFlag.Store(enabled)
	return enabled, nil
}

// RecordSessionData is the resolver for the recordSessionData field.
func (r *mutationResolver) RecordSessionData(ctx context.Context, input gqlmodel.RecordSessionDataInput) (bool, error) {
	pageViews := make([]repository.PageViewInput, len(input.PageViews))
	for i, pv := range input.PageViews {
		pageViews[i] = repository.PageViewInput{
			Path:            pv.Path,
			DurationSeconds: int(pv.DurationSeconds),
			MaxScrollDepth:  int(pv.MaxScrollDepth),
		}
	}
	if err := r.RecordSessionUseCase.Execute(ctx, int(input.SessionDurationSeconds), pageViews); err != nil {
		return false, err
	}
	return true, nil
}

// AdminSearchUsers is the resolver for the adminSearchUsers field.
//
// searchUsers と同じ検索だが、管理者専用で連絡先まで返す。口を分けているのは、
// GraphQL の戻り値の型が呼び出し元の権限で変わらないため（searchUsers に
// 「管理者のときだけ email も」を足すことはできない）。
func (r *queryResolver) AdminSearchUsers(ctx context.Context, keyword string, limit *int32, offset *int32) (*gqlmodel.UserAccountPage, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}
	users, total, err := r.SearchUserAccountsUseCase.Execute(ctx, keyword, resolvePageQuery(ctx, limit, offset, defaultPageSize))
	if err != nil {
		return nil, err
	}
	items := make([]*gqlmodel.UserAccount, 0, len(users))
	for _, user := range users {
		items = append(items, toGraphUserAccount(user))
	}
	return &gqlmodel.UserAccountPage{Items: items, Total: int32(total)}, nil
}

// Administrators is the resolver for the administrators field.
func (r *queryResolver) Administrators(ctx context.Context, limit *int32, offset *int32) (*gqlmodel.AdministratorPage, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}

	admins, total, err := r.ListAdministratorsUseCase.Execute(ctx, resolvePageQuery(ctx, limit, offset, defaultPageSize))
	if err != nil {
		return nil, err
	}

	items := make([]*gqlmodel.Administrator, 0, len(admins))
	for _, admin := range admins {
		items = append(items, toGraphAdministrator(admin))
	}
	return &gqlmodel.AdministratorPage{Items: items, Total: int32(total)}, nil
}

// GetAdministratorByID is the resolver for the getAdministratorByID field.
func (r *queryResolver) GetAdministratorByID(ctx context.Context, id string) (*gqlmodel.Administrator, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}

	numericID, err := decodeGraphID(ctx, "administrator", id)
	if err != nil {
		return nil, fmt.Errorf("invalid administrator id")
	}

	admin, err := r.GetAdministratorByIDUseCase.Execute(ctx, numericID)
	if err != nil {
		return nil, err
	}

	return toGraphAdministrator(admin), nil
}

// SearchAdministrators is the resolver for the searchAdministrators field.
func (r *queryResolver) SearchAdministrators(ctx context.Context, name string) ([]*gqlmodel.Administrator, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}

	admins, err := r.SearchAdministratorsUseCase.Execute(ctx, name)
	if err != nil {
		return nil, err
	}

	var gqlAdmins []*gqlmodel.Administrator
	for _, admin := range admins {
		gqlAdmins = append(gqlAdmins, toGraphAdministrator(admin))
	}
	return gqlAdmins, nil
}

// MaintenanceMode is the resolver for the maintenanceMode field.
func (r *queryResolver) MaintenanceMode(ctx context.Context) (bool, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return false, err
	}
	return r.MaintenanceFlag.Load(), nil
}

// AdminGetFavoriteUsers is the resolver for the adminGetFavoriteUsers field.
func (r *queryResolver) AdminGetFavoriteUsers(ctx context.Context, userID string, limit *int32, offset *int32) ([]*gqlmodel.User, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}
	numericUserID, err := decodeGraphID(ctx, "user", userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id")
	}
	favoriteUsers, err := r.GetFavoriteUserByUserIDUseCase.Execute(ctx, numericUserID, resolveUnpagedWindow(limit, offset))
	if err != nil {
		return nil, err
	}
	return r.favoriteUsersToGQL(ctx, favoriteUsers)
}

// AdminGetBlockers is the resolver for the adminGetBlockers field.
func (r *queryResolver) AdminGetBlockers(ctx context.Context, userID string, limit *int32, offset *int32) ([]*gqlmodel.User, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}
	numericUserID, err := decodeGraphID(ctx, "user", userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id")
	}
	blockedUsers, err := r.GetBlockersByUserIDUseCase.Execute(ctx, numericUserID, resolveUnpagedWindow(limit, offset))
	if err != nil {
		return nil, err
	}
	return r.blockedUsersToGQL(ctx, blockedUsers)
}

// AdminGetAnalytics is the resolver for the adminGetAnalytics field.
func (r *queryResolver) AdminGetAnalytics(ctx context.Context) (*gqlmodel.AnalyticsSummary, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}
	summary, err := r.GetAnalyticsUseCase.Execute(ctx, resolveAnalyticsFields(ctx))
	if err != nil {
		return nil, err
	}
	return toGraphAnalyticsSummary(summary), nil
}

// AdminGetCommunityAnalytics is the resolver for the adminGetCommunityAnalytics field.
func (r *queryResolver) AdminGetCommunityAnalytics(ctx context.Context, limit *int32, offset *int32) (*gqlmodel.CommunityStatsPage, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}
	items, total, err := r.GetCommunityAnalyticsUseCase.Execute(ctx, resolvePageQuery(ctx, limit, offset, defaultPageSize))
	if err != nil {
		return nil, err
	}
	gqlItems := make([]*gqlmodel.CommunityStatItem, len(items))
	for i, item := range items {
		gqlItems[i] = toGraphCommunityStatItem(item)
	}
	return &gqlmodel.CommunityStatsPage{Items: gqlItems, Total: int32(total)}, nil
}

// AdminGetTimeSeries is the resolver for the adminGetTimeSeries field.
func (r *queryResolver) AdminGetTimeSeries(ctx context.Context, granularity gqlmodel.TimeSeriesGranularity, from string, to string) (*gqlmodel.TimeSeriesData, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}
	points, err := r.GetTimeSeriesUseCase.Execute(ctx, string(granularity), from, to, resolveAnalyticsFields(ctx, "points"))
	if err != nil {
		return nil, err
	}
	gqlPoints := make([]*gqlmodel.TimeSeriesPoint, len(points))
	for i, p := range points {
		gqlPoints[i] = &gqlmodel.TimeSeriesPoint{
			Label:       p.Label,
			Posts:       int32(p.Posts),
			Comments:    int32(p.Comments),
			Messages:    int32(p.Messages),
			NewUsers:    int32(p.NewUsers),
			Likes:       int32(p.Likes),
			ActiveUsers: int32(p.ActiveUsers),
		}
	}
	return &gqlmodel.TimeSeriesData{Points: gqlPoints}, nil
}

// AdminCourseImportStatus is the resolver for the adminCourseImportStatus field.
func (r *queryResolver) AdminCourseImportStatus(ctx context.Context) (*gqlmodel.CourseImportStatus, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}
	return toGraphCourseImportStatus(r.CourseImportTracker.Get()), nil
}

// AdminListCourseYears is the resolver for the adminListCourseYears field.
func (r *queryResolver) AdminListCourseYears(ctx context.Context) ([]int32, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}

	years, err := r.ListCourseYearsUseCase.Execute(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]int32, 0, len(years))
	for _, y := range years {
		result = append(result, int32(y))
	}
	return result, nil
}

// AdminGetCourse is the resolver for the adminGetCourse field.
func (r *queryResolver) AdminGetCourse(ctx context.Context, id string) (*gqlmodel.Course, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}

	numericID, err := decodeGraphID(ctx, "course", id)
	if err != nil {
		return nil, fmt.Errorf("invalid course id")
	}

	c, err := r.GetCourseByIDUseCase.Execute(ctx, numericID)
	if err != nil || c == nil {
		return nil, err
	}
	gqlCourse := toGraphCourse(c)
	// 履修者数は削除前の影響範囲を見せるためだけの値なので、選ばれたときだけ数える。
	if fieldRequested(ctx, "registeredCount") {
		count, err := r.GetCourseRegisteredCountUseCase.Execute(ctx, c.ID)
		if err != nil {
			return nil, err
		}
		gqlCourse.RegisteredCount = int32(count)
	}
	return gqlCourse, nil
}

// AdminListCourses is the resolver for the adminListCourses field.
func (r *queryResolver) AdminListCourses(ctx context.Context, year *int32, semester *string, dayOfWeek *string, keyword *string, limit *int32, offset *int32) (*gqlmodel.CoursePage, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}

	var y *int
	if year != nil {
		v := int(*year)
		y = &v
	}
	kw := ""
	if keyword != nil {
		kw = *keyword
	}
	items, total, err := r.ListCoursesUseCase.Execute(ctx, courseusecase.ListCoursesParam{
		Year:      y,
		Semester:  semester,
		DayOfWeek: dayOfWeek,
		Keyword:   kw,
		Page:      resolvePageQuery(ctx, limit, offset, defaultPageSize),
	})
	if err != nil {
		return nil, err
	}

	// 履修者数は、選ばれたときだけ授業IDの集合で1クエリにまとめて数える。
	// 以前は一覧の1件ごとに COUNT を撃っていた（20件なら20本）。
	// 単体の adminCourse と同じく、判定は共通の fieldRequested。
	registeredCounts := map[int64]int{}
	if fieldRequested(ctx, "items", "registeredCount") {
		courseIDs := make([]int64, 0, len(items))
		for _, c := range items {
			courseIDs = append(courseIDs, c.ID)
		}
		registeredCounts, err = r.GetCourseRegisteredCountsUseCase.Execute(ctx, courseIDs)
		if err != nil {
			return nil, err
		}
	}

	gqlItems := make([]*gqlmodel.Course, 0, len(items))
	for _, c := range items {
		gqlCourse := toGraphCourse(c)
		gqlCourse.RegisteredCount = int32(registeredCounts[c.ID])
		gqlItems = append(gqlItems, gqlCourse)
	}

	return &gqlmodel.CoursePage{Items: gqlItems, Total: int32(total)}, nil
}

// AdminCourseImportStatusUpdated is the resolver for the adminCourseImportStatusUpdated field.
func (r *subscriptionResolver) AdminCourseImportStatusUpdated(ctx context.Context) (<-chan *gqlmodel.CourseImportStatus, error) {
	claims, err := requireAdminAuth(ctx)
	if err != nil {
		return nil, err
	}

	// ドメインの値（courseimport.Status）で流れてくるので GraphQL 型へ直してから配信する。
	return subscribeTopicFunc(
		ctx,
		r.PubSub,
		CourseImportStatusTopic,
		subscriptionScope{UserID: claims.ID},
		func(status courseimport.Status) (*gqlmodel.CourseImportStatus, bool) {
			return toGraphCourseImportStatus(status), true
		},
	), nil
}
