package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"

	gqlmodel "github.com/Cityboypenguin/SPACE-server/graph/model"
	announcementusecase "github.com/Cityboypenguin/SPACE-server/usecase/announcement"
)

// CreateAnnouncement is the resolver for the createAnnouncement field.
func (r *mutationResolver) CreateAnnouncement(ctx context.Context, input gqlmodel.CreateAnnouncementInput) (*gqlmodel.Announcement, error) {
	_, err := requireAdminAuth(ctx)
	if err != nil {
		return nil, err
	}
	a, err := r.CreateAnnouncementUseCase.Execute(ctx, announcementusecase.CreateAnnouncementInput{
		Title: input.Title,
		Body:  input.Body,
	})
	if err != nil {
		return nil, err
	}
	return toGraphAnnouncement(a), nil
}

// UpdateAnnouncement is the resolver for the updateAnnouncement field.
func (r *mutationResolver) UpdateAnnouncement(ctx context.Context, id string, input gqlmodel.UpdateAnnouncementInput) (*gqlmodel.Announcement, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}
	numericID, err := decodeGraphID(ctx, "announcement", id)
	if err != nil {
		return nil, fmt.Errorf("invalid announcement id")
	}
	a, err := r.UpdateAnnouncementUseCase.Execute(ctx, announcementusecase.UpdateAnnouncementInput{
		ID:    numericID,
		Title: input.Title,
		Body:  input.Body,
	})
	if err != nil {
		return nil, err
	}
	return toGraphAnnouncement(a), nil
}

// DeleteAnnouncement is the resolver for the deleteAnnouncement field.
func (r *mutationResolver) DeleteAnnouncement(ctx context.Context, id string) (bool, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return false, err
	}
	numericID, err := decodeGraphID(ctx, "announcement", id)
	if err != nil {
		return false, fmt.Errorf("invalid announcement id")
	}
	if err := r.DeleteAnnouncementUseCase.Execute(ctx, numericID); err != nil {
		return false, err
	}
	return true, nil
}

// Announcements is the resolver for the announcements field.
func (r *queryResolver) Announcements(ctx context.Context, limit *int32, offset *int32) (*gqlmodel.AnnouncementPage, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	list, total, err := r.ListAnnouncementsUseCase.Execute(ctx, resolvePageQuery(ctx, limit, offset, defaultPageSize))
	if err != nil {
		return nil, err
	}
	items := make([]*gqlmodel.Announcement, 0, len(list))
	for _, a := range list {
		items = append(items, toGraphAnnouncement(a))
	}
	return &gqlmodel.AnnouncementPage{Items: items, Total: int32(total)}, nil
}

// Announcement is the resolver for the announcement field.
func (r *queryResolver) Announcement(ctx context.Context, id string) (*gqlmodel.Announcement, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	numericID, err := decodeGraphID(ctx, "announcement", id)
	if err != nil {
		return nil, fmt.Errorf("invalid announcement id")
	}
	a, err := r.GetAnnouncementUseCase.Execute(ctx, numericID)
	if err != nil {
		return nil, err
	}
	return toGraphAnnouncement(a), nil
}

// AdminListAnnouncements is the resolver for the adminListAnnouncements field.
func (r *queryResolver) AdminListAnnouncements(ctx context.Context, limit *int32, offset *int32) (*gqlmodel.AnnouncementPage, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}
	list, total, err := r.ListAnnouncementsUseCase.Execute(ctx, resolvePageQuery(ctx, limit, offset, defaultPageSize))
	if err != nil {
		return nil, err
	}
	items := make([]*gqlmodel.Announcement, 0, len(list))
	for _, a := range list {
		items = append(items, toGraphAnnouncement(a))
	}
	return &gqlmodel.AnnouncementPage{Items: items, Total: int32(total)}, nil
}
