package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"
	"fmt"
	"time"

	gqlmodel "github.com/Cityboypenguin/SPACE-server/graph/model"
	"github.com/Cityboypenguin/SPACE-server/internal/dataloader"
	"github.com/Cityboypenguin/SPACE-server/model"
	"github.com/Cityboypenguin/SPACE-server/repository"
	chatusecase "github.com/Cityboypenguin/SPACE-server/usecase/chat"
	roomusecase "github.com/Cityboypenguin/SPACE-server/usecase/room"
)

// Room is the resolver for the room field.
func (r *messageResolver) Room(ctx context.Context, obj *gqlmodel.Message) (*gqlmodel.Room, error) {
	numericID, err := decodeGraphID(ctx, "room", obj.RoomID)
	if err != nil {
		return nil, nil
	}
	// チャット履歴は同じルームのメッセージが並ぶので DataLoader 経由で引く
	//（メッセージ N 件で N クエリ → 1クエリ、かつ同一ルームならキャッシュで1回）。
	// 引けなくても従来どおり nil を返して画面は出す。
	rm, err := dataloader.For(ctx).RoomLoader.Load(ctx, numericID)
	if err != nil || rm == nil {
		return nil, nil
	}
	gqlRoom := toGraphRoom(rm)
	gqlRoom.IsMessagingDisabled = false
	return gqlRoom, nil
}

// UserID is the resolver for the userID field.
func (r *messageResolver) UserID(ctx context.Context, obj *gqlmodel.Message) (string, error) {
	numericID, err := decodeGraphID(ctx, "user", obj.UserID)
	if err != nil {
		return "", nil
	}

	if anon := r.anonymousUserForCourseRoom(ctx, obj.RoomID, numericID); anon != nil {
		return anon.ID, nil
	}

	return obj.UserID, nil
}

// User is the resolver for the user field.
func (r *messageResolver) User(ctx context.Context, obj *gqlmodel.Message) (*gqlmodel.User, error) {
	numericID, err := decodeGraphID(ctx, "user", obj.UserID)
	if err != nil {
		return nil, nil
	}

	if anon := r.anonymousUserForCourseRoom(ctx, obj.RoomID, numericID); anon != nil {
		return anon, nil
	}

	u, err := dataloader.For(ctx).UserLoader.Load(ctx, numericID)
	if err != nil || u == nil {
		return nil, nil
	}
	return toGraphUser(u), nil
}

// Media is the resolver for the media field.
func (r *messageResolver) Media(ctx context.Context, obj *gqlmodel.Message) ([]*gqlmodel.Media, error) {
	numericID, err := decodeGraphID(ctx, "message", obj.ID)
	if err != nil {
		return nil, nil
	}
	mediaList, err := dataloader.For(ctx).MessageMediaLoader.Load(ctx, numericID)
	if err != nil {
		return nil, err
	}
	var result []*gqlmodel.Media
	for _, m := range mediaList {
		result = append(result, toGraphMedia(m, r.StorageRepository.PublicURL(m.StorageKey)))
	}
	return result, nil
}

// IsMine is the resolver for the isMine field.
func (r *messageResolver) IsMine(ctx context.Context, obj *gqlmodel.Message) (bool, error) {
	return isCallerID(ctx, obj.UserID), nil
}

// ReplyTo is the resolver for the replyTo field.
func (r *messageResolver) ReplyTo(ctx context.Context, obj *gqlmodel.Message) (*gqlmodel.Message, error) {
	if obj.ReplyToID == nil {
		return nil, nil
	}
	numericID, err := decodeGraphID(ctx, "message", *obj.ReplyToID)
	if err != nil {
		return nil, nil
	}
	// 返信先が削除済みなら nil。クライアントは replyToID があるのに replyTo が nil の
	// ケースを「削除されたメッセージへの返信」として表示する。
	parent, err := dataloader.For(ctx).MessageLoader.Load(ctx, numericID)
	if err != nil || parent == nil {
		return nil, nil
	}
	return toGraphMessage(parent), nil
}

// Mentions is the resolver for the mentions field.
func (r *messageResolver) Mentions(ctx context.Context, obj *gqlmodel.Message) ([]*gqlmodel.Mention, error) {
	numericMessageID, err := decodeGraphID(ctx, "message", obj.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid message id")
	}

	mentions, err := dataloader.For(ctx).MessageMentionLoader.Load(ctx, numericMessageID)
	if err != nil {
		return nil, err
	}
	return resolveMentions(ctx, mentions)
}

// CreateRoom is the resolver for the createRoom field.
func (r *mutationResolver) CreateRoom(ctx context.Context, input gqlmodel.CreateRoomInput) (*gqlmodel.Room, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}

	community, err := r.CreateCommunityUseCase.Execute(ctx, input.Name, "", nil)
	if err != nil {
		return nil, err
	}
	if community == nil {
		return nil, errors.New("community creation returned no community")
	}
	room, err := r.GetRoomUseCase.Execute(ctx, community.RoomID)
	if err != nil {
		return nil, err
	}
	if room == nil {
		return nil, errors.New("created community room not found")
	}

	gqlRoom := toGraphRoom(room)
	gqlRoom.IsMessagingDisabled = false
	return gqlRoom, nil
}

// GetOrCreateDMRoom is the resolver for the getOrCreateDMRoom field.
func (r *mutationResolver) GetOrCreateDMRoom(ctx context.Context, targetUserID string) (*gqlmodel.Room, error) {
	_, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	tid, err := decodeGraphID(ctx, "user", targetUserID)
	if err != nil {
		return nil, fmt.Errorf("invalid target user id")
	}

	// 双方のメンバー登録は GetOrCreateDMRoomUseCase（= RoomUserRepository.FindOrCreateDMRoom）
	// が SERIALIZABLE トランザクション内で担保している。既存ルームは「両者の room_users が
	// 揃っている」ことを JOIN 条件にして探し、無ければ rooms と2件の room_users を同じ
	// トランザクションで作る。したがってここで AddUserToRoom を撃ち直す必要はない。
	room, err := r.GetOrCreateDMRoomUseCase.Execute(ctx, tid)
	if err != nil {
		return nil, err
	}

	gqlRoom := toGraphRoom(room)

	// room クエリと同じで、メンバー一覧とブロック判定は選ばれたときだけ引く。
	// ここは DM を作る（または見つける）ミューテーションなので、相手は引数から
	// 決まっており、メンバー一覧はブロック判定には要らない。
	if fieldRequested(ctx, "user") {
		usersByRoomID, err := r.ListUsersByRoomIDsUseCase.Execute(ctx, []int64{room.ID})
		if err != nil {
			return nil, fmt.Errorf("failed to load room members")
		}
		members := make([]*gqlmodel.User, 0)
		for _, u := range usersByRoomID[room.ID] {
			members = append(members, toGraphUser(u))
		}
		gqlRoom.User = members
	}

	if fieldRequested(ctx, "isMessagingDisabled") {
		isBlocked, err := r.CheckBlockRelationUseCase.Execute(ctx, tid)
		if err != nil {
			gqlRoom.IsMessagingDisabled = false
		} else {
			gqlRoom.IsMessagingDisabled = isBlocked
		}
	}

	return gqlRoom, nil
}

// AddUserToRoom is the resolver for the addUserToRoom field.
func (r *mutationResolver) AddUserToRoom(ctx context.Context, input gqlmodel.AddUserToRoomInput) (bool, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}

	rid, err := decodeGraphID(ctx, "room", input.RoomID)
	if err != nil {
		return false, fmt.Errorf("invalid room id")
	}
	uid, err := decodeGraphID(ctx, "user", input.UserID)
	if err != nil {
		return false, fmt.Errorf("invalid user id")
	}

	if uid != claims.ID {
		return false, errors.New("forbidden: can only join community as yourself")
	}

	return r.JoinRoomUseCase.Execute(ctx, rid)
}

// RemoveUserFromRoom is the resolver for the removeUserFromRoom field.
func (r *mutationResolver) RemoveUserFromRoom(ctx context.Context, input gqlmodel.RemoveUserFromRoomInput) (bool, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}

	rid, err := decodeGraphID(ctx, "room", input.RoomID)
	if err != nil {
		return false, fmt.Errorf("invalid room id")
	}
	uid, err := decodeGraphID(ctx, "user", input.UserID)
	if err != nil {
		return false, fmt.Errorf("invalid user id")
	}

	if claims.ID != uid {
		return false, errors.New("forbidden: can only remove yourself from a room")
	}

	left, err := r.LeaveCommunityUseCase.Execute(ctx, rid)
	if err != nil || !left {
		return left, err
	}

	// 退出した本人の購読をその場で終わらせる。抜けた直後に「もう読めない部屋の
	// 新着だけが、開いたままのタブに届き続ける」のを防ぐ。
	r.publishRoomAccessChanged(rid, []int64{uid})
	return true, nil
}

// DeleteRoom is the resolver for the deleteRoom field.
func (r *mutationResolver) DeleteRoom(ctx context.Context, roomID string) (bool, error) {
	if _, err := requireAuth(ctx); err != nil {
		return false, err
	}

	rid, err := decodeGraphID(ctx, "room", roomID)
	if err != nil {
		return false, fmt.Errorf("invalid room id")
	}

	return r.DeleteOrphanedDMUseCase.Execute(ctx, rid)
}

// JoinRoom is the resolver for the joinRoom field.
func (r *mutationResolver) JoinRoom(ctx context.Context, roomID string) (bool, error) {
	if _, err := requireAuth(ctx); err != nil {
		return false, err
	}
	rid, err := decodeGraphID(ctx, "room", roomID)
	if err != nil {
		return false, fmt.Errorf("invalid room id")
	}
	return r.JoinRoomUseCase.Execute(ctx, rid)
}

// SendMessage is the resolver for the sendMessage field.
//
// 権限判定（授業の学期・履修 / membership / ブロック）、メンションの検証、
// 保存後の配信・通知は全て ChatCommands 側にある。ここは GraphQL ID のデコードと
// GraphQL 型への変換だけを行う。
func (r *mutationResolver) SendMessage(ctx context.Context, roomID string, content string, mediaInputs []*gqlmodel.MediaUploadInput, mentionUserIDs []string, replyToID *string) (*gqlmodel.Message, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}

	rid, err := decodeGraphID(ctx, "room", roomID)
	if err != nil {
		return nil, fmt.Errorf("invalid room id")
	}

	var replyTo *int64
	if replyToID != nil && *replyToID != "" {
		decoded, err := decodeGraphID(ctx, "message", *replyToID)
		if err != nil {
			return nil, fmt.Errorf("invalid reply target id")
		}
		replyTo = &decoded
	}

	mentionIDs, err := decodeMentionUserIDs(ctx, mentionUserIDs)
	if err != nil {
		return nil, err
	}

	ucMediaInputs := r.toMediaInputs(mediaInputs)

	msg, err := r.ChatCommands.SendMessage(ctx, chatusecase.SendMessageInput{
		RoomID:         rid,
		Content:        content,
		MediaInputs:    ucMediaInputs,
		MentionUserIDs: mentionIDs,
		ReplyToID:      replyTo,
	})
	if err != nil {
		return nil, err
	}

	return toGraphMessage(msg), nil
}

// DeleteMessage is the resolver for the deleteMessage field.
func (r *mutationResolver) DeleteMessage(ctx context.Context, roomID string, id string) (bool, error) {
	if _, err := requireAuth(ctx); err != nil {
		return false, err
	}

	rid, err := decodeGraphID(ctx, "room", roomID)
	if err != nil {
		return false, fmt.Errorf("invalid room id")
	}
	numericID, err := decodeGraphID(ctx, "message", id)
	if err != nil {
		return false, fmt.Errorf("invalid message id")
	}

	return r.ChatCommands.DeleteMessage(ctx, chatusecase.DeleteMessageInput{RoomID: rid, MessageID: numericID})
}

// UpdateMessage is the resolver for the updateMessage field.
func (r *mutationResolver) UpdateMessage(ctx context.Context, roomID string, id string, content string, mentionUserIDs []string) (*gqlmodel.Message, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}

	rid, err := decodeGraphID(ctx, "room", roomID)
	if err != nil {
		return nil, fmt.Errorf("invalid room id")
	}
	numericID, err := decodeGraphID(ctx, "message", id)
	if err != nil {
		return nil, fmt.Errorf("invalid message id")
	}

	mentionIDs, err := decodeMentionUserIDs(ctx, mentionUserIDs)
	if err != nil {
		return nil, err
	}

	msg, err := r.ChatCommands.UpdateMessage(ctx, chatusecase.UpdateMessageInput{
		RoomID:         rid,
		MessageID:      numericID,
		Content:        content,
		MentionUserIDs: mentionIDs,
	})
	if err != nil {
		return nil, err
	}

	return toGraphMessage(msg), nil
}

// MarkRoomAsRead is the resolver for the markRoomAsRead field.
//
// 既読位置の置き場（授業内チャットは course_room_reads、それ以外は room_users）の
// 切り分けと、既読にしたあとの配信（相手側の既読表示・DM 通知の既読化・本人への
// room_changed）は ChatReads 側にある。
//
// lastReadMessageID は任意。渡ってきたときは不透明IDを数値へ戻すところまでがここの
// 仕事で、「本当にこのルームのメッセージか」の検証は既読位置を決める
// roomusecase.resolveReadMessageID が持つ（保存する値を決める場所と検証する場所を
// 離すと、新しい呼び出し元が増えたときに検証だけ抜ける）。
// 省略時（古いクライアント）はサーバ側が最新メッセージを既読位置にする。
func (r *mutationResolver) MarkRoomAsRead(ctx context.Context, roomID string, lastReadMessageID *string) (bool, error) {
	if _, err := requireAuth(ctx); err != nil {
		return false, err
	}
	rid, err := decodeGraphID(ctx, "room", roomID)
	if err != nil {
		return false, fmt.Errorf("invalid room id")
	}
	var messageID *int64
	if lastReadMessageID != nil {
		id, err := decodeGraphID(ctx, "message", *lastReadMessageID)
		if err != nil {
			return false, fmt.Errorf("invalid last read message id")
		}
		messageID = &id
	}
	if err := r.ChatReads.MarkAsRead(ctx, rid, messageID); err != nil {
		return false, err
	}
	return true, nil
}

// Messages is the resolver for the messages field.
//
// 閲覧権限（授業は全員閲覧可、それ以外は room_users）の判定は
// ChatAccess.EnsureReadAccess にあり、messageAdded などのサブスクリプションと
// 同じ1本を通る。ここはカーソルのデコードと GraphQL 型への変換だけ。
func (r *queryResolver) Messages(ctx context.Context, roomID string, limit *int32, before *string, after *string, afterTime *string, around *string) (*gqlmodel.MessagePage, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}

	rid, err := decodeGraphID(ctx, "room", roomID)
	if err != nil {
		return nil, fmt.Errorf("invalid room id")
	}

	// チャットは1画面に載る件数が一覧系より多いので、ここだけ上限が maxPageSize
	// ではなく maxMessagePageSize。クランプそのものは resolveLimit に揃える。
	l := resolveLimit(limit, 50, maxMessagePageSize)
	var beforeID *int64
	if before != nil {
		id, err := decodeGraphID(ctx, "message", *before)
		if err != nil {
			return nil, fmt.Errorf("invalid before id")
		}
		beforeID = &id
	}

	var afterID *int64
	if after != nil {
		id, err := decodeGraphID(ctx, "message", *after)
		if err != nil {
			return nil, fmt.Errorf("invalid after id")
		}
		afterID = &id
	}

	var afterTimeVal *time.Time
	if afterTime != nil {
		t, err := time.Parse(time.RFC3339, *afterTime)
		if err != nil {
			return nil, fmt.Errorf("invalid afterTime format, use RFC3339")
		}
		afterTimeVal = &t
	}

	var aroundID *int64
	if around != nil {
		id, err := decodeGraphID(ctx, "message", *around)
		if err != nil {
			return nil, fmt.Errorf("invalid around id")
		}
		aroundID = &id
	}

	page, err := r.ChatQueries.ListMessages(ctx, chatusecase.ListMessagesInput{
		RoomID:   rid,
		Limit:    l,
		Cursor:   repository.MessageCursor{BeforeID: beforeID, AfterID: afterID, AfterTime: afterTimeVal},
		AroundID: aroundID,
	})
	if err != nil {
		return nil, err
	}

	items := make([]*gqlmodel.Message, 0, len(page.Items))
	for _, msg := range page.Items {
		items = append(items, toGraphMessage(msg))
	}
	return &gqlmodel.MessagePage{Items: items, HasMoreBefore: page.HasMoreBefore, HasMoreAfter: page.HasMoreAfter}, nil
}

// Room is the resolver for the room field.
func (r *queryResolver) Room(ctx context.Context, id string) (*gqlmodel.Room, error) {
	// 認証は requireRoomReadAccess（ChatAccess.EnsureReadAccess）側でも行われるが、
	// この後のブロック判定で claims.ID が要るので claims も受け取っておく。
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	rid, err := decodeGraphID(ctx, "room", id)
	if err != nil {
		return nil, fmt.Errorf("invalid room id")
	}

	// 閲覧可否の判定は messages クエリや各サブスクリプションと同じ
	// ChatAccess.EnsureReadAccess に揃える（ルームを返すので GetRoomUseCase は不要）。
	// 以前ここだけは「管理者なら DM でも閲覧可」という独自分岐を持っていたが、同じ
	// 部屋に対して room は取れるのに messages は取れないという食い違いが出るため、
	// EnsureReadAccess 側の規則（DM は管理者でも membership 必須）へ寄せた。
	room, err := r.requireRoomReadAccess(ctx, rid)
	if err != nil {
		return nil, err
	}

	gqlRoom := toGraphRoom(room)

	// ここから下は「要求されたときだけ引く」付帯情報。閲覧可否の判定
	// （requireRoomReadAccess）はこの上で必ず済ませてあるので、遅らせても
	// 権限判定より先に DB を触ることはない。既読もブロックも「権限判定済みの
	// room」を前提にした口を使っているため、判定の順序はこの形でないと崩れる。
	//
	// メンバー一覧は user フィールドだけでなく isMessagingDisabled（DM の相手を
	// 特定するため）も使うので、どちらかが選ばれていれば引く。
	wantMembers := fieldRequested(ctx, "user")
	wantMessagingDisabled := fieldRequested(ctx, "isMessagingDisabled")

	var users []*model.User
	if wantMembers || wantMessagingDisabled {
		usersByRoomID, err := r.ListUsersByRoomIDsUseCase.Execute(ctx, []int64{rid})
		if err != nil {
			return nil, fmt.Errorf("failed to load room members")
		}
		users = usersByRoomID[rid]
	}

	if wantMembers {
		members := make([]*gqlmodel.User, 0, len(users))
		for _, u := range users {
			members = append(members, toGraphUser(u))
		}
		gqlRoom.User = members
	}

	// 入力欄を閉じるのは DM だけ。AccessPolicy.ensureWriteAccessFor のブロック判定と
	// 同じ規則に揃える（画面の状態と実際の送信可否が食い違わないようにするため）。
	// 相手が1人に決まらない DM ではブロックを引けないので、向こうと同じく判定しない。
	gqlRoom.IsMessagingDisabled = false
	if wantMessagingDisabled && room.Type == model.RoomTypeDM {
		partnerID, ok := dmPartnerID(users, claims.ID)
		if ok {
			// 引けなかったときは従来どおり「ブロックなし」として入力欄を開けたままにする。
			// 実際に送ろうとすれば AccessPolicy 側のブロック判定で弾かれるので通ることは
			// ないが、入力欄の状態だけが食い違うので失敗は残す。
			isBlocked, err := r.CheckBlockRelationUseCase.Execute(ctx, partnerID)
			if err != nil {
				logChatLookup(err, chatLookupBlockRelation).
					Int64("room_id", rid).
					Int64("partner_id", partnerID).
					Msg("failed to check the block relation; leaving messaging enabled")
			}
			gqlRoom.IsMessagingDisabled = isBlocked
		}
	}

	// 既読位置の置き場（授業内チャットは course_room_reads、それ以外は room_users）の
	// 切り分けは ChatReads 側にある。
	//
	// 既読の取得に失敗してもルーム自体は返す。既読はルーム画面の付帯情報で、
	// ここで room ごと失敗させるとチャットが開けなくなる（本体より軽い情報のために
	// 本体を落とさない）。ただし画面上は「未読0・未読み」と区別がつかないので、
	// 黙って落とさず必ずログに残す。DB 障害が正常表示に化けて気づけない、という
	// 状態を作らないため。
	// 閲覧権限は requireRoomReadAccess で判定済みなので、その room をそのまま渡す
	// 口を使う（GetReadStatus を呼ぶとルームと membership の取得がもう一度走る）。
	if roomReadStatusRequested(ctx) {
		readStatus, err := r.ChatReads.ReadStatusOfAuthorizedRoom(ctx, room)
		if err != nil {
			logChatLookup(err, chatLookupReadStatus).
				Int64("room_id", rid).
				Int64("user_id", claims.ID).
				Msg("failed to load read status; returning the room without it")
		} else {
			applyRoomReadStatus(gqlRoom, readStatus)
		}
	}

	return gqlRoom, nil
}

// MyDMRooms is the resolver for the myDMRooms field.
func (r *queryResolver) MyDMRooms(ctx context.Context, limit *int32, offset *int32) (*gqlmodel.RoomPage, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	rooms, total, err := r.ListMyDMRoomsUseCase.Execute(ctx, resolvePageQuery(ctx, limit, offset, defaultPageSize))
	if err != nil {
		return nil, err
	}

	roomIDs := make([]int64, 0, len(rooms))
	for _, room := range rooms {
		roomIDs = append(roomIDs, room.ID)
	}

	// room クエリと同じで、ここから下は「要求されたときだけ引く」付帯情報。
	// 一覧に載せてよいルームかどうかは ListMyDMRooms（自分が入っている DM だけ）で
	// 絞り済みなので、付帯情報を遅らせても権限判定の順序は変わらない。
	//
	// メンバー一覧は user と isMessagingDisabled の両方が使う（相手の特定と
	// 「退会済みで自分しか居ない」の判定）ので、どちらかが選ばれていれば引く。
	wantMembers := fieldRequested(ctx, "items", "user")
	wantMessagingDisabled := fieldRequested(ctx, "items", "isMessagingDisabled")

	usersByRoomID := map[int64][]*model.User{}
	if wantMembers || wantMessagingDisabled {
		usersByRoomID, err = r.ListUsersByRoomIDsUseCase.Execute(ctx, roomIDs)
		if err != nil {
			return nil, fmt.Errorf("failed to load room members")
		}
	}

	// ブロック一覧が引けないと、ブロック相手の DM が「ブロックなし」の見た目で並ぶ。
	// 一覧ごと落とすほどではないので続けるが、黙って落とすと気づけないので残す。
	blockedSet := map[int64]bool{}
	if wantMessagingDisabled {
		blockedSet, err = r.GetBlockRelatedUserIDsUseCase.Execute(ctx)
		if err != nil {
			logChatLookup(err, chatLookupBlockedUserIDs).
				Int64("user_id", claims.ID).
				Msg("failed to load blocked user ids; returning the DM rooms without block marks")
		}
	}

	// 既読の取得に失敗しても一覧は返す（未読バッジは一覧の付帯情報で、そのために
	// DM 一覧ごと落とさない）。ただし画面上は「未読0」と区別がつかないので、
	// room リゾルバと同じく必ずログに残す。
	readStatusMap := map[int64]*roomusecase.RoomReadStatus{}
	if roomReadStatusRequested(ctx, "items") {
		readStatusMap, err = r.GetRoomReadStatusBatchUseCase.Execute(ctx, roomIDs, claims.ID, model.RoomTypeDM)
		if err != nil {
			logChatLookup(err, chatLookupReadStatusBatch).
				Int64("user_id", claims.ID).
				Int("rooms", len(roomIDs)).
				Msg("failed to load read statuses; returning the DM rooms without unread counts")
		}
	}

	// 最新メッセージ（一覧のプレビュー）も同じ扱い。取れなければ空欄で出す。
	// Room の content がプレビューの置き場（Community 側は lastMessage）。
	lastMessageMap := map[int64]*model.Message{}
	if fieldRequested(ctx, "items", "content") {
		lastMessageMap, err = r.GetLastMessagesByRoomIDsUseCase.Execute(ctx, roomIDs)
		if err != nil {
			logChatLookup(err, chatLookupLastMessages).
				Int64("user_id", claims.ID).
				Int("rooms", len(roomIDs)).
				Msg("failed to load last messages; returning the DM rooms without previews")
		}
	}

	result := make([]*gqlmodel.Room, 0, len(rooms))
	for _, room := range rooms {
		users := usersByRoomID[room.ID]
		hasOnlyCurrentUser := len(users) == 1 && users[0].ID == claims.ID

		gqlRoom := toGraphRoom(room)

		if wantMembers {
			members := make([]*gqlmodel.User, 0, len(users))
			for _, u := range users {
				members = append(members, toGraphUser(u))
			}
			if hasOnlyCurrentUser {
				members = []*gqlmodel.User{toGraphDeletedUser(), members[0]}
			}
			gqlRoom.User = members
		}

		if wantMessagingDisabled {
			// 相手が退会済み（自分しか居ない）なら送信不可。それ以外は相手が1人に決まる
			// DM のときだけブロックを見る。ここは myDMRooms なので room.Type は DM のはず
			// だが、人数から DM を推測しないという規則を一覧側でも崩さないために明示する。
			partnerID, hasPartner := dmPartnerID(users, claims.ID)
			gqlRoom.IsMessagingDisabled = hasOnlyCurrentUser ||
				(room.Type == model.RoomTypeDM && hasPartner && blockedSet[partnerID])
		}

		if lastMsg := lastMessageMap[room.ID]; lastMsg != nil {
			gqlRoom.Content = &lastMsg.Content
		}

		applyRoomReadStatus(gqlRoom, readStatusMap[room.ID])

		result = append(result, gqlRoom)
	}

	return &gqlmodel.RoomPage{Items: result, Total: int32(total)}, nil
}

// MessageAdded is the resolver for the messageAdded field.
func (r *subscriptionResolver) MessageAdded(ctx context.Context, roomID string) (<-chan *gqlmodel.Message, error) {
	return r.messageSubscription(ctx, roomID, roomID+":message:added")
}

// MessageDeleted is the resolver for the messageDeleted field.
func (r *subscriptionResolver) MessageDeleted(ctx context.Context, roomID string) (<-chan *gqlmodel.Message, error) {
	return r.messageSubscription(ctx, roomID, roomID+":message:deleted")
}

// MessageUpdated is the resolver for the messageUpdated field.
func (r *subscriptionResolver) MessageUpdated(ctx context.Context, roomID string) (<-chan *gqlmodel.Message, error) {
	return r.messageSubscription(ctx, roomID, roomID+":message:updated")
}

// RoomReadStatusUpdated is the resolver for the roomReadStatusUpdated field.
func (r *subscriptionResolver) RoomReadStatusUpdated(ctx context.Context, roomID string) (<-chan *gqlmodel.RoomReadStatusUpdate, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	rid, err := decodeGraphID(ctx, "room", roomID)
	if err != nil {
		return nil, fmt.Errorf("invalid room id")
	}

	// 既読状況の購読もメッセージ本体と同じ閲覧可否で守る。判定は
	// ChatAccess.EnsureReadAccess の1本だけ（以前はここに同じ分岐を写経していた）。
	if _, err := r.requireRoomReadAccess(ctx, rid); err != nil {
		return nil, err
	}

	currentUserGraphID := encodeGraphID("user", claims.ID)
	return subscribeTopicGuarded(
		ctx,
		r.PubSub,
		roomID+":read_status",
		subscriptionScope{UserID: claims.ID, RoomID: roomID},
		// 既読状況も「誰がどこまで読んだか」というルームの情報なので、
		// メッセージ本体と同じく購読中も権限を確かめ直す。
		r.roomReadGuard(rid),
		func(update *gqlmodel.RoomReadStatusUpdate) (*gqlmodel.RoomReadStatusUpdate, bool) {
			// 自分の読み取りイベントは除外し、相手のものだけ配信
			return update, update.UserID != currentUserGraphID
		},
	), nil
}

// Message returns MessageResolver implementation.
func (r *Resolver) Message() MessageResolver { return &messageResolver{r} }

type messageResolver struct{ *Resolver }
