package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"
	"time"

	gqlmodel "github.com/Cityboypenguin/SPACE-server/graph/model"
	"github.com/Cityboypenguin/SPACE-server/internal/dataloader"
	pollusecase "github.com/Cityboypenguin/SPACE-server/usecase/poll"
)

// User is the resolver for the user field.
func (r *answerResolver) User(ctx context.Context, obj *gqlmodel.Answer) (*gqlmodel.User, error) {
	numericUserID, err := decodeGraphID(ctx, "user", obj.User.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %s", obj.User.ID)
	}

	// 回答は質問を経由しないとルームが分からないので、匿名表示の判定に質問を引く。
	// 引けないと授業ルームでも実名で出てしまうため、失敗は必ず残す
	// （ID のデコード失敗は audit.LogProbe が既に記録している）。
	//
	// 質問は DataLoader 経由。1つの質問にぶら下がる回答は全て同じ質問を指すので、
	// 新しいクエリが増えるのではなくリクエスト内キャッシュで1回に畳まれる
	// （回答一覧 N 件で N クエリ → 1クエリ）。
	qid, err := decodeGraphID(ctx, "question", obj.QuestionID)
	if err == nil {
		q, err := dataloader.For(ctx).QuestionLoader.Load(ctx, qid)
		if err != nil {
			logChatLookup(err, chatLookupQuestionRoom).
				Int64("question_id", qid).
				Int64("author_user_id", numericUserID).
				Msg("failed to load the question; falling back to showing the real user")
		} else if q != nil {
			roomIDStr := encodeGraphID("room", q.RoomID)
			if anon := r.anonymousUserForCourseRoom(ctx, roomIDStr, numericUserID); anon != nil {
				return anon, nil
			}
		}
	}

	u, err := dataloader.For(ctx).UserLoader.Load(ctx, numericUserID)
	if err != nil || u == nil {
		return nil, err
	}
	return toGraphUser(u), nil
}

// Media is the resolver for the media field.
func (r *answerResolver) Media(ctx context.Context, obj *gqlmodel.Answer) ([]*gqlmodel.Media, error) {
	numericID, err := decodeGraphID(ctx, "answer", obj.ID)
	if err != nil {
		return nil, nil
	}
	mediaList, err := dataloader.For(ctx).AnswerMediaLoader.Load(ctx, numericID)
	if err != nil {
		return nil, err
	}
	var result []*gqlmodel.Media
	for _, m := range mediaList {
		result = append(result, toGraphMedia(m, r.StorageRepository.PublicURL(m.StorageKey)))
	}
	return result, nil
}

// IsMine is the resolver for the isMine field.
func (r *answerResolver) IsMine(ctx context.Context, obj *gqlmodel.Answer) (bool, error) {
	return isCallerID(ctx, obj.User.ID), nil
}

// CreateQuestion is the resolver for the createQuestion field.
func (r *mutationResolver) CreateQuestion(ctx context.Context, roomID string, body string, mediaInputs []*gqlmodel.MediaUploadInput) (*gqlmodel.Question, error) {
	rid, err := decodeGraphID(ctx, "room", roomID)
	if err != nil {
		return nil, fmt.Errorf("invalid room id")
	}

	ucMediaInputs := r.toMediaInputs(mediaInputs)

	q, err := r.CreateQuestionUseCase.Execute(ctx, rid, body, ucMediaInputs)
	if err != nil {
		return nil, err
	}

	// 配信はユースケース側（usecase/question の EventPublisher）が出す。
	return toGraphQuestion(q), nil
}

// UpdateQuestion is the resolver for the updateQuestion field.
func (r *mutationResolver) UpdateQuestion(ctx context.Context, id string, body string, deletedMediaIDs []string) (*gqlmodel.Question, error) {
	qid, err := decodeGraphID(ctx, "question", id)
	if err != nil {
		return nil, fmt.Errorf("invalid question id")
	}

	mediaIDs := make([]int64, 0, len(deletedMediaIDs))
	for _, strID := range deletedMediaIDs {
		mediaID, err := decodeGraphID(ctx, "media", strID)
		if err != nil {
			return nil, fmt.Errorf("invalid media id")
		}
		mediaIDs = append(mediaIDs, mediaID)
	}

	q, err := r.UpdateQuestionUseCase.Execute(ctx, qid, body, mediaIDs)
	if err != nil {
		return nil, err
	}

	return toGraphQuestion(q), nil
}

// DeleteQuestion is the resolver for the deleteQuestion field.
func (r *mutationResolver) DeleteQuestion(ctx context.Context, id string) (bool, error) {
	qid, err := decodeGraphID(ctx, "question", id)
	if err != nil {
		return false, fmt.Errorf("invalid question id")
	}

	if _, err := r.DeleteMyQuestionUseCase.Execute(ctx, qid); err != nil {
		return false, err
	}
	return true, nil
}

// AnswerQuestion is the resolver for the answerQuestion field.
func (r *mutationResolver) AnswerQuestion(ctx context.Context, questionID string, body string, mediaInputs []*gqlmodel.MediaUploadInput) (*gqlmodel.Answer, error) {
	qid, err := decodeGraphID(ctx, "question", questionID)
	if err != nil {
		return nil, fmt.Errorf("invalid question id")
	}

	ucMediaInputs := r.toMediaInputs(mediaInputs)

	a, err := r.AnswerQuestionUseCase.Execute(ctx, qid, body, ucMediaInputs)
	if err != nil {
		return nil, err
	}

	return toGraphAnswer(a), nil
}

// UpdateAnswer is the resolver for the updateAnswer field.
func (r *mutationResolver) UpdateAnswer(ctx context.Context, id string, body string, deletedMediaIDs []string) (*gqlmodel.Answer, error) {
	aid, err := decodeGraphID(ctx, "answer", id)
	if err != nil {
		return nil, fmt.Errorf("invalid answer id")
	}

	mediaIDs := make([]int64, 0, len(deletedMediaIDs))
	for _, strID := range deletedMediaIDs {
		mediaID, err := decodeGraphID(ctx, "media", strID)
		if err != nil {
			return nil, fmt.Errorf("invalid media id")
		}
		mediaIDs = append(mediaIDs, mediaID)
	}

	aw, err := r.UpdateAnswerUseCase.Execute(ctx, aid, body, mediaIDs)
	if err != nil {
		return nil, err
	}

	gqlA := toGraphAnswerWithLikes(aw)
	return gqlA, nil
}

// DeleteAnswer is the resolver for the deleteAnswer field.
func (r *mutationResolver) DeleteAnswer(ctx context.Context, id string) (bool, error) {
	aid, err := decodeGraphID(ctx, "answer", id)
	if err != nil {
		return false, fmt.Errorf("invalid answer id")
	}

	if _, err := r.DeleteAnswerUseCase.Execute(ctx, aid); err != nil {
		return false, err
	}
	return true, nil
}

// LikeAnswer is the resolver for the likeAnswer field.
func (r *mutationResolver) LikeAnswer(ctx context.Context, id string) (*gqlmodel.Answer, error) {
	aid, err := decodeGraphID(ctx, "answer", id)
	if err != nil {
		return nil, fmt.Errorf("invalid answer id")
	}

	aw, err := r.LikeAnswerUseCase.Execute(ctx, aid)
	if err != nil {
		return nil, err
	}

	gqlA := toGraphAnswerWithLikes(aw)
	return gqlA, nil
}

// UnlikeAnswer is the resolver for the unlikeAnswer field.
func (r *mutationResolver) UnlikeAnswer(ctx context.Context, id string) (*gqlmodel.Answer, error) {
	aid, err := decodeGraphID(ctx, "answer", id)
	if err != nil {
		return nil, fmt.Errorf("invalid answer id")
	}

	aw, err := r.UnlikeAnswerUseCase.Execute(ctx, aid)
	if err != nil {
		return nil, err
	}

	gqlA := toGraphAnswerWithLikes(aw)
	return gqlA, nil
}

// SelectBestAnswer is the resolver for the selectBestAnswer field.
func (r *mutationResolver) SelectBestAnswer(ctx context.Context, questionID string, answerID string) (*gqlmodel.Question, error) {
	qid, err := decodeGraphID(ctx, "question", questionID)
	if err != nil {
		return nil, fmt.Errorf("invalid question id")
	}
	aid, err := decodeGraphID(ctx, "answer", answerID)
	if err != nil {
		return nil, fmt.Errorf("invalid answer id")
	}

	q, err := r.SelectBestAnswerUseCase.Execute(ctx, qid, aid)
	if err != nil {
		return nil, err
	}

	return toGraphQuestion(q), nil
}

// CancelBestAnswer is the resolver for the cancelBestAnswer field.
func (r *mutationResolver) CancelBestAnswer(ctx context.Context, questionID string) (*gqlmodel.Question, error) {
	qid, err := decodeGraphID(ctx, "question", questionID)
	if err != nil {
		return nil, fmt.Errorf("invalid question id")
	}

	q, err := r.CancelBestAnswerUseCase.Execute(ctx, qid)
	if err != nil {
		return nil, err
	}

	return toGraphQuestion(q), nil
}

// CreatePoll is the resolver for the createPoll field.
func (r *mutationResolver) CreatePoll(ctx context.Context, roomID string, question string, options []string, allowMultipleChoice *bool, deadline *string) (*gqlmodel.Poll, error) {
	rid, err := decodeGraphID(ctx, "room", roomID)
	if err != nil {
		return nil, fmt.Errorf("invalid room id")
	}

	amc := false
	if allowMultipleChoice != nil {
		amc = *allowMultipleChoice
	}

	var dl *time.Time
	if deadline != nil {
		parsed, err := time.Parse(timeFormat, *deadline)
		if err != nil {
			return nil, fmt.Errorf("invalid deadline")
		}
		dl = &parsed
	}

	p, err := r.CreatePollUseCase.Execute(ctx, rid, question, options, amc, dl)
	if err != nil {
		return nil, err
	}

	gqlP := toGraphPoll(p)
	return gqlP, nil
}

// VotePoll is the resolver for the votePoll field.
func (r *mutationResolver) VotePoll(ctx context.Context, pollID string, optionIDs []string) (*gqlmodel.Poll, error) {
	pid, err := decodeGraphID(ctx, "poll", pollID)
	if err != nil {
		return nil, fmt.Errorf("invalid poll id")
	}

	oids := make([]int64, 0, len(optionIDs))
	for _, oidStr := range optionIDs {
		oid, err := decodeGraphID(ctx, "pollOption", oidStr)
		if err != nil {
			return nil, fmt.Errorf("invalid poll option id")
		}
		oids = append(oids, oid)
	}

	p, err := r.VotePollUseCase.Execute(ctx, pid, oids)
	if err != nil {
		return nil, err
	}

	gqlP := toGraphPoll(p)
	return gqlP, nil
}

// DeletePoll is the resolver for the deletePoll field.
func (r *mutationResolver) DeletePoll(ctx context.Context, pollID string) (bool, error) {
	pid, err := decodeGraphID(ctx, "poll", pollID)
	if err != nil {
		return false, fmt.Errorf("invalid poll id")
	}

	if _, err := r.DeletePollUseCase.Execute(ctx, pid); err != nil {
		return false, err
	}
	return true, nil
}

// User is the resolver for the user field.
func (r *pollResolver) User(ctx context.Context, obj *gqlmodel.Poll) (*gqlmodel.User, error) {
	numericUserID, err := decodeGraphID(ctx, "user", obj.User.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %s", obj.User.ID)
	}

	if anon := r.anonymousUserForCourseRoom(ctx, obj.RoomID, numericUserID); anon != nil {
		// 投票の「先生からの投票」表示のため、匿名化しつつも role だけは実ユーザーのものを
		// 引き継ぐ(name/avatarUrl/ID等は匿名IDのまま個人を特定できないようにする)。
		//
		// 引けなくても匿名表示のまま返す（role が既定値になるだけで匿名性は壊れない）。
		// ただし「先生からの投票」バッジが黙って消えるのは気づきにくいのでログに残す。
		u, err := dataloader.For(ctx).UserLoader.Load(ctx, numericUserID)
		if err != nil {
			logChatLookup(err, chatLookupPollAuthorRole).
				Str("poll_id", obj.ID).
				Int64("author_user_id", numericUserID).
				Msg("failed to load the poll author; the role badge falls back to the default")
		} else if u != nil {
			anon.Role = u.Role
		}
		return anon, nil
	}

	u, err := dataloader.For(ctx).UserLoader.Load(ctx, numericUserID)
	if err != nil || u == nil {
		return nil, err
	}
	return toGraphUser(u), nil
}

// Options is the resolver for the options field.
func (r *pollResolver) Options(ctx context.Context, obj *gqlmodel.Poll) ([]*gqlmodel.PollOption, error) {
	pid, err := decodeGraphID(ctx, "poll", obj.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid poll id")
	}

	// 投票一覧では投票ごとにこのフィールドが呼ばれるので DataLoader 経由で引く
	//（投票 N 件で N クエリ → 1クエリ）。選択肢が無い投票は nil スライスが返り、
	// 単体取得のときと同じ「空配列」になる。
	results, err := dataloader.For(ctx).PollOptionLoader.Load(ctx, pid)
	if err != nil {
		return nil, err
	}

	out := make([]*gqlmodel.PollOption, 0, len(results))
	for _, res := range results {
		out = append(out, toGraphPollOption(res))
	}
	return out, nil
}

// VoterCount is the resolver for the voterCount field.
func (r *pollResolver) VoterCount(ctx context.Context, obj *gqlmodel.Poll) (int32, error) {
	pid, err := decodeGraphID(ctx, "poll", obj.ID)
	if err != nil {
		return 0, fmt.Errorf("invalid poll id")
	}

	// options と同じ理由で DataLoader 経由（投票 N 件で N クエリ → 1クエリ）。
	// 誰も投票していない投票はバッチの map に現れないが、int のゼロ値が
	// そのまま正しい「0人」になる。
	count, err := dataloader.For(ctx).PollVoterCountLoader.Load(ctx, pid)
	if err != nil {
		return 0, err
	}
	return int32(count), nil
}

// IsMine is the resolver for the isMine field.
func (r *pollResolver) IsMine(ctx context.Context, obj *gqlmodel.Poll) (bool, error) {
	return isCallerID(ctx, obj.User.ID), nil
}

// Questions is the resolver for the questions field.
func (r *queryResolver) Questions(ctx context.Context, roomID string, limit *int32, offset *int32) (*gqlmodel.QuestionPage, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}

	rid, err := decodeGraphID(ctx, "room", roomID)
	if err != nil {
		return nil, fmt.Errorf("invalid room id")
	}
	if _, err := r.requireRoomReadAccess(ctx, rid); err != nil {
		return nil, err
	}

	items, total, err := r.ListQuestionsUseCase.Execute(ctx, rid, resolvePageQuery(ctx, limit, offset, defaultPageSize))
	if err != nil {
		return nil, err
	}

	gqlItems := make([]*gqlmodel.Question, 0, len(items))
	for _, q := range items {
		gqlItems = append(gqlItems, toGraphQuestion(q))
	}
	return &gqlmodel.QuestionPage{Items: gqlItems, Total: int32(total)}, nil
}

// Question is the resolver for the question field.
func (r *queryResolver) Question(ctx context.Context, id string) (*gqlmodel.Question, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}

	qid, err := decodeGraphID(ctx, "question", id)
	if err != nil {
		return nil, fmt.Errorf("invalid question id")
	}

	q, err := r.GetQuestionByIDUseCase.Execute(ctx, qid)
	if err != nil || q == nil {
		return nil, err
	}
	if _, err := r.requireRoomReadAccess(ctx, q.RoomID); err != nil {
		return nil, err
	}

	return toGraphQuestion(q), nil
}

// Polls is the resolver for the polls field.
func (r *queryResolver) Polls(ctx context.Context, roomID string, limit *int32, offset *int32) (*gqlmodel.PollPage, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}

	rid, err := decodeGraphID(ctx, "room", roomID)
	if err != nil {
		return nil, fmt.Errorf("invalid room id")
	}
	if _, err := r.requireRoomReadAccess(ctx, rid); err != nil {
		return nil, err
	}

	items, total, unvotedTotal, err := r.ListPollsUseCase.Execute(ctx, rid, pollusecase.ListPollsQuery{
		Page:             resolvePageQuery(ctx, limit, offset, 50),
		WithUnvotedTotal: fieldRequested(ctx, "unvotedTotal"),
	})
	if err != nil {
		return nil, err
	}

	gqlItems := make([]*gqlmodel.Poll, 0, len(items))
	for _, p := range items {
		gqlItems = append(gqlItems, toGraphPoll(p))
	}
	return &gqlmodel.PollPage{Items: gqlItems, Total: int32(total), UnvotedTotal: int32(unvotedTotal)}, nil
}

// Poll is the resolver for the poll field.
func (r *queryResolver) Poll(ctx context.Context, id string) (*gqlmodel.Poll, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}

	pid, err := decodeGraphID(ctx, "poll", id)
	if err != nil {
		return nil, fmt.Errorf("invalid poll id")
	}

	p, err := r.GetPollByIDUseCase.Execute(ctx, pid)
	if err != nil || p == nil {
		return nil, err
	}
	if _, err := r.requireRoomReadAccess(ctx, p.RoomID); err != nil {
		return nil, err
	}

	return toGraphPoll(p), nil
}

// User is the resolver for the user field.
func (r *questionResolver) User(ctx context.Context, obj *gqlmodel.Question) (*gqlmodel.User, error) {
	numericUserID, err := decodeGraphID(ctx, "user", obj.User.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %s", obj.User.ID)
	}

	if anon := r.anonymousUserForCourseRoom(ctx, obj.RoomID, numericUserID); anon != nil {
		return anon, nil
	}

	u, err := dataloader.For(ctx).UserLoader.Load(ctx, numericUserID)
	if err != nil || u == nil {
		return nil, err
	}
	return toGraphUser(u), nil
}

// BestAnswer is the resolver for the bestAnswer field.
func (r *questionResolver) BestAnswer(ctx context.Context, obj *gqlmodel.Question) (*gqlmodel.Answer, error) {
	if obj.BestAnswer == nil {
		return nil, nil
	}
	aid, err := decodeGraphID(ctx, "answer", obj.BestAnswer.ID)
	if err != nil {
		return nil, nil
	}
	// 質問一覧では質問ごとにこのフィールドが呼ばれるので DataLoader 経由で引く
	//（質問 N 件で N クエリ → 1クエリ）。
	a, err := dataloader.For(ctx).AnswerLoader.Load(ctx, aid)
	if err != nil || a == nil {
		return nil, err
	}
	return toGraphAnswerWithLikes(a), nil
}

// Answers is the resolver for the answers field.
func (r *questionResolver) Answers(ctx context.Context, obj *gqlmodel.Question, limit *int32, offset *int32) (*gqlmodel.AnswerPage, error) {
	qid, err := decodeGraphID(ctx, "question", obj.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid question id")
	}

	// 質問一覧では質問ごとにこのフィールドが呼ばれ、しかも1件あたり
	// 一覧 + COUNT の2クエリだった（質問 N 件で 2N クエリ → 2クエリ）。
	// limit/offset もキーに含める（同じ質問でも件数が違えば別の結果なので、
	// ID だけをキーにすると先に来た方のページを使い回してしまう）。
	page, err := dataloader.For(ctx).AnswerPageLoader.Load(ctx, dataloader.AnswerPageKey{
		QuestionID: qid,
		Page:       resolvePageQuery(ctx, limit, offset, defaultPageSize),
	})
	if err != nil {
		return nil, err
	}
	if page == nil {
		// バッチは回答ゼロの質問にも空ページを返すので通常ここには来ない。
		// 来たとしても「回答なし」として従来と同じ形を返す。
		return &gqlmodel.AnswerPage{Items: []*gqlmodel.Answer{}, Total: 0}, nil
	}

	items := make([]*gqlmodel.Answer, 0, len(page.Items))
	for _, a := range page.Items {
		items = append(items, toGraphAnswerWithLikes(a))
	}
	return &gqlmodel.AnswerPage{Items: items, Total: int32(page.Total)}, nil
}

// Answers is the resolver for the answers field.
// AnswerCount is the resolver for the answerCount field on Question.
//
// 件数だけを出す画面（管理画面の質問一覧）が answers を選ばずに済むようにするための
// フィールド。COUNT(*) 1本で、回答の本文も投稿者も運ばない。
func (r *questionResolver) AnswerCount(ctx context.Context, obj *gqlmodel.Question) (int32, error) {
	qid, err := decodeGraphID(ctx, "question", obj.ID)
	if err != nil {
		return 0, fmt.Errorf("invalid question id")
	}

	count, err := dataloader.For(ctx).AnswerCountLoader.Load(ctx, qid)
	if err != nil {
		return 0, err
	}
	return int32(count), nil
}

// Media is the resolver for the media field.
func (r *questionResolver) Media(ctx context.Context, obj *gqlmodel.Question) ([]*gqlmodel.Media, error) {
	numericID, err := decodeGraphID(ctx, "question", obj.ID)
	if err != nil {
		return nil, nil
	}
	mediaList, err := dataloader.For(ctx).QuestionMediaLoader.Load(ctx, numericID)
	if err != nil {
		return nil, err
	}
	var result []*gqlmodel.Media
	for _, m := range mediaList {
		result = append(result, toGraphMedia(m, r.StorageRepository.PublicURL(m.StorageKey)))
	}
	return result, nil
}

// IsMine is the resolver for the isMine field.
func (r *questionResolver) IsMine(ctx context.Context, obj *gqlmodel.Question) (bool, error) {
	return isCallerID(ctx, obj.User.ID), nil
}

// QuestionAdded is the resolver for the questionAdded field.
func (r *subscriptionResolver) QuestionAdded(ctx context.Context, roomID string) (<-chan *gqlmodel.Question, error) {
	return r.questionSubscription(ctx, roomID, roomID+":question:added")
}

// QuestionUpdated is the resolver for the questionUpdated field.
func (r *subscriptionResolver) QuestionUpdated(ctx context.Context, roomID string) (<-chan *gqlmodel.Question, error) {
	return r.questionSubscription(ctx, roomID, roomID+":question:updated")
}

// QuestionDeleted is the resolver for the questionDeleted field.
func (r *subscriptionResolver) QuestionDeleted(ctx context.Context, roomID string) (<-chan *gqlmodel.Question, error) {
	return r.questionSubscription(ctx, roomID, roomID+":question:deleted")
}

// AnswerAdded is the resolver for the answerAdded field.
func (r *subscriptionResolver) AnswerAdded(ctx context.Context, questionID string) (<-chan *gqlmodel.Answer, error) {
	return r.answerSubscription(ctx, questionID, questionID+":answer:added")
}

// AnswerUpdated is the resolver for the answerUpdated field.
func (r *subscriptionResolver) AnswerUpdated(ctx context.Context, questionID string) (<-chan *gqlmodel.Answer, error) {
	return r.answerSubscription(ctx, questionID, questionID+":answer:updated")
}

// AnswerDeleted is the resolver for the answerDeleted field.
func (r *subscriptionResolver) AnswerDeleted(ctx context.Context, questionID string) (<-chan *gqlmodel.Answer, error) {
	return r.answerSubscription(ctx, questionID, questionID+":answer:deleted")
}

// PollAdded is the resolver for the pollAdded field.
func (r *subscriptionResolver) PollAdded(ctx context.Context, roomID string) (<-chan *gqlmodel.Poll, error) {
	return r.roomPollSubscription(ctx, roomID, roomID+":poll:added")
}

// PollUpdated is the resolver for the pollUpdated field.
func (r *subscriptionResolver) PollUpdated(ctx context.Context, pollID string) (<-chan *gqlmodel.Poll, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	pid, err := decodeGraphID(ctx, "poll", pollID)
	if err != nil {
		return nil, fmt.Errorf("invalid poll id")
	}
	p, err := r.GetPollByIDUseCase.Execute(ctx, pid)
	if err != nil {
		return nil, err
	}
	if p == nil {
		return nil, fmt.Errorf("poll not found")
	}
	if _, err := r.requireRoomReadAccess(ctx, p.RoomID); err != nil {
		return nil, err
	}

	return subscribeTopicGuarded(ctx, r.PubSub, pollID+":poll:updated",
		subscriptionScope{UserID: claims.ID, RoomID: encodeGraphID("room", p.RoomID)},
		r.roomReadGuard(p.RoomID),
		func(poll *gqlmodel.Poll) (*gqlmodel.Poll, bool) { return poll, true },
	), nil
}

// PollDeleted is the resolver for the pollDeleted field.
func (r *subscriptionResolver) PollDeleted(ctx context.Context, roomID string) (<-chan *gqlmodel.Poll, error) {
	return r.roomPollSubscription(ctx, roomID, roomID+":poll:deleted")
}

// Answer returns AnswerResolver implementation.
func (r *Resolver) Answer() AnswerResolver { return &answerResolver{r} }

// Poll returns PollResolver implementation.
func (r *Resolver) Poll() PollResolver { return &pollResolver{r} }

// Question returns QuestionResolver implementation.
func (r *Resolver) Question() QuestionResolver { return &questionResolver{r} }

type (
	answerResolver   struct{ *Resolver }
	pollResolver     struct{ *Resolver }
	questionResolver struct{ *Resolver }
)
