package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"
	"fmt"

	gqlmodel "github.com/Cityboypenguin/SPACE-server/graph/model"
	"github.com/Cityboypenguin/SPACE-server/model"
	"github.com/Cityboypenguin/SPACE-server/repository"
	communityusecase "github.com/Cityboypenguin/SPACE-server/usecase/community"
	roomusecase "github.com/Cityboypenguin/SPACE-server/usecase/room"
)

// CreateCommunity is the resolver for the createCommunity field.
func (r *mutationResolver) CreateCommunity(ctx context.Context, input gqlmodel.CreateCommunityInput) (*gqlmodel.Community, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	c, err := r.CreateCommunityUseCase.Execute(ctx, input.Name, input.Description, input.AvatarKey)
	if err != nil {
		return nil, err
	}
	if c == nil {
		return nil, errors.New("community creation returned no community")
	}

	membership, err := r.loadCommunityMembership(ctx, []int64{c.RoomID}, &claims.ID,
		fieldRequested(ctx, "memberCount"), fieldRequested(ctx, "isMember"))
	if err != nil {
		return nil, err
	}
	return r.toGraphCommunityWith(c, membership), nil
}

// UpdateCommunity is the resolver for the updateCommunity field.
func (r *mutationResolver) UpdateCommunity(ctx context.Context, id string, input gqlmodel.UpdateCommunityInput) (*gqlmodel.Community, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	numericID, err := decodeGraphID(ctx, "community", id)
	if err != nil {
		return nil, fmt.Errorf("invalid community id")
	}

	c, err := r.UpdateCommunityUseCase.Execute(ctx, numericID, communityusecase.UpdateCommunityParam{
		Name:        input.Name,
		Description: input.Description,
		AvatarKey:   input.AvatarKey,
	})
	if err != nil {
		return nil, err
	}

	membership, err := r.loadCommunityMembership(ctx, []int64{c.RoomID}, &claims.ID,
		fieldRequested(ctx, "memberCount"), fieldRequested(ctx, "isMember"))
	if err != nil {
		return nil, err
	}
	return r.toGraphCommunityWith(c, membership), nil
}

// KickUserFromCommunity is the resolver for the kickUserFromCommunity field.
func (r *mutationResolver) KickUserFromCommunity(ctx context.Context, communityID string, userID string) (bool, error) {
	if _, err := requireAuth(ctx); err != nil {
		return false, err
	}

	numericCommunityID, err := decodeGraphID(ctx, "community", communityID)
	if err != nil {
		return false, fmt.Errorf("invalid community id")
	}

	numericUserID, err := decodeGraphID(ctx, "user", userID)
	if err != nil {
		return false, fmt.Errorf("invalid user id")
	}

	if err := r.updateCommunityMembers(ctx, numericCommunityID, []communityusecase.MemberUpdate{{UserID: numericUserID, Action: communityusecase.MemberActionKick}}); err != nil {
		return false, err
	}
	return true, nil
}

// PromoteToCommunityOwner is the resolver for the promoteToCommunityOwner field.
func (r *mutationResolver) PromoteToCommunityOwner(ctx context.Context, communityID string, userID string) (bool, error) {
	if _, err := requireAuth(ctx); err != nil {
		return false, err
	}
	numericCommunityID, err := decodeGraphID(ctx, "community", communityID)
	if err != nil {
		return false, fmt.Errorf("invalid community id")
	}
	numericUserID, err := decodeGraphID(ctx, "user", userID)
	if err != nil {
		return false, fmt.Errorf("invalid user id")
	}
	if err := r.updateCommunityMembers(ctx, numericCommunityID, []communityusecase.MemberUpdate{{UserID: numericUserID, Action: communityusecase.MemberActionPromote}}); err != nil {
		return false, err
	}
	return true, nil
}

// DemoteFromCommunityOwner is the resolver for the demoteFromCommunityOwner field.
func (r *mutationResolver) DemoteFromCommunityOwner(ctx context.Context, communityID string, userID string) (bool, error) {
	if _, err := requireAuth(ctx); err != nil {
		return false, err
	}
	numericCommunityID, err := decodeGraphID(ctx, "community", communityID)
	if err != nil {
		return false, fmt.Errorf("invalid community id")
	}
	numericUserID, err := decodeGraphID(ctx, "user", userID)
	if err != nil {
		return false, fmt.Errorf("invalid user id")
	}
	if err := r.updateCommunityMembers(ctx, numericCommunityID, []communityusecase.MemberUpdate{{UserID: numericUserID, Action: communityusecase.MemberActionDemote}}); err != nil {
		return false, err
	}
	return true, nil
}

// UpdateCommunityMembers is the resolver for the updateCommunityMembers field.
func (r *mutationResolver) UpdateCommunityMembers(ctx context.Context, communityID string, updates []*gqlmodel.CommunityMemberUpdateInput) (bool, error) {
	if _, err := requireAuth(ctx); err != nil {
		return false, err
	}

	numericCommunityID, err := decodeGraphID(ctx, "community", communityID)
	if err != nil {
		return false, fmt.Errorf("invalid community id")
	}

	params := make([]communityusecase.MemberUpdate, 0, len(updates))
	for _, u := range updates {
		numericUserID, err := decodeGraphID(ctx, "user", u.UserID)
		if err != nil {
			return false, fmt.Errorf("invalid user id: %s", u.UserID)
		}
		var action communityusecase.MemberAction
		switch u.Action {
		case gqlmodel.CommunityMemberActionPromote:
			action = communityusecase.MemberActionPromote
		case gqlmodel.CommunityMemberActionDemote:
			action = communityusecase.MemberActionDemote
		case gqlmodel.CommunityMemberActionKick:
			action = communityusecase.MemberActionKick
		default:
			return false, fmt.Errorf("unknown action: %s", u.Action)
		}
		params = append(params, communityusecase.MemberUpdate{UserID: numericUserID, Action: action})
	}

	if err := r.updateCommunityMembers(ctx, numericCommunityID, params); err != nil {
		return false, err
	}
	return true, nil
}

// MyCommunities is the resolver for the myCommunities field.
func (r *queryResolver) MyCommunities(ctx context.Context, limit *int32, offset *int32) (*gqlmodel.CommunityPage, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	communities, total, err := r.ListMyCommunitiesUseCase.Execute(ctx, resolvePageQuery(ctx, limit, offset, defaultPageSize))
	if err != nil {
		return nil, err
	}
	roomIDs := make([]int64, 0, len(communities))
	for _, c := range communities {
		roomIDs = append(roomIDs, c.RoomID)
	}

	// DM 一覧と同じ流儀。未読もプレビューも取れなくても一覧は返し、失敗はログに残す。
	// コミュニティなので partnerLastReadAt は返らない（RoomReadStatus のコメント参照）。
	// Community が持つ既読まわりは unreadCount だけなので、判定もそれ1つ。
	readStatusMap := map[int64]*roomusecase.RoomReadStatus{}
	if fieldRequested(ctx, "items", "unreadCount") {
		readStatusMap, err = r.GetRoomReadStatusBatchUseCase.Execute(ctx, roomIDs, claims.ID, model.RoomTypeCommunity)
		if err != nil {
			logChatLookup(err, chatLookupReadStatusBatch).
				Int64("user_id", claims.ID).
				Int("rooms", len(roomIDs)).
				Msg("failed to load read statuses; returning the communities without unread counts")
		}
	}
	lastMessageMap := map[int64]*model.Message{}
	if fieldRequested(ctx, "items", "lastMessage") {
		lastMessageMap, err = r.GetLastMessagesByRoomIDsUseCase.Execute(ctx, roomIDs)
		if err != nil {
			logChatLookup(err, chatLookupLastMessages).
				Int64("user_id", claims.ID).
				Int("rooms", len(roomIDs)).
				Msg("failed to load last messages; returning the communities without previews")
		}
	}

	membership, err := r.loadCommunityMembership(ctx, roomIDs, &claims.ID,
		fieldRequested(ctx, "items", "memberCount"), fieldRequested(ctx, "items", "isMember"))
	if err != nil {
		return nil, err
	}

	items := make([]*gqlmodel.Community, 0, len(communities))
	for _, c := range communities {
		gqlC := r.toGraphCommunityWith(c, membership)
		if readStatus := readStatusMap[c.RoomID]; readStatus != nil {
			gqlC.UnreadCount = int32(readStatus.UnreadCount)
		}
		if lastMsg := lastMessageMap[c.RoomID]; lastMsg != nil {
			gqlC.LastMessage = &lastMsg.Content
		}
		items = append(items, gqlC)
	}
	return &gqlmodel.CommunityPage{Items: items, Total: int32(total)}, nil
}

// SearchCommunities is the resolver for the searchCommunities field.
func (r *queryResolver) SearchCommunities(ctx context.Context, name string, limit *int32, offset *int32) (*gqlmodel.CommunityPage, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	communities, total, err := r.SearchCommunityUseCase.Execute(ctx, name, resolvePageQuery(ctx, limit, offset, defaultPageSize))
	if err != nil {
		return nil, err
	}
	membership, err := r.loadCommunityMembership(ctx, communityRoomIDs(communities), &claims.ID,
		fieldRequested(ctx, "items", "memberCount"), fieldRequested(ctx, "items", "isMember"))
	if err != nil {
		return nil, err
	}
	items := make([]*gqlmodel.Community, 0, len(communities))
	for _, c := range communities {
		items = append(items, r.toGraphCommunityWith(c, membership))
	}
	return &gqlmodel.CommunityPage{Items: items, Total: int32(total)}, nil
}

// Communities is the resolver for the communities field.
func (r *queryResolver) Communities(ctx context.Context, limit *int32, offset *int32) (*gqlmodel.CommunityPage, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}
	communities, total, err := r.ListAllCommunitiesUseCase.Execute(ctx, resolvePageQuery(ctx, limit, offset, defaultPageSize))
	if err != nil {
		return nil, err
	}
	// 管理者の全件一覧は viewer を渡さない（誰の所属かが決まらないので isMember は
	// 以前から false 固定）。人数だけ、選ばれていれば1クエリで数える。
	membership, err := r.loadCommunityMembership(ctx, communityRoomIDs(communities), nil,
		fieldRequested(ctx, "items", "memberCount"), false)
	if err != nil {
		return nil, err
	}
	items := make([]*gqlmodel.Community, 0, len(communities))
	for _, c := range communities {
		items = append(items, r.toGraphCommunityWith(c, membership))
	}
	return &gqlmodel.CommunityPage{Items: items, Total: int32(total)}, nil
}

// RandomCommunities is the resolver for the randomCommunities field.
func (r *queryResolver) RandomCommunities(ctx context.Context, limit int32) ([]*gqlmodel.Community, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	communities, err := r.GetRandomCommunitiesUseCase.Execute(ctx, claims.ID, resolveLimit(&limit, defaultPageSize, maxPageSize))
	if err != nil {
		return nil, err
	}

	// randomCommunities は Community のリストを直接返す（ページ型でない）ので、
	// 選択パスは items を挟まない。
	membership, err := r.loadCommunityMembership(ctx, communityRoomIDs(communities), &claims.ID,
		fieldRequested(ctx, "memberCount"), fieldRequested(ctx, "isMember"))
	if err != nil {
		return nil, err
	}
	result := make([]*gqlmodel.Community, 0, len(communities))
	for _, c := range communities {
		result = append(result, r.toGraphCommunityWith(c, membership))
	}
	return result, nil
}

// GetMyRoleInCommunity is the resolver for the getMyRoleInCommunity field.
func (r *queryResolver) GetMyRoleInCommunity(ctx context.Context, communityID string) (string, error) {
	_, err := requireAuth(ctx)
	if err != nil {
		return "", err
	}

	numericCommunityID, err := decodeGraphID(ctx, "community", communityID)
	if err != nil {
		return "", fmt.Errorf("invalid community id")
	}

	c, err := r.GetCommunityUseCase.Execute(ctx, numericCommunityID)
	if err != nil {
		return "", err
	}
	if c == nil {
		return "", fmt.Errorf("community not found")
	}

	role, err := r.GetRoomUserRoleUseCase.Execute(ctx, c.RoomID)
	if err != nil {
		return "", err
	}
	return role, nil
}

// CommunityMembers is the resolver for the communityMembers field.
func (r *queryResolver) CommunityMembers(ctx context.Context, communityID string, limit *int32, offset *int32) (*gqlmodel.CommunityMemberPage, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}

	numericCommunityID, err := decodeGraphID(ctx, "community", communityID)
	if err != nil {
		return nil, fmt.Errorf("invalid community id")
	}
	c, err := r.GetCommunityUseCase.Execute(ctx, numericCommunityID)
	if err != nil {
		return nil, err
	}
	if c == nil {
		return nil, fmt.Errorf("community not found")
	}

	l, o := resolvePagination(limit, offset, 50)
	q := repository.PageQuery{Limit: l, Offset: o, WithTotal: fieldRequested(ctx, "total")}
	members, total, err := r.ListRoomMembersWithRolesPageUseCase.Execute(ctx, c.RoomID, q)
	if err != nil {
		return nil, err
	}
	items := make([]*gqlmodel.CommunityMember, 0, len(members))
	for _, member := range members {
		items = append(items, &gqlmodel.CommunityMember{User: toGraphUser(member.User), Role: member.Role})
	}
	return &gqlmodel.CommunityMemberPage{Items: items, Total: int32(total)}, nil
}
