package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	gqlmodel "github.com/Cityboypenguin/SPACE-server/graph/model"
)

// RegisterTimetableEntry is the resolver for the registerTimetableEntry field.
func (r *mutationResolver) RegisterTimetableEntry(ctx context.Context, courseID string) (*gqlmodel.TimetableEntry, error) {
	cID, err := decodeGraphID(ctx, "course", courseID)
	if err != nil {
		return nil, err
	}

	t, err := r.RegisterTimetableUseCase.Execute(ctx, cID)
	if err != nil {
		return nil, err
	}

	c, err := r.GetCourseByIDUseCase.Execute(ctx, t.CourseID)
	if err != nil {
		return nil, err
	}

	return toGraphTimetableEntry(t, c), nil
}

// RemoveTimetableEntry is the resolver for the removeTimetableEntry field.
func (r *mutationResolver) RemoveTimetableEntry(ctx context.Context, id string) (bool, error) {
	tID, err := decodeGraphID(ctx, "timetable", id)
	if err != nil {
		return false, err
	}
	return r.RemoveTimetableUseCase.Execute(ctx, tID)
}

// SetTimetableEntryColor is the resolver for the setTimetableEntryColor field.
func (r *mutationResolver) SetTimetableEntryColor(ctx context.Context, id string, color gqlmodel.TimetableEntryColor) (*gqlmodel.TimetableEntry, error) {
	tID, err := decodeGraphID(ctx, "timetable", id)
	if err != nil {
		return nil, err
	}

	t, err := r.SetTimetableEntryColorUseCase.Execute(ctx, tID, string(color))
	if err != nil {
		return nil, err
	}

	c, err := r.GetCourseByIDUseCase.Execute(ctx, t.CourseID)
	if err != nil {
		return nil, err
	}

	return toGraphTimetableEntry(t, c), nil
}

// SetMyTimetable is the resolver for the setMyTimetable field.
func (r *mutationResolver) SetMyTimetable(ctx context.Context, year int32, semester string, baselineEntryIDs []string, courseIDs []string) ([]*gqlmodel.TimetableEntry, error) {
	baselineIDs := make([]int64, 0, len(baselineEntryIDs))
	for _, id := range baselineEntryIDs {
		numericID, err := decodeGraphID(ctx, "timetable", id)
		if err != nil {
			return nil, err
		}
		baselineIDs = append(baselineIDs, numericID)
	}

	cIDs := make([]int64, 0, len(courseIDs))
	for _, id := range courseIDs {
		numericID, err := decodeGraphID(ctx, "course", id)
		if err != nil {
			return nil, err
		}
		cIDs = append(cIDs, numericID)
	}

	entries, err := r.ReplaceTimetableUseCase.Execute(ctx, int(year), semester, baselineIDs, cIDs)
	if err != nil {
		return nil, err
	}

	result := make([]*gqlmodel.TimetableEntry, 0, len(entries))
	for _, e := range entries {
		result = append(result, toGraphTimetableEntry(e.Timetable, e.Course))
	}
	return result, nil
}

// UpdateCurrentSemester is the resolver for the updateCurrentSemester field.
func (r *mutationResolver) UpdateCurrentSemester(ctx context.Context, year int32, semester string) (*gqlmodel.CurrentSemester, error) {
	if err := r.UpdateCurrentSemesterUseCase.Execute(ctx, int(year), semester); err != nil {
		return nil, err
	}
	return &gqlmodel.CurrentSemester{Year: year, Semester: semester}, nil
}

// SearchCourses is the resolver for the searchCourses field.
func (r *queryResolver) SearchCourses(ctx context.Context, dayOfWeek string, period int32, keyword *string, limit *int32, offset *int32) (*gqlmodel.CoursePage, error) {
	kw := ""
	if keyword != nil {
		kw = *keyword
	}

	items, total, err := r.SearchCoursesUseCase.Execute(ctx, dayOfWeek, int(period), kw, resolvePageQuery(ctx, limit, offset, defaultPageSize))
	if err != nil {
		return nil, err
	}

	gqlItems := make([]*gqlmodel.Course, 0, len(items))
	for _, c := range items {
		gqlItems = append(gqlItems, toGraphCourse(c))
	}

	return &gqlmodel.CoursePage{Items: gqlItems, Total: int32(total)}, nil
}

// MyTimetable is the resolver for the myTimetable field.
func (r *queryResolver) MyTimetable(ctx context.Context, year *int32, semester *string) ([]*gqlmodel.TimetableEntry, error) {
	var y *int
	if year != nil {
		v := int(*year)
		y = &v
	}

	entries, err := r.ListTimetableUseCase.Execute(ctx, y, semester)
	if err != nil {
		return nil, err
	}

	result := make([]*gqlmodel.TimetableEntry, 0, len(entries))
	for _, e := range entries {
		result = append(result, toGraphTimetableEntry(e.Timetable, e.Course))
	}
	return result, nil
}

// UserTimetable is the resolver for the userTimetable field.
func (r *queryResolver) UserTimetable(ctx context.Context, userID string, year *int32, semester *string) ([]*gqlmodel.TimetableEntry, error) {
	uID, err := decodeGraphID(ctx, "user", userID)
	if err != nil {
		return nil, err
	}

	var y *int
	if year != nil {
		v := int(*year)
		y = &v
	}

	// 閲覧可否はユースケース側で判定済み（見えないときは entries が空）。
	// このフィールドは可否をレスポンスに載せないので visible は捨てる。
	entries, _, err := r.GetUserTimetableUseCase.Execute(ctx, uID, y, semester)
	if err != nil {
		return nil, err
	}

	result := make([]*gqlmodel.TimetableEntry, 0, len(entries))
	for _, e := range entries {
		result = append(result, toGraphTimetableEntry(e.Timetable, e.Course))
	}
	return result, nil
}

// UserTimetableProfile is the resolver for the userTimetableProfile field.
func (r *queryResolver) UserTimetableProfile(ctx context.Context, userID string, year *int32, semester *string) (*gqlmodel.UserTimetableProfile, error) {
	uID, err := decodeGraphID(ctx, "user", userID)
	if err != nil {
		return nil, err
	}

	var y *int
	if year != nil {
		v := int(*year)
		y = &v
	}

	// 認証と閲覧可否（公開設定・ブロック関係）の判定はユースケースに集約してある。
	// ここで再判定すると同じルールが2箇所に散るので、結果をそのまま返すだけにする。
	entries, visible, err := r.GetUserTimetableUseCase.Execute(ctx, uID, y, semester)
	if err != nil {
		return nil, err
	}

	result := make([]*gqlmodel.TimetableEntry, 0, len(entries))
	for _, e := range entries {
		result = append(result, toGraphTimetableEntry(e.Timetable, e.Course))
	}

	return &gqlmodel.UserTimetableProfile{Visible: visible, Entries: result}, nil
}

// CurrentSemester is the resolver for the currentSemester field.
func (r *queryResolver) CurrentSemester(ctx context.Context) (*gqlmodel.CurrentSemester, error) {
	year, semesterName, err := r.GetCurrentSemesterUseCase.Execute(ctx)
	if err != nil {
		return nil, err
	}
	return &gqlmodel.CurrentSemester{Year: int32(year), Semester: semesterName}, nil
}

// CourseYears is the resolver for the courseYears field.
func (r *queryResolver) CourseYears(ctx context.Context) ([]int32, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}

	years, err := r.ListCourseYearsUseCase.Execute(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]int32, 0, len(years))
	for _, y := range years {
		result = append(result, int32(y))
	}
	return result, nil
}

// MyCourseRoomUnreadCounts is the resolver for the myCourseRoomUnreadCounts field.
func (r *queryResolver) MyCourseRoomUnreadCounts(ctx context.Context) ([]*gqlmodel.CourseRoomUnread, error) {
	counts, err := r.ListCourseRoomUnreadCountsUseCase.Execute(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*gqlmodel.CourseRoomUnread, 0, len(counts))
	for _, c := range counts {
		result = append(result, &gqlmodel.CourseRoomUnread{
			RoomID:      encodeGraphID("room", c.RoomID),
			UnreadCount: int32(c.UnreadCount),
		})
	}
	return result, nil
}
