package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"strconv"

	gqlmodel "github.com/Cityboypenguin/SPACE-server/graph/model"
	"github.com/Cityboypenguin/SPACE-server/internal/upload"
)

// ReportMediaDimensions is the resolver for the reportMediaDimensions field.
func (r *mutationResolver) ReportMediaDimensions(ctx context.Context, mediaID string, width int32, height int32) (bool, error) {
	if _, err := requireAuth(ctx); err != nil {
		return false, err
	}
	// メディア ID は署名付きの不透明値なので、クエリで受け取った＝閲覧できたメディア
	// しか指定できない。加えて未設定のときしか書き込まないため、
	// 誤った観測が入っても影響は 1 枚の表示比率にとどまる。
	numericID, err := decodeGraphID(ctx, "media", mediaID)
	if err != nil {
		return false, err
	}

	if err := r.ReportMediaDimensionsUseCase.Execute(ctx, numericID, int(width), int(height)); err != nil {
		return false, err
	}
	return true, nil
}

// PresignedAvatarUploadURL is the resolver for the presignedAvatarUploadUrl field.
func (r *queryResolver) PresignedAvatarUploadURL(ctx context.Context, contentType string) (*gqlmodel.PresignedUploadURL, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	return r.presignedUploadURL(ctx, upload.Avatar, strconv.FormatInt(claims.ID, 10), contentType)
}

// PresignedMediaUploadURL is the resolver for the presignedMediaUploadUrl field.
func (r *queryResolver) PresignedMediaUploadURL(ctx context.Context, contentType string) (*gqlmodel.PresignedUploadURL, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	return r.presignedUploadURL(ctx, upload.Media, strconv.FormatInt(claims.ID, 10), contentType)
}

// PresignedCommunityIconUploadURL is the resolver for the presignedCommunityIconUploadUrl field.
func (r *queryResolver) PresignedCommunityIconUploadURL(ctx context.Context, contentType string) (*gqlmodel.PresignedUploadURL, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	return r.presignedUploadURL(ctx, upload.CommunityIcon, strconv.FormatInt(claims.ID, 10), contentType)
}

// PresignedTermsDocumentUploadURL is the resolver for the presignedTermsDocumentUploadUrl field.
func (r *queryResolver) PresignedTermsDocumentUploadURL(ctx context.Context) (*gqlmodel.PresignedUploadURL, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}

	// 規約は利用者ごとに分けない（管理者しか置けず、版で一意なので）。
	return r.presignedUploadURL(ctx, upload.TermsDocument, "", "text/markdown")
}

// AdminListMediaMissingDimensions is the resolver for the adminListMediaMissingDimensions field.
func (r *queryResolver) AdminListMediaMissingDimensions(ctx context.Context, limit *int32, offset *int32) ([]*gqlmodel.Media, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}

	lim, off := resolvePagination(limit, offset, defaultPageSize)
	items, err := r.ListImagesMissingDimensionsUseCase.Execute(ctx, lim, off)
	if err != nil {
		return nil, err
	}

	result := make([]*gqlmodel.Media, 0, len(items))
	for _, m := range items {
		result = append(result, toGraphMedia(m, r.StorageRepository.PublicURL(m.StorageKey)))
	}
	return result, nil
}
