package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"
	"strconv"
	"time"

	gqlmodel "github.com/Cityboypenguin/SPACE-server/graph/model"
	"github.com/Cityboypenguin/SPACE-server/model"
	inquiryusecase "github.com/Cityboypenguin/SPACE-server/usecase/inquiry"
	"github.com/Cityboypenguin/SPACE-server/usecase/report"
	"log"
	"strings"
)

// FreezeUser is the resolver for the freezeUser field.
func (r *mutationResolver) FreezeUser(ctx context.Context, id string) (bool, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return false, err
	}

	numericID, err := decodeGraphID(ctx, "user", id)
	if err != nil {
		return false, fmt.Errorf("invalid user id")
	}

	return r.FreezeUserUseCase.Execute(ctx, numericID)
}

// UnfreezeUser is the resolver for the unfreezeUser field.
func (r *mutationResolver) UnfreezeUser(ctx context.Context, id string) (bool, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return false, err
	}

	numericID, err := decodeGraphID(ctx, "user", id)
	if err != nil {
		return false, fmt.Errorf("invalid user id")
	}

	return r.UnfreezeUserUseCase.Execute(ctx, numericID)
}

// CreateReport is the resolver for the createReport field.
func (r *mutationResolver) CreateReport(ctx context.Context, input gqlmodel.CreateReportInput) (*gqlmodel.UserReport, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	kind := reportTargetKind(input.TargetType)
	if kind == "" {
		return nil, fmt.Errorf("unsupported target type: %s", input.TargetType)
	}
	numericTargetID, err := decodeGraphID(ctx, kind, input.TargetID)
	if err != nil {
		return nil, fmt.Errorf("invalid target id")
	}

	var snapshotContent *string

	if strings.ToUpper(string(input.TargetType)) == "POST" || input.TargetType == "post" {
		post, err := r.GetPostByIDUseCase.Execute(ctx, numericTargetID)
		if err == nil && post != nil {
			snapshotContent = &post.Content
		} else if err != nil {
			log.Printf("Failed to fetch post for report: %v", err)
		}
	}

	res, err := r.CreateReportUsecase.Execute(ctx, report.CreateReportInput{
		ReporterID:   claims.ID,
		TargetType:   model.ReportTargetType(input.TargetType),
		TargetID:     fmt.Sprintf("%d", numericTargetID),
		Reason:       input.Reason,
		CustomReason: input.CustomReason,
		Content:      snapshotContent,
	})
	if err != nil {
		return nil, err
	}

	reporter, err := r.GetUserByIDUseCase.Execute(ctx, claims.ID)
	if err != nil || reporter == nil {
		return nil, fmt.Errorf("failed to fetch reporter")
	}

	return &gqlmodel.UserReport{
		ID:           res.ID,
		TargetType:   input.TargetType,
		TargetID:     encodeGraphID(kind, numericTargetID),
		Reason:       res.Reason,
		CustomReason: res.CustomReason,
		Status:       gqlmodel.ReportStatusPending,
		Reporter:     toGraphUser(reporter),
		Content:      res.PostContent,
		CreatedAt:    res.CreatedAt.Format(time.RFC3339),
		UpdatedAt:    res.UpdatedAt.Format(time.RFC3339),
	}, nil
}

// UpdateReportStatus is the resolver for the updateReportStatus field.
func (r *mutationResolver) UpdateReportStatus(ctx context.Context, id string, status gqlmodel.ReportStatus) (*gqlmodel.UserReport, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}
	res, err := r.ManageReportUsecase.UpdateStatus(ctx, id, model.ReportStatus(status))
	if err != nil {
		return nil, err
	}
	if r.InvalidateAnalyticsSummary != nil {
		r.InvalidateAnalyticsSummary()
	}

	reporter, err := r.GetUserByIDUseCase.Execute(ctx, res.ReporterID)
	if err != nil || reporter == nil {
		return nil, fmt.Errorf("failed to fetch reporter")
	}

	targetType := gqlmodel.ReportTargetType(res.TargetType)
	targetID := res.TargetID
	if kind := reportTargetKind(targetType); kind != "" {
		if numericID, err := strconv.ParseInt(res.TargetID, 10, 64); err == nil {
			targetID = encodeGraphID(kind, numericID)
		}
	}

	return &gqlmodel.UserReport{
		ID:           res.ID,
		TargetType:   targetType,
		TargetID:     targetID,
		Reason:       res.Reason,
		CustomReason: res.CustomReason,
		Status:       status,
		Reporter:     toGraphUser(reporter),
		Content:      res.PostContent,
		CreatedAt:    res.CreatedAt.Format(time.RFC3339),
		UpdatedAt:    res.UpdatedAt.Format(time.RFC3339),
	}, nil
}

// CreateInquiry is the resolver for the createInquiry field.
func (r *mutationResolver) CreateInquiry(ctx context.Context, input gqlmodel.CreateInquiryInput) (*gqlmodel.Inquiry, error) {
	inquiry, err := r.CreateInquiryUsecase.Execute(ctx, inquiryusecase.CreateInquiryInput{
		Name:     input.Name,
		Email:    input.Email,
		Category: model.InquiryCategory(input.Category),
		Subject:  input.Subject,
		Content:  input.Content,
	})
	if err != nil {
		return nil, err
	}
	return toGraphInquiry(inquiry), nil
}

// UpdateInquiryStatus is the resolver for the updateInquiryStatus field.
func (r *mutationResolver) UpdateInquiryStatus(ctx context.Context, id string, status gqlmodel.InquiryStatus) (*gqlmodel.Inquiry, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}

	inquiry, err := r.ManageInquiryUsecase.UpdateStatus(ctx, id, model.InquiryStatus(status))
	if err != nil {
		return nil, err
	}
	return toGraphInquiry(inquiry), nil
}

// SetReportServiceStatus is the resolver for the setReportServiceStatus field.
func (r *mutationResolver) SetReportServiceStatus(ctx context.Context, enabled bool) (bool, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return false, err
	}
	if err := r.ManageSystemSettingUsecase.Execute(ctx, enabled); err != nil {
		return false, err
	}

	return enabled, nil
}

// SearchReports is the resolver for the searchReports field.
func (r *queryResolver) SearchReports(ctx context.Context, filter *gqlmodel.ReportSearchFilter, limit *int32, offset *int32) (*gqlmodel.ReportPage, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}

	var domainFilter *model.ReportSearchFilter
	if filter != nil {
		domainFilter = &model.ReportSearchFilter{}
		if filter.Status != nil {
			s := model.ReportStatus(*filter.Status)
			domainFilter.Status = &s
		}
		if filter.TargetType != nil {
			t := model.ReportTargetType(*filter.TargetType)
			domainFilter.TargetType = &t
		}
		if filter.ReporterID != nil {
			numericID, err := decodeGraphID(ctx, "user", *filter.ReporterID)
			if err != nil {
				return nil, fmt.Errorf("invalid reporter id")
			}
			domainFilter.ReporterID = &numericID
		}
	}

	reports, total, err := r.ManageReportUsecase.Search(ctx, domainFilter, resolvePageQuery(ctx, limit, offset, defaultPageSize))
	if err != nil {
		return nil, err
	}

	// 通報者をバッチフェッチ (N+1 防止)
	seen := map[int64]struct{}{}
	var reporterIDs []int64
	for _, res := range reports {
		if _, ok := seen[res.ReporterID]; !ok {
			seen[res.ReporterID] = struct{}{}
			reporterIDs = append(reporterIDs, res.ReporterID)
		}
	}
	reporterMap := map[int64]*model.User{}
	if len(reporterIDs) > 0 {
		reporters, aerr := r.GetUsersByIDsUseCase.Execute(ctx, reporterIDs)
		if aerr == nil {
			for _, u := range reporters {
				reporterMap[u.ID] = u
			}
		}
	}

	gqlReports := make([]*gqlmodel.UserReport, 0, len(reports))
	for _, res := range reports {
		targetType := gqlmodel.ReportTargetType(res.TargetType)
		targetID := res.TargetID
		if kind := reportTargetKind(targetType); kind != "" {
			if numericID, err := strconv.ParseInt(res.TargetID, 10, 64); err == nil {
				targetID = encodeGraphID(kind, numericID)
			}
		}

		var reporterUser *gqlmodel.User
		if u, ok := reporterMap[res.ReporterID]; ok {
			reporterUser = toGraphUser(u)
		} else {
			reporterUser = &gqlmodel.User{ID: encodeGraphID("user", res.ReporterID)}
		}

		var reportContent *string
		if res.TargetType == model.TargetPost && res.PostContent != nil {
			reportContent = res.PostContent
		}

		gqlReports = append(gqlReports, &gqlmodel.UserReport{
			ID:           res.ID,
			TargetType:   targetType,
			TargetID:     targetID,
			Reason:       res.Reason,
			CustomReason: res.CustomReason,
			Status:       gqlmodel.ReportStatus(res.Status),
			Reporter:     reporterUser,
			Content:      reportContent,
			CreatedAt:    res.CreatedAt.Format(time.RFC3339),
			UpdatedAt:    res.UpdatedAt.Format(time.RFC3339),
		})
	}
	return &gqlmodel.ReportPage{Items: gqlReports, Total: int32(total)}, nil
}

// SearchInquiries is the resolver for the searchInquiries field.
func (r *queryResolver) SearchInquiries(ctx context.Context, status *gqlmodel.InquiryStatus, limit *int32, offset *int32) (*gqlmodel.InquiryPage, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}

	var domainStatus *model.InquiryStatus
	if status != nil {
		s := model.InquiryStatus(*status)
		domainStatus = &s
	}

	inquiries, total, err := r.ManageInquiryUsecase.Search(ctx, domainStatus, resolvePageQuery(ctx, limit, offset, defaultPageSize))
	if err != nil {
		return nil, err
	}
	items := make([]*gqlmodel.Inquiry, 0, len(inquiries))
	for _, inq := range inquiries {
		items = append(items, toGraphInquiry(inq))
	}
	return &gqlmodel.InquiryPage{Items: items, Total: int32(total)}, nil
}

// GetInquiry is the resolver for the getInquiry field.
func (r *queryResolver) GetInquiry(ctx context.Context, id string) (*gqlmodel.Inquiry, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}

	inquiry, err := r.ManageInquiryUsecase.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	if inquiry == nil {
		return nil, nil
	}
	return toGraphInquiry(inquiry), nil
}

// IsReportServiceEnabled is the resolver for the isReportServiceEnabled field.
func (r *queryResolver) IsReportServiceEnabled(ctx context.Context) (bool, error) {
	return r.ManageSystemSettingUsecase.IsReportEnabled(ctx)
}
