package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"
	"fmt"

	gqlmodel "github.com/Cityboypenguin/SPACE-server/graph/model"
	"github.com/Cityboypenguin/SPACE-server/internal/auth"
	"github.com/Cityboypenguin/SPACE-server/model"
)

// MarkNotificationAsRead is the resolver for the markNotificationAsRead field.
func (r *mutationResolver) MarkNotificationAsRead(ctx context.Context, id string) (bool, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	numericID, err := decodeGraphID(ctx, "notification", id)
	if err != nil {
		return false, fmt.Errorf("invalid notification id")
	}
	if err := r.MarkAsReadUseCase.Execute(ctx, numericID); err != nil {
		return false, err
	}
	// 数は配らず「変わった」ことだけを知らせる。受け取った他のタブ・他の端末が
	// 自分で未読数を取り直す（sse.EventNotificationsChanged のコメント参照）。
	r.SSEBroker.PublishNotificationsChangedToUser(claims.ID)
	return true, nil
}

// MarkAllNotificationsAsRead is the resolver for the markAllNotificationsAsRead field.
func (r *mutationResolver) MarkAllNotificationsAsRead(ctx context.Context) (bool, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	if err := r.MarkAllAsReadUseCase.Execute(ctx); err != nil {
		return false, err
	}
	r.SSEBroker.PublishNotificationsChangedToUser(claims.ID)
	return true, nil
}

// MarkAllNotificationsAsReadByActor is the resolver for the markAllNotificationsAsReadByActor field.
func (r *mutationResolver) MarkAllNotificationsAsReadByActor(ctx context.Context, typeArg string, actorID string) (bool, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	numericActorID, err := decodeGraphID(ctx, "user", actorID)
	if err != nil {
		return false, fmt.Errorf("invalid actor id")
	}
	if err := r.MarkAllAsReadByActorUseCase.Execute(ctx, typeArg, numericActorID); err != nil {
		return false, err
	}
	r.SSEBroker.PublishNotificationsChangedToUser(claims.ID)
	return true, nil
}

// DeleteNotifications is the resolver for the deleteNotifications field.
func (r *mutationResolver) DeleteNotifications(ctx context.Context, ids []string) (bool, error) {
	_, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	numericIDs := make([]int64, 0, len(ids))
	for _, id := range ids {
		numericID, err := decodeGraphID(ctx, "notification", id)
		if err != nil {
			return false, fmt.Errorf("invalid notification id: %s", id)
		}
		numericIDs = append(numericIDs, numericID)
	}
	if err := r.DeleteNotificationsUseCase.Execute(ctx, numericIDs); err != nil {
		return false, err
	}
	return true, nil
}

// DeleteReadNotifications is the resolver for the deleteReadNotifications field.
func (r *mutationResolver) DeleteReadNotifications(ctx context.Context) (bool, error) {
	_, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	if err := r.DeleteReadNotificationsUseCase.Execute(ctx); err != nil {
		return false, err
	}
	return true, nil
}

// DeleteReadNotificationsByActor is the resolver for the deleteReadNotificationsByActor field.
func (r *mutationResolver) DeleteReadNotificationsByActor(ctx context.Context, typeArg string, actorID string) (bool, error) {
	_, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	numericActorID, err := decodeGraphID(ctx, "user", actorID)
	if err != nil {
		return false, fmt.Errorf("invalid actor id")
	}
	if err := r.DeleteReadNotificationsByActorUseCase.Execute(ctx, typeArg, numericActorID); err != nil {
		return false, err
	}
	return true, nil
}

// IssueNotificationStreamTicket is the resolver for the issueNotificationStreamTicket field.
func (r *mutationResolver) IssueNotificationStreamTicket(ctx context.Context) (string, error) {
	// 認証は通常どおりヘッダーで行う（チケットは /events へ渡すためだけのもので、
	// これ自体を取る口は認証済みでないと叩けない）。発行するのは常に「自分ぶん」で、
	// 他人ぶんを発行させる引数は持たせない。
	_, err := requireAuth(ctx)
	if err != nil {
		return "", err
	}
	// チケットにはトークンそのものも預ける。/events は接続したあと何時間も
	// 生きるので、その間に失効・凍結・パスワード変更が起きたかを確かめ直す
	// 元手が要る（repository.StreamSession のコメント参照）。
	token, ok := auth.TokenFromContext(ctx)
	if !ok {
		return "", errors.New("unauthorized")
	}
	return r.IssueStreamTicketUseCase.Execute(ctx, token)
}

// Actor is the resolver for the actor field on Notification.
func (r *notificationResolver) Actor(ctx context.Context, obj *gqlmodel.Notification) (*gqlmodel.User, error) {
	if obj.Actor == nil {
		return nil, nil
	}
	// MyNotifications で事前ロード済みの場合はDBアクセス不要
	if obj.Actor.AccountID != "" {
		return obj.Actor, nil
	}
	numericID, err := decodeGraphID(ctx, "user", obj.Actor.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid actor id")
	}
	user, err := r.GetUserByIDUseCase.Execute(ctx, numericID)
	if err != nil {
		return nil, err
	}
	if user == nil {
		return toGraphDeletedUserWithID(numericID), nil
	}
	return toGraphUser(user), nil
}

// TargetMessage is the resolver for the targetMessage field.
func (r *notificationResolver) TargetMessage(ctx context.Context, obj *gqlmodel.Notification) (*gqlmodel.Message, error) {
	return r.notificationTargetMessage(ctx, obj.TargetType, obj.TargetID)
}

// TargetMessage is the resolver for the targetMessage field.
func (r *notificationGroupResolver) TargetMessage(ctx context.Context, obj *gqlmodel.NotificationGroup) (*gqlmodel.Message, error) {
	return r.notificationTargetMessage(ctx, obj.TargetType, obj.TargetID)
}

// MyNotifications is the resolver for the myNotifications field.
func (r *queryResolver) MyNotifications(ctx context.Context, limit *int32, offset *int32, typeArg *string, actorID *string) (*gqlmodel.NotificationPage, error) {
	_, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	pq := resolvePageQuery(ctx, limit, offset, defaultPageSize)

	var notifications []*model.Notification
	var total int
	if actorID != nil {
		numericActorID, decErr := decodeGraphID(ctx, "user", *actorID)
		if decErr != nil {
			return nil, fmt.Errorf("invalid actor id")
		}
		notifType := ""
		if typeArg != nil {
			notifType = *typeArg
		}
		notifications, total, err = r.ListNotificationsByActorUseCase.Execute(ctx, notifType, numericActorID, pq)
	} else {
		notifications, total, err = r.ListNotificationsUseCase.Execute(ctx, pq)
	}
	if err != nil {
		return nil, err
	}

	// actor と対象 Post は、選ばれたときだけまとめて引く（N+1 は避けたまま、
	// 要求されていない一括取得は撃たない）。判定は共通の fieldRequested。
	actorIDs := make([]*int64, 0, len(notifications))
	for _, n := range notifications {
		actorIDs = append(actorIDs, n.ActorID)
	}
	hydration, err := r.hydrateNotifications(ctx,
		uniqueInt64(actorIDs),
		postTargetIDs(notifications),
		fieldRequested(ctx, "items", "actor"),
		fieldRequested(ctx, "items", "targetPost"),
	)
	if err != nil {
		return nil, err
	}

	items := make([]*gqlmodel.Notification, 0, len(notifications))
	for _, n := range notifications {
		items = append(items, toGraphNotification(n, hydration))
	}
	return &gqlmodel.NotificationPage{Items: items, Total: int32(total)}, nil
}

// MyNotificationGroups is the resolver for the myNotificationGroups field.
func (r *queryResolver) MyNotificationGroups(ctx context.Context, limit *int32, offset *int32) (*gqlmodel.NotificationGroupPage, error) {
	_, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	groups, total, err := r.ListNotificationGroupsUseCase.Execute(ctx, resolvePageQuery(ctx, limit, offset, defaultPageSize))
	if err != nil {
		return nil, err
	}

	// 通知一覧（MyNotifications）と同じ扱い。
	actorIDs := make([]*int64, 0, len(groups))
	for _, g := range groups {
		actorIDs = append(actorIDs, g.ActorID)
	}
	hydration, err := r.hydrateNotifications(ctx,
		uniqueInt64(actorIDs),
		groupPostTargetIDs(groups),
		fieldRequested(ctx, "items", "actor"),
		fieldRequested(ctx, "items", "targetPost"),
	)
	if err != nil {
		return nil, err
	}

	items := make([]*gqlmodel.NotificationGroup, 0, len(groups))
	for _, g := range groups {
		items = append(items, toGraphNotificationGroup(g, hydration))
	}
	return &gqlmodel.NotificationGroupPage{Items: items, Total: int32(total)}, nil
}

// Notification is the resolver for the notification field.
func (r *queryResolver) Notification(ctx context.Context, id string) (*gqlmodel.Notification, error) {
	_, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	numericID, err := decodeGraphID(ctx, "notification", id)
	if err != nil {
		return nil, fmt.Errorf("invalid notification id")
	}
	n, err := r.GetNotificationUseCase.Execute(ctx, numericID)
	if err != nil {
		return nil, err
	}
	if n == nil {
		return nil, nil
	}
	// 一覧と同じく、actor と対象 Post は選ばれたときだけ引く。単体なので
	// GetUsersByIDs に1件渡す形になるが、判定と経路を一覧と揃えておくほうが
	// 「ここだけ常に引いている」という取りこぼしが起きにくい。
	notifications := []*model.Notification{n}
	hydration, err := r.hydrateNotifications(ctx,
		uniqueInt64([]*int64{n.ActorID}),
		postTargetIDs(notifications),
		fieldRequested(ctx, "actor"),
		fieldRequested(ctx, "targetPost"),
	)
	if err != nil {
		return nil, err
	}
	return toGraphNotification(n, hydration), nil
}

// MyUnreadNotificationCount is the resolver for the myUnreadNotificationCount field.
func (r *queryResolver) MyUnreadNotificationCount(ctx context.Context) (int32, error) {
	_, err := requireAuth(ctx)
	if err != nil {
		return 0, err
	}
	count, err := r.CountUnreadUseCase.Execute(ctx)
	if err != nil {
		return 0, err
	}
	return int32(count), nil
}

// MyUnreadDMCount is the resolver for the myUnreadDMCount field.
func (r *queryResolver) MyUnreadDMCount(ctx context.Context) (int32, error) {
	_, err := requireAuth(ctx)
	if err != nil {
		return 0, err
	}
	count, err := r.CountUnreadByRoomTypeUseCase.Execute(ctx, model.RoomTypeDM)
	if err != nil {
		return 0, err
	}
	return int32(count), nil
}

// MyUnreadCommunityCount is the resolver for the myUnreadCommunityCount field.
func (r *queryResolver) MyUnreadCommunityCount(ctx context.Context) (int32, error) {
	_, err := requireAuth(ctx)
	if err != nil {
		return 0, err
	}
	count, err := r.CountUnreadByRoomTypeUseCase.Execute(ctx, model.RoomTypeCommunity)
	if err != nil {
		return 0, err
	}
	return int32(count), nil
}

// Notification returns NotificationResolver implementation.
func (r *Resolver) Notification() NotificationResolver { return &notificationResolver{r} }

// NotificationGroup returns NotificationGroupResolver implementation.
func (r *Resolver) NotificationGroup() NotificationGroupResolver {
	return &notificationGroupResolver{r}
}

type (
	notificationResolver      struct{ *Resolver }
	notificationGroupResolver struct{ *Resolver }
)
