package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"
	"time"

	gqlmodel "github.com/Cityboypenguin/SPACE-server/graph/model"
	"github.com/Cityboypenguin/SPACE-server/internal/auth"
	"github.com/Cityboypenguin/SPACE-server/internal/dataloader"
	"github.com/Cityboypenguin/SPACE-server/model"
	"github.com/Cityboypenguin/SPACE-server/repository"
	"strings"
)

// User is the resolver for the user field on Favorite.
func (r *favoriteResolver) User(ctx context.Context, obj *gqlmodel.Favorite) (*gqlmodel.User, error) {
	numericUserID, err := decodeGraphID(ctx, "user", obj.User.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %s", obj.User.ID)
	}
	// いいね一覧は同じ投稿・同じ人が何度も並ぶので DataLoader 経由で引く
	//（いいね N 件で N クエリ → 1クエリ）。単体取得と同じく、居なければ nil。
	user, err := dataloader.For(ctx).UserLoader.Load(ctx, numericUserID)
	if err != nil {
		return nil, err
	}
	return toGraphUser(user), nil
}

// Post is the resolver for the post field on Favorite.
func (r *favoriteResolver) Post(ctx context.Context, obj *gqlmodel.Favorite) (*gqlmodel.Post, error) {
	numericPostID, err := decodeGraphID(ctx, "post", obj.Post.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid post id: %s", obj.Post.ID)
	}

	// user フィールドと同じ理由で DataLoader 経由（いいね N 件で N クエリ → 1クエリ）。
	// PostLoader の裏は GetPostsByIDs で、削除済み・ブロック相手の投稿が
	// 落ちるところまで単体の GetPostByID と同じ。
	post, err := dataloader.For(ctx).PostLoader.Load(ctx, numericPostID)
	if err != nil {
		return nil, err
	}
	if post == nil {
		// スキーマ上 Favorite.post は非null（post: Post!）。いいねが残ったまま
		// 投稿が消えた／ブロック相手になったときにここへ来る。
		//
		// ここで nil を返しても「投稿だけ欠けた Favorite」にはならない。gqlgen の
		// 非null用マーシャラが「the requested element is null which the schema
		// does not allow」を立て、親（Favorite、ひいてはそれを含む非nullリスト）
		// ごと落ちる。どうせ失敗するなら、理由の分かる形で返す。
		return nil, denyNotVisible(ctx, "read_favorite_post", "post", numericPostID)
	}

	return toGraphPost(post), nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input gqlmodel.CreatePostInput) (*gqlmodel.Post, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	trimmedContent := strings.TrimSpace(input.Content)

	var numericParentID *int64
	if input.ParentID != nil && *input.ParentID != "" {
		parentID, err := decodeGraphID(ctx, "post", *input.ParentID)
		if err != nil {
			return nil, fmt.Errorf("invalid parent post id")
		}
		numericParentID = &parentID
	}

	ucMediaInputs := r.toMediaInputs(input.MediaInputs)

	post, err := r.CreatePostUseCase.Execute(ctx, model.CreatePostParam{
		UserID:   claims.ID,
		Content:  trimmedContent,
		ParentID: numericParentID,
	}, ucMediaInputs)
	if err != nil {
		return nil, err
	}

	// 返信先投稿者への通知は CreatePostUseCase 内で発行される。

	return toGraphPost(post), nil
}

// DeletePost is the resolver for the deletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, id string) (bool, error) {
	_, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}

	numericID, err := decodeGraphID(ctx, "post", id)
	if err != nil {
		return false, fmt.Errorf("invalid post id")
	}

	return r.DeletePostUseCase.Execute(ctx, numericID, false)
}

// UpdatePost is the resolver for the updatePost field.
func (r *mutationResolver) UpdatePost(ctx context.Context, input gqlmodel.UpdatePostInput) (*gqlmodel.Post, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	trimmedContent := strings.TrimSpace(input.Content)

	numericID, err := decodeGraphID(ctx, "post", input.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid post id")
	}

	var deletedMediaIDs []int64
	for _, strID := range input.DeletedMediaIDs {
		numID, err := decodeGraphID(ctx, "media", strID)
		if err != nil {
			return nil, fmt.Errorf("invalid deleted media id format: %s", strID)
		}
		deletedMediaIDs = append(deletedMediaIDs, numID)
	}

	ucMediaInputs := r.toMediaInputs(input.NewMediaInputs)

	post, err := r.UpdatePostUseCase.Execute(ctx, model.UpdatePostParam{
		PostID:  numericID,
		UserID:  claims.ID,
		Content: &trimmedContent,
	}, ucMediaInputs, deletedMediaIDs)
	if err != nil {
		return nil, err
	}

	return toGraphPost(post), nil
}

// CreateFavorite is the resolver for the createFavorite field.
func (r *mutationResolver) CreateFavorite(ctx context.Context, input gqlmodel.CreateFavoriteInput) (*gqlmodel.Favorite, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	numericPostID, err := decodeGraphID(ctx, "post", input.PostID)
	if err != nil {
		return nil, fmt.Errorf("invalid post id")
	}

	favorite, err := r.CreateFavoriteUseCase.Execute(ctx, model.CreateFavoriteParam{
		UserID: claims.ID,
		PostID: numericPostID,
	})
	if err != nil {
		return nil, err
	}

	// 投稿者への「いいね」通知は CreateFavoriteUseCase 内で発行される。

	return toGraphFavorite(favorite), nil
}

// DeleteFavorite is the resolver for the deleteFavorite field.
func (r *mutationResolver) DeleteFavorite(ctx context.Context, input gqlmodel.DeleteFavoriteInput) (bool, error) {
	_, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}

	numericPostID, err := decodeGraphID(ctx, "post", input.PostID)
	if err != nil {
		return false, fmt.Errorf("invalid post id")
	}

	return r.DeleteFavoriteByUserIDAndPostIDUseCase.Execute(ctx, numericPostID)
}

// User is the resolver for the user field on Post.
func (r *postResolver) User(ctx context.Context, obj *gqlmodel.Post) (*gqlmodel.User, error) {
	numericUserID, err := decodeGraphID(ctx, "user", obj.User.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %s", obj.User.ID)
	}

	user, err := dataloader.For(ctx).UserLoader.Load(ctx, numericUserID)

	if err != nil {
		return nil, err
	}
	if user == nil {
		return toGraphDeletedUserWithID(numericUserID), nil
	}
	return toGraphUser(user), nil
}

// RootPost is the resolver for the rootPost field.
func (r *postResolver) RootPost(ctx context.Context, obj *gqlmodel.Post) (*gqlmodel.Post, error) {
	numericPostID, err := decodeGraphID(ctx, "post", obj.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid post id")
	}

	rootPost, err := r.GetRootPostUseCase.Execute(ctx, numericPostID)
	if err != nil {
		return nil, err
	}
	if rootPost == nil {
		return nil, nil
	}
	return toGraphPost(rootPost), nil
}

// Favorites is the resolver for the favorites field on Post.
func (r *postResolver) Favorites(ctx context.Context, obj *gqlmodel.Post, limit *int32, offset *int32) ([]*gqlmodel.Favorite, error) {
	numericPostID, err := decodeGraphID(ctx, "post", obj.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid post id")
	}

	// 「誰がいいねしたか」を見られるのは投稿した本人（と管理者）だけ。件数と自分の
	// 有無は favoriteCount / isFavoritedByMe が誰にでも返すが、名前の一覧は別扱いに
	// する。ここを開けたままにすると、投稿の ID さえ分かれば任意の投稿について
	// いいねした人を並べられてしまう。
	//
	// 一覧の途中でこれを選ぶと、自分以外の投稿のところで丸ごと失敗する。それで
	// よい。空で返すと「いいねが0件」と見分けが付かず、呼び出し側が気づけない。
	//
	// 投稿者は obj.User ではなく投稿の行そのものから決める。obj は呼び出し側が
	// 組み立てた値で、ID だけを詰めた見本もありうる（graph/presenter.go の親投稿）。
	// いまはどの経路も toGraphPost を通るので User は入っているが、そこに頼ると
	// 「入っていなければ nil 参照で落ちる」「実体と食い違えば誤った相手に許可が
	// 出る」の2つが、新しいフィールドを足した人には見えないまま残る。権限は
	// 運ばれてきた値ではなく元の行で決める。
	//
	// PostLoader はリクエスト内で使い回されるので、追加のクエリはほぼ出ない
	//（この口へ来る前に投稿を引いていれば、その結果がそのまま返る）。
	const action = "list_post_favorites"
	post, err := dataloader.For(ctx).PostLoader.Load(ctx, numericPostID)
	if err != nil {
		return nil, err
	}
	if post == nil {
		// 削除済み・ブロック相手で見えない投稿（PostLoader が nil を返す条件）。
		return nil, denyNotVisible(ctx, action, "post", numericPostID)
	}
	if _, err := requireSelfOrAdmin(ctx, post.UserID, action); err != nil {
		return nil, err
	}

	// limit を送らなくても unpagedCollectionCap で頭打ちになる。引数を後から
	// 足したフィールドなので、送っていないクライアントの見え方は変えない
	// （理由は graph/helpers.go の unpagedCollectionCap のコメント）。
	favorites, err := dataloader.For(ctx).FavoriteLoader.Load(ctx, dataloader.FavoritePageKey{
		PostID: numericPostID,
		Page:   resolveUnpagedWindow(limit, offset),
	})
	if err != nil {
		return nil, err
	}

	var gqlFavorites []*gqlmodel.Favorite
	for _, f := range favorites {
		gqlFavorites = append(gqlFavorites, toGraphFavorite(f))
	}
	return gqlFavorites, nil
}

// FavoriteCount is the resolver for the favoriteCount field on Post.
//
// favorites を選んで len を数えるのと違い、いいね行は1つも運ばない。
// 一覧では投稿の件数ぶんこれが呼ばれるので DataLoader で1クエリに畳む。
func (r *postResolver) FavoriteCount(ctx context.Context, obj *gqlmodel.Post) (int32, error) {
	numericPostID, err := decodeGraphID(ctx, "post", obj.ID)
	if err != nil {
		return 0, fmt.Errorf("invalid post id")
	}

	count, err := dataloader.For(ctx).FavoriteCountLoader.Load(ctx, numericPostID)
	if err != nil {
		return 0, err
	}
	return int32(count), nil
}

// IsFavoritedByMe is the resolver for the isFavoritedByMe field on Post.
//
// 未ログインでは常に false。いいねは本人にしか紐づかないので、
// 「自分」が居なければ答えは決まる（DBを引く必要も無い）。
func (r *postResolver) IsFavoritedByMe(ctx context.Context, obj *gqlmodel.Post) (bool, error) {
	claims, ok := auth.ClaimsFromContext(ctx)
	if !ok {
		return false, nil
	}
	numericPostID, err := decodeGraphID(ctx, "post", obj.ID)
	if err != nil {
		return false, fmt.Errorf("invalid post id")
	}

	return dataloader.For(ctx).FavoritedByMeLoader.Load(ctx,
		dataloader.FavoritedByKey{UserID: claims.ID, PostID: numericPostID})
}

// Parent is the resolver for the parent field on Post.
func (r *postResolver) Parent(ctx context.Context, obj *gqlmodel.Post) (*gqlmodel.Post, error) {
	if obj.Parent == nil {
		return nil, nil
	}
	numericParentID, err := decodeGraphID(ctx, "post", obj.Parent.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid parent post id")
	}

	// 返信が並ぶ画面では投稿ごとにこのフィールドが呼ばれるので DataLoader 経由で引く
	//（投稿 N 件で N クエリ → 1クエリ。同じ親を指す返信が並べばキャッシュで更に減る）。
	parent, err := dataloader.For(ctx).PostLoader.Load(ctx, numericParentID)
	if err != nil {
		return nil, err
	}
	if parent == nil {
		return nil, nil
	}

	var gqlGrandParent *gqlmodel.Post
	if parent.ParentID != nil && *parent.ParentID != 0 {
		gqlGrandParent = &gqlmodel.Post{ID: encodeGraphID("post", *parent.ParentID)}
	}

	gqlPost := toGraphPost(parent)
	gqlPost.Parent = gqlGrandParent
	return gqlPost, nil
}

// Replies is the resolver for the replies field.
func (r *postResolver) Replies(ctx context.Context, obj *gqlmodel.Post, limit *int32, offset *int32) ([]*gqlmodel.Post, error) {
	isAdmin := false
	if _, adminErr := requireAdminAuth(ctx); adminErr == nil {
		isAdmin = true
	} else {
		if _, userErr := requireAuth(ctx); userErr != nil {
			return nil, userErr
		} else if obj.DeletedAt != nil {
			return nil, nil // ユーザーには削除済みを見せない
		}
	}

	numericPostID, err := decodeGraphID(ctx, "post", obj.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid post id")
	}

	// admin/user で DataLoader を切り替えて soft-delete の可視性を制御する
	var replies []*model.Post
	var loaderErr error
	l, o := resolvePagination(limit, offset, 50)
	key := dataloader.ReplyPageKey{PostID: numericPostID, Page: repository.PageQuery{Limit: l, Offset: o}}

	if isAdmin {
		replies, loaderErr = dataloader.For(ctx).AdminReplyLoader.Load(ctx, key)
	} else {
		replies, loaderErr = dataloader.For(ctx).ReplyLoader.Load(ctx, key)
	}

	if loaderErr != nil {
		return nil, loaderErr
	}

	var gqlReplies []*gqlmodel.Post
	for _, reply := range replies {
		gqlReplies = append(gqlReplies, toGraphPost(reply))
	}
	return gqlReplies, nil
}

// Media is the resolver for the media field.
func (r *postResolver) Media(ctx context.Context, obj *gqlmodel.Post) ([]*gqlmodel.Media, error) {
	numericID, err := decodeGraphID(ctx, "post", obj.ID)
	if err != nil {
		return nil, nil
	}

	mediaList, err := dataloader.For(ctx).MediaLoader.Load(ctx, numericID)
	if err != nil {
		return nil, err
	}

	var result []*gqlmodel.Media
	for _, m := range mediaList {
		result = append(result, toGraphMedia(m, r.StorageRepository.PublicURL(m.StorageKey)))
	}
	return result, nil
}

// Mentions is the resolver for the mentions field.
func (r *postResolver) Mentions(ctx context.Context, obj *gqlmodel.Post) ([]*gqlmodel.Mention, error) {
	numericPostID, err := decodeGraphID(ctx, "post", obj.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid post id")
	}

	mentions, err := dataloader.For(ctx).PostMentionLoader.Load(ctx, numericPostID)
	if err != nil {
		return nil, err
	}
	return resolveMentions(ctx, mentions)
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, limit *int32, offset *int32) (*gqlmodel.PostPage, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}
	posts, total, err := r.ListPostsUseCase.Execute(ctx, resolvePageQuery(ctx, limit, offset, defaultPageSize))
	if err != nil {
		return nil, err
	}

	items := make([]*gqlmodel.Post, 0, len(posts))
	for _, post := range posts {
		items = append(items, toGraphPost(post))
	}
	return &gqlmodel.PostPage{Items: items, Total: int32(total)}, nil
}

// TopLevelPosts is the resolver for the topLevelPosts field.
func (r *queryResolver) TopLevelPosts(ctx context.Context, limit *int32, offset *int32) (*gqlmodel.PostPage, error) {
	_, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	posts, total, err := r.GetFeedPostsUseCase.Execute(ctx, resolvePageQuery(ctx, limit, offset, defaultPageSize))
	if err != nil {
		return nil, err
	}

	items := make([]*gqlmodel.Post, 0, len(posts))
	for _, post := range posts {
		items = append(items, toGraphPost(post))
	}
	return &gqlmodel.PostPage{Items: items, Total: int32(total)}, nil
}

// FollowersTopLevelPosts is the resolver for the followersTopLevelPosts field.
func (r *queryResolver) FollowersTopLevelPosts(ctx context.Context, userID string, limit *int32, offset *int32) (*gqlmodel.PostPage, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}

	numericUserID, err := decodeGraphID(ctx, "user", userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id")
	}
	posts, total, err := r.GetFollowersTopLevelPostsByUserIDUseCase.Execute(ctx, numericUserID, resolvePageQuery(ctx, limit, offset, defaultPageSize))
	if err != nil {
		return nil, err
	}

	items := make([]*gqlmodel.Post, 0, len(posts))
	for _, post := range posts {
		items = append(items, toGraphPost(post))
	}
	return &gqlmodel.PostPage{Items: items, Total: int32(total)}, nil
}

// NewFeedPostsCount is the resolver for the newFeedPostsCount field.
func (r *queryResolver) NewFeedPostsCount(ctx context.Context, since string) (int32, error) {
	_, err := requireAuth(ctx)
	if err != nil {
		return 0, err
	}
	sinceTime, err := time.Parse(time.RFC3339, since)
	if err != nil {
		return 0, fmt.Errorf("invalid since format: %w", err)
	}
	count, err := r.CountNewFeedPostsUseCase.Execute(ctx, sinceTime)
	if err != nil {
		return 0, err
	}
	return int32(count), nil
}

// GetRootPost is the resolver for the getRootPost field.
func (r *queryResolver) GetRootPost(ctx context.Context, id string) (*gqlmodel.Post, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	numericID, err := decodeGraphID(ctx, "post", id)
	if err != nil {
		return nil, fmt.Errorf("invalid post id")
	}
	post, err := r.GetRootPostUseCase.Execute(ctx, numericID)
	if err != nil {
		return nil, err
	}
	if post == nil {
		return nil, nil
	}
	return toGraphPost(post), nil
}

// GetPostByID is the resolver for the getPostByID field.
func (r *queryResolver) GetPostByID(ctx context.Context, id string) (*gqlmodel.Post, error) {
	_, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	numericID, err := decodeGraphID(ctx, "post", id)
	if err != nil {
		return nil, fmt.Errorf("invalid post id")
	}

	post, err := r.GetPostByIDUseCase.Execute(ctx, numericID)
	if err != nil {
		return nil, err
	}
	if post == nil {
		return nil, nil
	}

	return toGraphPost(post), nil
}

// GetPostByIDIncludeDeleted is the resolver for the getPostByIDIncludeDeleted field.
func (r *queryResolver) GetPostByIDIncludeDeleted(ctx context.Context, id string) (*gqlmodel.Post, error) {
	_, err := requireAdminAuth(ctx)
	if err != nil {
		return nil, err
	}
	numericID, err := decodeGraphID(ctx, "post", id)
	if err != nil {
		return nil, fmt.Errorf("invalid post id")
	}

	post, err := r.GetPostByIDIncludeDeletedUseCase.Execute(ctx, numericID)
	if err != nil {
		return nil, err
	}
	if post == nil {
		return nil, nil
	}

	return toGraphPost(post), nil
}

// GetPostsByUserID is the resolver for the getPostsByUserID field.
func (r *queryResolver) GetPostsByUserID(ctx context.Context, userID string, limit *int32, offset *int32) (*gqlmodel.PostPage, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	numericUserID, err := decodeGraphID(ctx, "user", userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id")
	}

	posts, total, err := r.GetPostsByUserIDUseCase.Execute(ctx, numericUserID, resolvePageQuery(ctx, limit, offset, defaultPageSize))
	if err != nil {
		return nil, err
	}
	items := make([]*gqlmodel.Post, 0, len(posts))
	for _, post := range posts {
		items = append(items, toGraphPost(post))
	}
	return &gqlmodel.PostPage{Items: items, Total: int32(total)}, nil
}

// GetRepliesByPostID is the resolver for the getRepliesByPostID field.
func (r *queryResolver) GetRepliesByPostID(ctx context.Context, postID string, limit *int32, offset *int32) ([]*gqlmodel.Post, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	numericPostID, err := decodeGraphID(ctx, "post", postID)
	if err != nil {
		return nil, fmt.Errorf("invalid post id")
	}

	replies, err := r.GetRepliesByIDUseCase.Execute(ctx, numericPostID, resolveUnpagedWindow(limit, offset))
	if err != nil {
		return nil, err
	}

	var gqlReplies []*gqlmodel.Post
	for _, reply := range replies {
		gqlReplies = append(gqlReplies, toGraphPost(reply))
	}
	return gqlReplies, nil
}

// GetFavoritePostsByUserID is the resolver for the getFavoritePostsByUserID field.
func (r *queryResolver) GetFavoritePostsByUserID(ctx context.Context, userID string, limit *int32, offset *int32) (*gqlmodel.PostPage, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	numericUserID, err := decodeGraphID(ctx, "user", userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id")
	}

	posts, total, err := r.GetFavoritePostsByUserIDUseCase.Execute(ctx, numericUserID, resolvePageQuery(ctx, limit, offset, defaultPageSize))
	if err != nil {
		return nil, err
	}
	items := make([]*gqlmodel.Post, 0, len(posts))
	for _, post := range posts {
		items = append(items, toGraphPost(post))
	}
	return &gqlmodel.PostPage{Items: items, Total: int32(total)}, nil
}

// SearchPosts is the resolver for the searchPosts field.
func (r *queryResolver) SearchPosts(ctx context.Context, keyword string, limit *int32, offset *int32) ([]*gqlmodel.Post, error) {
	_, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	l, o := resolvePagination(limit, offset, defaultPageSize)
	posts, err := r.SearchPostsUseCase.Execute(ctx, keyword, repository.PageQuery{Limit: l, Offset: o})
	if err != nil {
		return nil, err
	}

	var gqlPosts []*gqlmodel.Post
	for _, post := range posts {
		gqlPosts = append(gqlPosts, toGraphPost(post))
	}
	return gqlPosts, nil
}

// SearchPostsByHashtag is the resolver for the searchPostsByHashtag field.
func (r *queryResolver) SearchPostsByHashtag(ctx context.Context, tag string, limit *int32, offset *int32) ([]*gqlmodel.Post, error) {
	_, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	l, o := resolvePagination(limit, offset, defaultPageSize)
	posts, err := r.SearchPostsByHashtagUseCase.Execute(ctx, tag, repository.PageQuery{Limit: l, Offset: o})
	if err != nil {
		return nil, err
	}

	var gqlPosts []*gqlmodel.Post
	for _, post := range posts {
		gqlPosts = append(gqlPosts, toGraphPost(post))
	}
	return gqlPosts, nil
}

// PopularHashtags is the resolver for the popularHashtags field.
func (r *queryResolver) PopularHashtags(ctx context.Context) (*gqlmodel.HashtagSuggestionPage, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	// この一覧だけは窓をクライアントから受け取らない（常にユースケース側の
	// PopularHashtagsCap 件）ので、resolvePageQuery ではなく WithTotal だけを
	// 載せた PageQuery を渡す。判定に使う関数は他と同じ fieldRequested 1本。
	items, total, err := r.PopularHashtagsUseCase.Execute(ctx, repository.PageQuery{WithTotal: fieldRequested(ctx, "total")})
	if err != nil {
		return nil, err
	}
	return &gqlmodel.HashtagSuggestionPage{
		Items: toGraphHashtagSuggestions(items),
		Total: int32(total),
	}, nil
}

// SuggestHashtags is the resolver for the suggestHashtags field.
func (r *queryResolver) SuggestHashtags(ctx context.Context, prefix string, limit *int32) ([]*gqlmodel.HashtagSuggestion, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	// 既定値・上限はユースケース側（defaultSuggestLimit / maxSuggestLimit）が持つ。
	// 0 以下はそこで既定値に丸められるので、ここでは素通しでよい。
	l := 0
	if limit != nil {
		l = int(*limit)
	}
	suggestions, err := r.SuggestHashtagsUseCase.Execute(ctx, prefix, l)
	if err != nil {
		return nil, err
	}
	return toGraphHashtagSuggestions(suggestions), nil
}

// GetFavoriteByID is the resolver for the getFavoriteByID field.
func (r *queryResolver) GetFavoriteByID(ctx context.Context, id string) (*gqlmodel.Favorite, error) {
	//使ってないけど一応認証は必要にしておく
	_, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	numericID, err := decodeGraphID(ctx, "favorite", id)
	if err != nil {
		return nil, fmt.Errorf("invalid favorite id: %s", id)
	}

	f, err := r.GetFavoriteByIDUseCase.Execute(ctx, numericID)
	if err != nil {
		return nil, err
	}
	if f == nil {
		return nil, nil
	}

	return toGraphFavorite(f), nil
}

// Favorite returns FavoriteResolver implementation.
func (r *Resolver) Favorite() FavoriteResolver { return &favoriteResolver{r} }

// Post returns PostResolver implementation.
func (r *Resolver) Post() PostResolver { return &postResolver{r} }

type (
	favoriteResolver struct{ *Resolver }
	postResolver     struct{ *Resolver }
)
