# GraphQL schema example
#
# https://gqlgen.com/getting-started/
type Query {
  users: [User!]!
  getUserByID(id: ID!): User
  searchUsers(name: String!): [User!]!
  administrators: [Administrator!]!
  getAdministratorByID(id: ID!): Administrator
  searchAdministrators(name: String!): [Administrator!]!
  getProfileByUserID(userID: String!): Profile
  messages(roomID: ID!): [Message!]!
  room(id: ID!): Room
}

type User {
  ID: ID!
  userID: String!
  name: String!
  email: String!
  role: String!
  status: String!
  createdAt: String!
  updatedAt: String!
}

type Administrator {
  ID: ID!
  name: String!
  password: String!
  email: String!
  createdAt: String!
  updatedAt: String!
}

type UserAuthPayload {
  token: String!
  user: User!
}

type AdministratorAuthPayload {
  token: String!
  administrator: Administrator!
}

input LoginInput {
  email: String!
  password: String!
}

type Mutation {
  createUser(input: CreateUserInput!): User!
  deleteUser(id: ID!): Boolean!
  updateUser(input: UpdateUserInput!): User!
  loginUser(input: LoginInput!): UserAuthPayload!
  logoutUser(token: String!): Boolean!
  createAdministrator(input: CreateAdministratorInput!): Administrator!
  deleteAdministrator(id: ID!): Boolean!
  updateAdministrator(input: UpdateAdministratorInput!): Administrator!
  loginAdministrator(input: LoginInput!): AdministratorAuthPayload!
  logoutAdministrator(token: String!): Boolean!
  updateProfile(input: UpdateProfileInput!): Profile!
  sendMessage(roomID: ID!, userID: ID!, content: String!): Message!
  createRoom(input: CreateRoomInput!): Room!
  getOrCreateDMRoom(currentUserID: ID!, targetUserID: ID!): Room!
  addUserToRoom(input: AddUserToRoomInput!): Boolean!
  removeUserFromRoom(input: RemoveUserFromRoomInput!): Boolean!
}

input CreateAdministratorInput {
  name: String!
  email: String!
  password: String!
}

input UpdateAdministratorInput {
  ID: ID!
  name: String
  email: String
  password: String
}

input CreateUserInput {
  userID: String!
  name: String!
  email: String!
  password: String!
}

input UpdateUserInput {
  ID: ID!
  userID: String
  name: String
  email: String
  password: String
}

type Profile {
  userID: String!
  user: User!
  username: String!
  bio: String
  grade: Int
  image: String
  createdAt: String!
  updatedAt: String!
}

input UpdateProfileInput {
  userID: String!
  username: String
  bio: String
  grade: Int
  image: String
}

type Room {
  ID: ID!
  name: String!
  type: String!
  user: [User!]!
  description: String!
  createdAt: String!
  updatedAt: String!
}

type Message {
  ID: ID!
  roomID: ID!
  room: Room!
  userID: ID!
  user: User!
  content: String!
  createdAt: String!
  updatedAt: String!
}

input CreateRoomInput {
  name: String!
  description: String!
}

input UpdateRoomInput {
  ID: ID!
  name: String
  description: String
}

input AddUserToRoomInput {
  roomID: ID!
  userID: ID!
}

input RemoveUserFromRoomInput {
  roomID: ID!
  userID: ID!
}

type Subscription {
  messageAdded(roomID: ID!): Message!
}