package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"strconv"

	gqlmodel "github.com/Cityboypenguin/SPACE-server/graph/model"
	"github.com/Cityboypenguin/SPACE-server/model"
)

// User is the resolver for the user field.
func (r *favoriteResolver) User(ctx context.Context, obj *gqlmodel.Favorite) (*gqlmodel.User, error) {
	numericUserID, err := strconv.ParseInt(obj.User.ID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %s", obj.User.ID)
	}

	user, err := r.GetUserByIDUseCase.Execute(ctx, numericUserID)
	if err != nil {
		return nil, err
	}

	return &gqlmodel.User{
		ID:        fmt.Sprintf("%d", user.ID),
		AccountID: user.AccountID,
		Name:      user.Name,
		Email:     user.Email,
		Role:      user.Role,
		Status:    user.Status,
		CreatedAt: fmt.Sprintf("%s", user.CreatedAt),
		UpdatedAt: fmt.Sprintf("%s", user.UpdatedAt),
	}, nil
}

// Post is the resolver for the post field.
func (r *favoriteResolver) Post(ctx context.Context, obj *gqlmodel.Favorite) (*gqlmodel.Post, error) {
	numericPostID, err := strconv.ParseInt(obj.Post.ID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid post id: %s", obj.Post.ID)
	}

	post, err := r.GetPostByIDUseCase.Execute(ctx, numericPostID)
	if err != nil {
		return nil, err
	}

	var gqlParent *gqlmodel.Post
	if post.Parent != nil {
		gqlParent = &gqlmodel.Post{ID: fmt.Sprintf("%d", post.Parent.ID)}
	}

	return &gqlmodel.Post{
		ID:        fmt.Sprintf("%d", post.ID),
		Content:   post.Content,
		CreatedAt: fmt.Sprintf("%s", post.CreatedAt),
		UpdatedAt: fmt.Sprintf("%s", post.UpdatedAt),
		User: &gqlmodel.User{
			ID: fmt.Sprintf("%d", post.User.ID),
		},
		Parent: gqlParent,
	}, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input gqlmodel.CreateUserInput) (*gqlmodel.User, error) {
	param := model.CreateUserParam{
		AccountID: input.AccountID,
		Name:      input.Name,
		Email:     input.Email,
		Password:  input.Password,
	}

	user, err := r.CreateUserUseCase.Execute(ctx, param)
	if err != nil {
		return nil, err
	}

	return &gqlmodel.User{
		ID:        fmt.Sprintf("%d", user.ID),
		AccountID: user.AccountID,
		Name:      user.Name,
		Email:     user.Email,
		Role:      user.Role,
		Status:    user.Status,
		CreatedAt: fmt.Sprintf("%s", user.CreatedAt),
		UpdatedAt: fmt.Sprintf("%s", user.UpdatedAt),
	}, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	numericID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return false, fmt.Errorf("invalid user id: %s", id)
	}

	deleted, err := r.DeleteUserUseCase.Execute(ctx, numericID)
	if err != nil {
		return false, err
	}

	return deleted, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input gqlmodel.UpdateUserInput) (*gqlmodel.User, error) {
	numericID, err := strconv.ParseInt(input.ID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %s", input.ID)
	}

	// Validate that the user exists before updating
	_, err = r.GetUserByIDUseCase.Execute(ctx, numericID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %s", input.ID)
	}

	param := model.UpdateUserParam{
		Name:     input.Name,
		Email:    input.Email,
		Password: input.Password,
	}

	user, err := r.UpdateUserUseCase.Execute(ctx, numericID, param)
	if err != nil {
		return nil, err
	}

	return &gqlmodel.User{
		ID:        fmt.Sprintf("%d", user.ID),
		AccountID: user.AccountID,
		Name:      user.Name,
		Email:     user.Email,
		Role:      user.Role,
		Status:    user.Status,
		CreatedAt: fmt.Sprintf("%s", user.CreatedAt),
		UpdatedAt: fmt.Sprintf("%s", user.UpdatedAt),
	}, nil
}

// LoginUser is the resolver for the loginUser field.
func (r *mutationResolver) LoginUser(ctx context.Context, input gqlmodel.LoginInput) (*gqlmodel.UserAuthPayload, error) {
	result, err := r.LoginUserUseCase.Execute(ctx, input.Email, input.Password)
	if err != nil {
		return nil, err
	}

	return &gqlmodel.UserAuthPayload{
		Token: result.Token,
		User: &gqlmodel.User{
			ID:        fmt.Sprintf("%d", result.User.ID),
			AccountID: result.User.AccountID,
			Name:      result.User.Name,
			Email:     result.User.Email,
			Role:      result.User.Role,
			Status:    result.User.Status,
			CreatedAt: fmt.Sprintf("%s", result.User.CreatedAt),
			UpdatedAt: fmt.Sprintf("%s", result.User.UpdatedAt),
		},
	}, nil
}

// LogoutUser is the resolver for the logoutUser field.
func (r *mutationResolver) LogoutUser(ctx context.Context, token string) (bool, error) {
	if err := r.LogoutUserUseCase.Execute(ctx, token); err != nil {
		return false, err
	}
	return true, nil
}

// CreateAdministrator is the resolver for the createAdministrator field.
func (r *mutationResolver) CreateAdministrator(ctx context.Context, input gqlmodel.CreateAdministratorInput) (*gqlmodel.Administrator, error) {
	param := model.CreateAdministratorParam{
		Name:     input.Name,
		Email:    input.Email,
		Password: input.Password,
	}

	administrator, err := r.CreateAdministratorUseCase.Execute(ctx, param)
	if err != nil {
		return nil, err
	}

	return &gqlmodel.Administrator{
		ID:        fmt.Sprintf("%d", administrator.ID),
		Name:      administrator.Name,
		Email:     administrator.Email,
		Password:  administrator.HashedPassword,
		CreatedAt: fmt.Sprintf("%s", administrator.CreatedAt),
		UpdatedAt: fmt.Sprintf("%s", administrator.UpdatedAt),
	}, nil
}

// DeleteAdministrator is the resolver for the deleteAdministrator field.
func (r *mutationResolver) DeleteAdministrator(ctx context.Context, id string) (bool, error) {
	numericID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return false, fmt.Errorf("invalid administrator id: %s", id)
	}

	deleted, err := r.DeleteAdministratorUseCase.Execute(ctx, numericID)
	if err != nil {
		return false, err
	}

	return deleted, nil
}

// UpdateAdministrator is the resolver for the updateAdministrator field.
func (r *mutationResolver) UpdateAdministrator(ctx context.Context, input gqlmodel.UpdateAdministratorInput) (*gqlmodel.Administrator, error) {
	numericID, err := strconv.ParseInt(input.ID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid administrator id: %s", input.ID)
	}

	param := model.UpdateAdministratorParam{
		Name:     input.Name,
		Email:    input.Email,
		Password: input.Password,
	}

	admin, err := r.UpdateAdministratorUseCase.Execute(ctx, numericID, param)
	if err != nil {
		return nil, err
	}

	return &gqlmodel.Administrator{
		ID:        fmt.Sprintf("%d", admin.ID),
		Name:      admin.Name,
		Email:     admin.Email,
		Password:  admin.HashedPassword,
		CreatedAt: fmt.Sprintf("%s", admin.CreatedAt),
		UpdatedAt: fmt.Sprintf("%s", admin.UpdatedAt),
	}, nil
}

// LoginAdministrator is the resolver for the loginAdministrator field.
func (r *mutationResolver) LoginAdministrator(ctx context.Context, input gqlmodel.LoginInput) (*gqlmodel.AdministratorAuthPayload, error) {
	result, err := r.LoginAdministratorUseCase.Execute(ctx, input.Email, input.Password)
	if err != nil {
		return nil, err
	}

	return &gqlmodel.AdministratorAuthPayload{
		Token: result.Token,
		Administrator: &gqlmodel.Administrator{
			ID:        fmt.Sprintf("%d", result.Administrator.ID),
			Name:      result.Administrator.Name,
			Email:     result.Administrator.Email,
			Password:  result.Administrator.HashedPassword,
			CreatedAt: fmt.Sprintf("%s", result.Administrator.CreatedAt),
			UpdatedAt: fmt.Sprintf("%s", result.Administrator.UpdatedAt),
		},
	}, nil
}

// LogoutAdministrator is the resolver for the logoutAdministrator field.
func (r *mutationResolver) LogoutAdministrator(ctx context.Context, token string) (bool, error) {
	if err := r.LogoutAdministratorUseCase.Execute(ctx, token); err != nil {
		return false, err
	}
	return true, nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input gqlmodel.CreatePostInput) (*gqlmodel.Post, error) {
	numericUserID, err := strconv.ParseInt(input.UserID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %s", input.UserID)
	}

	var numericParentID *int64
	if input.ParentID != nil {
		parentID, err := strconv.ParseInt(*input.ParentID, 10, 64)
		if err != nil {
			return nil, fmt.Errorf("invalid parent post id: %s", *input.ParentID)
		}
		numericParentID = &parentID
	}

	param := model.CreatePostParam{
		UserID:   numericUserID,
		Content:  input.Content,
		ParentID: numericParentID,
	}

	post, err := r.CreatePostUseCase.Execute(ctx, param)
	if err != nil {
		return nil, err
	}

	var gqlParent *gqlmodel.Post
	if input.ParentID != nil {
		gqlParent = &gqlmodel.Post{ID: *input.ParentID} // IDだけ詰めてバトンにする！
	}

	return &gqlmodel.Post{
		ID:        fmt.Sprintf("%d", post.ID),
		Content:   post.Content,
		CreatedAt: fmt.Sprintf("%s", post.CreatedAt),
		UpdatedAt: fmt.Sprintf("%s", post.UpdatedAt),
		User: &gqlmodel.User{
			ID: fmt.Sprintf("%d", post.User.ID),
		},
		Parent: gqlParent,
	}, nil
}

// DeletePost is the resolver for the deletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, id string) (bool, error) {
	numericID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return false, fmt.Errorf("invalid post id: %s", id)
	}

	deleted, err := r.DeletePostUseCase.Execute(ctx, numericID)
	if err != nil {
		return false, err
	}

	return deleted, nil
}

// UpdatePost is the resolver for the updatePost field.
func (r *mutationResolver) UpdatePost(ctx context.Context, input gqlmodel.UpdatePostInput) (*gqlmodel.Post, error) {
	numericID, err := strconv.ParseInt(input.ID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid post id: %s", input.ID)
	}

	param := model.UpdatePostParam{
		Content: input.Content,
	}

	post, err := r.UpdatePostUseCase.Execute(ctx, numericID, param)
	if err != nil {
		return nil, err
	}

	return &gqlmodel.Post{
		ID:        fmt.Sprintf("%d", post.ID),
		Content:   post.Content,
		CreatedAt: fmt.Sprintf("%s", post.CreatedAt),
		UpdatedAt: fmt.Sprintf("%s", post.UpdatedAt),
		User: &gqlmodel.User{
			ID: fmt.Sprintf("%d", post.User.ID),
		},
	}, nil
}

// CreateFavorite is the resolver for the createFavorite field.
func (r *mutationResolver) CreateFavorite(ctx context.Context, input gqlmodel.CreateFavoriteInput) (*gqlmodel.Favorite, error) {
	numericUserID, err := strconv.ParseInt(input.UserID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %s", input.UserID)
	}

	numericPostID, err := strconv.ParseInt(input.PostID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid post id: %s", input.PostID)
	}

	param := model.CreateFavoriteParam{
		UserID: numericUserID,
		PostID: numericPostID,
	}

	favorite, err := r.CreateFavoriteUseCase.Execute(ctx, param)
	if err != nil {
		return nil, err
	}

	return &gqlmodel.Favorite{
		ID:        fmt.Sprintf("%d", favorite.ID),
		CreatedAt: fmt.Sprintf("%s", favorite.CreatedAt),
		User: &gqlmodel.User{
			ID: fmt.Sprintf("%d", favorite.User.ID),
		},
		Post: &gqlmodel.Post{
			ID: fmt.Sprintf("%d", favorite.Post.ID),
		},
	}, nil
}

// DeleteFavorite is the resolver for the deleteFavorite field.
func (r *mutationResolver) DeleteFavorite(ctx context.Context, input gqlmodel.DeleteFavoriteInput) (bool, error) {
	numericUserID, err := strconv.ParseInt(input.UserID, 10, 64)
	if err != nil {
		return false, fmt.Errorf("invalid user id: %s", input.UserID)
	}

	numericPostID, err := strconv.ParseInt(input.PostID, 10, 64)
	if err != nil {
		return false, fmt.Errorf("invalid post id: %s", input.PostID)
	}

	deleted, err := r.DeleteFavoriteByUserIDAndPostIDUseCase.Execute(ctx, numericUserID, numericPostID)
	if err != nil {
		return false, err
	}

	return deleted, nil
}

// User is the resolver for the user field.
func (r *postResolver) User(ctx context.Context, obj *gqlmodel.Post) (*gqlmodel.User, error) {
	numericUserID, err := strconv.ParseInt(obj.User.ID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %s", obj.User.ID)
	}

	user, err := r.GetUserByIDUseCase.Execute(ctx, numericUserID)
	if err != nil {
		return nil, err
	}

	return &gqlmodel.User{
		ID:        fmt.Sprintf("%d", user.ID),
		AccountID: user.AccountID,
		Name:      user.Name,
		Email:     user.Email,
		Role:      user.Role,
		Status:    user.Status,
		CreatedAt: fmt.Sprintf("%s", user.CreatedAt),
		UpdatedAt: fmt.Sprintf("%s", user.UpdatedAt),
	}, nil
}

// Favorites is the resolver for the favorites field.
func (r *postResolver) Favorites(ctx context.Context, obj *gqlmodel.Post) ([]*gqlmodel.Favorite, error) {
	numericPostID, err := strconv.ParseInt(obj.ID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid post id: %s", obj.ID)
	}

	favorites, err := r.GetFavoritesByPostIDUseCase.Execute(ctx, numericPostID)
	if err != nil {
		return nil, err
	}

	var gqlFavorites []*gqlmodel.Favorite
	for _, favorite := range favorites {
		gqlFavorites = append(gqlFavorites, &gqlmodel.Favorite{
			ID:        fmt.Sprintf("%d", favorite.ID),
			CreatedAt: fmt.Sprintf("%s", favorite.CreatedAt),
			User: &gqlmodel.User{
				ID: fmt.Sprintf("%d", favorite.User.ID),
			},
			Post: &gqlmodel.Post{
				ID: fmt.Sprintf("%d", favorite.Post.ID),
			},
		})
	}

	return gqlFavorites, nil
}

// Parent is the resolver for the parent field.
func (r *postResolver) Parent(ctx context.Context, obj *gqlmodel.Post) (*gqlmodel.Post, error) {
	if obj.Parent == nil {
		return nil, nil
	}
	numericParentID, err := strconv.ParseInt(obj.Parent.ID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid parent post id: %s", obj.Parent.ID)
	}

	parentPost, err := r.GetPostByIDUseCase.Execute(ctx, numericParentID)
	if err != nil {
		return nil, err
	}

	var grandParent *gqlmodel.Post
	if parentPost.Parent != nil && parentPost.Parent.ID != 0 {
		grandParent = &gqlmodel.Post{ID: fmt.Sprintf("%d", parentPost.Parent.ID)}
	}

	return &gqlmodel.Post{
		ID:        fmt.Sprintf("%d", parentPost.ID),
		Content:   parentPost.Content,
		CreatedAt: fmt.Sprintf("%s", parentPost.CreatedAt),
		UpdatedAt: fmt.Sprintf("%s", parentPost.UpdatedAt),
		User:      &gqlmodel.User{ID: fmt.Sprintf("%d", parentPost.User.ID)},
		Parent:    grandParent,
	}, nil
}

// Replies is the resolver for the replies field.
func (r *postResolver) Replies(ctx context.Context, obj *gqlmodel.Post) ([]*gqlmodel.Post, error) {
	numericPostID, err := strconv.ParseInt(obj.ID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid post id: %s", obj.ID)
	}

	replies, err := r.GetRepliesByIDUseCase.Execute(ctx, numericPostID)
	if err != nil {
		return nil, err
	}

	var gqlReplies []*gqlmodel.Post
	for _, reply := range replies {
		gqlReplies = append(gqlReplies, &gqlmodel.Post{
			ID:        fmt.Sprintf("%d", reply.ID),
			Content:   reply.Content,
			CreatedAt: fmt.Sprintf("%s", reply.CreatedAt),
			UpdatedAt: fmt.Sprintf("%s", reply.UpdatedAt),
			User:      &gqlmodel.User{ID: fmt.Sprintf("%d", reply.User.ID)},
			Parent:    &gqlmodel.Post{ID: obj.ID},
		})
	}

	return gqlReplies, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*gqlmodel.User, error) {
	users, err := r.ListUsersUseCase.Execute(ctx)
	if err != nil {
		return nil, err
	}

	var gqlUsers []*gqlmodel.User
	for _, user := range users {
		gqlUsers = append(gqlUsers, &gqlmodel.User{
			ID:        fmt.Sprintf("%d", user.ID),
			AccountID: user.AccountID,
			Name:      user.Name,
			Email:     user.Email,
			Role:      user.Role,
			Status:    user.Status,
			CreatedAt: fmt.Sprintf("%s", user.CreatedAt),
			UpdatedAt: fmt.Sprintf("%s", user.UpdatedAt),
		})
	}
	return gqlUsers, nil
}

// GetUserByID is the resolver for the getUserByID field.
func (r *queryResolver) GetUserByID(ctx context.Context, id string) (*gqlmodel.User, error) {
	numericID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %s", id)
	}

	user, err := r.GetUserByIDUseCase.Execute(ctx, numericID)
	if err != nil {
		return nil, err
	}

	posts, err := r.GetPostsByUserIDUseCase.Execute(ctx, numericID)
	if err != nil {
		return nil, err
	}

	favorites, err := r.GetFavoritesByUserIDUseCase.Execute(ctx, numericID)
	if err != nil {
		return nil, err
	}

	var gqlPosts []*gqlmodel.Post
	for _, post := range posts {
		gqlPosts = append(gqlPosts, &gqlmodel.Post{
			ID:        fmt.Sprintf("%d", post.ID),
			Content:   post.Content,
			CreatedAt: fmt.Sprintf("%s", post.CreatedAt),
			UpdatedAt: fmt.Sprintf("%s", post.UpdatedAt),
		})
	}

	var gqlFavorites []*gqlmodel.Favorite
	for _, favorite := range favorites {
		gqlFavorites = append(gqlFavorites, &gqlmodel.Favorite{
			ID:        fmt.Sprintf("%d", favorite.ID),
			CreatedAt: fmt.Sprintf("%s", favorite.CreatedAt),
		})
	}

	return &gqlmodel.User{
		ID:        fmt.Sprintf("%d", user.ID),
		AccountID: user.AccountID,
		Name:      user.Name,
		Email:     user.Email,
		Role:      user.Role,
		Status:    user.Status,
		CreatedAt: fmt.Sprintf("%s", user.CreatedAt),
		UpdatedAt: fmt.Sprintf("%s", user.UpdatedAt),
		Posts:     gqlPosts,
		Favorites: gqlFavorites,
	}, nil
}

// SearchUsers is the resolver for the searchUsers field.
func (r *queryResolver) SearchUsers(ctx context.Context, name string) ([]*gqlmodel.User, error) {
	users, err := r.SearchUsersUseCase.Execute(ctx, name)
	if err != nil {
		return nil, err
	}

	var gqlUsers []*gqlmodel.User
	for _, user := range users {
		gqlUsers = append(gqlUsers, &gqlmodel.User{
			ID:        fmt.Sprintf("%d", user.ID),
			AccountID: user.AccountID,
			Name:      user.Name,
			Email:     user.Email,
			Role:      user.Role,
			Status:    user.Status,
			CreatedAt: fmt.Sprintf("%s", user.CreatedAt),
			UpdatedAt: fmt.Sprintf("%s", user.UpdatedAt),
		})
	}
	return gqlUsers, nil
}

// Administrators is the resolver for the administrators field.
func (r *queryResolver) Administrators(ctx context.Context) ([]*gqlmodel.Administrator, error) {
	admins, err := r.ListAdministratorsUseCase.Execute(ctx)
	if err != nil {
		return nil, err
	}

	var gqlAdmins []*gqlmodel.Administrator
	for _, admin := range admins {
		gqlAdmins = append(gqlAdmins, &gqlmodel.Administrator{
			ID:        fmt.Sprintf("%d", admin.ID),
			Name:      admin.Name,
			Email:     admin.Email,
			Password:  admin.HashedPassword,
			CreatedAt: fmt.Sprintf("%s", admin.CreatedAt),
			UpdatedAt: fmt.Sprintf("%s", admin.UpdatedAt),
		})
	}
	return gqlAdmins, nil
}

// GetAdministratorByID is the resolver for the getAdministratorByID field.
func (r *queryResolver) GetAdministratorByID(ctx context.Context, id string) (*gqlmodel.Administrator, error) {
	numericID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid administrator id: %s", id)
	}

	admin, err := r.GetAdministratorByIDUseCase.Execute(ctx, numericID)
	if err != nil {
		return nil, err
	}

	return &gqlmodel.Administrator{
		ID:        fmt.Sprintf("%d", admin.ID),
		Name:      admin.Name,
		Email:     admin.Email,
		Password:  admin.HashedPassword,
		CreatedAt: fmt.Sprintf("%s", admin.CreatedAt),
		UpdatedAt: fmt.Sprintf("%s", admin.UpdatedAt),
	}, nil
}

// SearchAdministrators is the resolver for the searchAdministrators field.
func (r *queryResolver) SearchAdministrators(ctx context.Context, name string) ([]*gqlmodel.Administrator, error) {
	admins, err := r.SearchAdministratorsUseCase.Execute(ctx, name)
	if err != nil {
		return nil, err
	}

	var gqlAdmins []*gqlmodel.Administrator
	for _, admin := range admins {
		gqlAdmins = append(gqlAdmins, &gqlmodel.Administrator{
			ID:        fmt.Sprintf("%d", admin.ID),
			Name:      admin.Name,
			Email:     admin.Email,
			Password:  admin.HashedPassword,
			CreatedAt: fmt.Sprintf("%s", admin.CreatedAt),
			UpdatedAt: fmt.Sprintf("%s", admin.UpdatedAt),
		})
	}
	return gqlAdmins, nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context) ([]*gqlmodel.Post, error) {
	posts, err := r.ListPostsUseCase.Execute(ctx)
	if err != nil {
		return nil, err
	}

	var gqlPosts []*gqlmodel.Post
	for _, post := range posts {
		var gqlParent *gqlmodel.Post
		if post.Parent != nil {
			gqlParent = &gqlmodel.Post{ID: fmt.Sprintf("%d", post.Parent.ID)}
		}
		gqlPosts = append(gqlPosts, &gqlmodel.Post{
			ID:        fmt.Sprintf("%d", post.ID),
			Content:   post.Content,
			CreatedAt: fmt.Sprintf("%s", post.CreatedAt),
			UpdatedAt: fmt.Sprintf("%s", post.UpdatedAt),
			User: &gqlmodel.User{
				ID: fmt.Sprintf("%d", post.User.ID),
			},
			Parent: gqlParent,
		})
	}
	return gqlPosts, nil
}

// TopLevelPosts is the resolver for the topLevelPosts field.
func (r *queryResolver) TopLevelPosts(ctx context.Context) ([]*gqlmodel.Post, error) {
	posts, err := r.ListTopLevelPostsUseCase.Execute(ctx)
	if err != nil {
		return nil, err
	}

	var gqlPosts []*gqlmodel.Post
	for _, post := range posts {
		gqlPosts = append(gqlPosts, &gqlmodel.Post{
			ID:        fmt.Sprintf("%d", post.ID),
			Content:   post.Content,
			CreatedAt: fmt.Sprintf("%s", post.CreatedAt),
			UpdatedAt: fmt.Sprintf("%s", post.UpdatedAt),
			User: &gqlmodel.User{
				ID: fmt.Sprintf("%d", post.User.ID),
			},
		})
	}
	return gqlPosts, nil
}

// GetPostByID is the resolver for the getPostByID field.
func (r *queryResolver) GetPostByID(ctx context.Context, id string) (*gqlmodel.Post, error) {
	numericID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid post id: %s", id)
	}

	post, err := r.GetPostByIDUseCase.Execute(ctx, numericID)
	if err != nil {
		return nil, err
	}

	var gqlParent *gqlmodel.Post
	if post.Parent != nil {
		gqlParent = &gqlmodel.Post{ID: fmt.Sprintf("%d", post.Parent.ID)}
	}

	return &gqlmodel.Post{
		ID:        fmt.Sprintf("%d", post.ID),
		Content:   post.Content,
		CreatedAt: fmt.Sprintf("%s", post.CreatedAt),
		UpdatedAt: fmt.Sprintf("%s", post.UpdatedAt),
		User: &gqlmodel.User{
			ID: fmt.Sprintf("%d", post.User.ID),
		},
		Parent: gqlParent,
	}, nil
}

// GetRepliesByPostID is the resolver for the getRepliesByPostID field.
func (r *queryResolver) GetRepliesByPostID(ctx context.Context, postID string) ([]*gqlmodel.Post, error) {
	numericPostID, err := strconv.ParseInt(postID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid post id: %s", postID)
	}

	replies, err := r.GetRepliesByIDUseCase.Execute(ctx, numericPostID)
	if err != nil {
		return nil, err
	}

	var gqlReplies []*gqlmodel.Post
	for _, reply := range replies {
		gqlReplies = append(gqlReplies, &gqlmodel.Post{
			ID:        fmt.Sprintf("%d", reply.ID),
			Content:   reply.Content,
			CreatedAt: fmt.Sprintf("%s", reply.CreatedAt),
			UpdatedAt: fmt.Sprintf("%s", reply.UpdatedAt),
			User: &gqlmodel.User{
				ID: fmt.Sprintf("%d", reply.User.ID),
			},
			Parent: &gqlmodel.Post{ID: postID},
		})
	}

	return gqlReplies, nil
}

// SearchPosts is the resolver for the searchPosts field.
func (r *queryResolver) SearchPosts(ctx context.Context, content string) ([]*gqlmodel.Post, error) {
	posts, err := r.SearchPostsUseCase.Execute(ctx, content)
	if err != nil {
		return nil, err
	}

	var gqlPosts []*gqlmodel.Post
	for _, post := range posts {
		var gqlParent *gqlmodel.Post
		if post.Parent != nil {
			gqlParent = &gqlmodel.Post{ID: fmt.Sprintf("%d", post.Parent.ID)}
		}
		gqlPosts = append(gqlPosts, &gqlmodel.Post{
			ID:        fmt.Sprintf("%d", post.ID),
			Content:   post.Content,
			CreatedAt: fmt.Sprintf("%s", post.CreatedAt),
			UpdatedAt: fmt.Sprintf("%s", post.UpdatedAt),
			User: &gqlmodel.User{
				ID: fmt.Sprintf("%d", post.User.ID),
			},
			Parent: gqlParent,
		})
	}
	return gqlPosts, nil
}

// Favorites is the resolver for the favorites field.
func (r *queryResolver) Favorites(ctx context.Context) ([]*gqlmodel.Favorite, error) {
	favorites, err := r.ListFavoritesUseCase.Execute(ctx)
	if err != nil {
		return nil, err
	}

	var gqlFavorites []*gqlmodel.Favorite
	for _, favorite := range favorites {
		gqlFavorites = append(gqlFavorites, &gqlmodel.Favorite{
			ID:        fmt.Sprintf("%d", favorite.ID),
			CreatedAt: fmt.Sprintf("%s", favorite.CreatedAt),
			User: &gqlmodel.User{
				ID: fmt.Sprintf("%d", favorite.User.ID),
			},
			Post: &gqlmodel.Post{
				ID: fmt.Sprintf("%d", favorite.Post.ID),
			},
		})
	}
	return gqlFavorites, nil
}

// GetFavoriteByID is the resolver for the getFavoriteByID field.
func (r *queryResolver) GetFavoriteByID(ctx context.Context, id string) (*gqlmodel.Favorite, error) {
	numericID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid favorite id: %s", id)
	}

	favorite, err := r.GetFavoriteByIDUseCase.Execute(ctx, numericID)
	if err != nil {
		return nil, err
	}

	return &gqlmodel.Favorite{
		ID:        fmt.Sprintf("%d", favorite.ID),
		CreatedAt: fmt.Sprintf("%s", favorite.CreatedAt),
		User: &gqlmodel.User{
			ID: fmt.Sprintf("%d", favorite.User.ID),
		},
		Post: &gqlmodel.Post{
			ID: fmt.Sprintf("%d", favorite.Post.ID),
		},
	}, nil
}

// Favorite returns FavoriteResolver implementation.
func (r *Resolver) Favorite() FavoriteResolver { return &favoriteResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Post returns PostResolver implementation.
func (r *Resolver) Post() PostResolver { return &postResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type favoriteResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
