package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"errors"
	"fmt"
	"strconv"

	"github.com/Cityboypenguin/SPACE-server/graph/model"
)

// SignUp is the resolver for the signUp field.
func (r *mutationResolver) SignUp(ctx context.Context, in model.SignUpInput) (*model.User, error) {
	u, err := r.SignUpUseCase.Execute(ctx, in)
	if err != nil {
		return nil, errors.Join(err)
	}
	return &model.User{
		ID:        strconv.FormatInt(u.ID, 10),
		Name:      u.Name,
		CreatedAt: u.CreatedAt.String(),
		UpdatedAt: u.CreatedAt.String(),
	}, nil
}

// Hello is the resolver for the hello field.
func (r *queryResolver) Hello(ctx context.Context) (string, error) {
	return "hello", nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
