package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"strconv"

	gqlmodel "github.com/Cityboypenguin/SPACE-server/graph/model"
	"github.com/Cityboypenguin/SPACE-server/model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input gqlmodel.CreateUserInput) (*gqlmodel.User, error) {
	param := model.CreateUserParam{
		UserID:   input.UserID,
		Name:     input.Name,
		Email:    input.Email,
		Password: input.Password,
	}

	user, err := r.CreateUserUseCase.Execute(ctx, param)
	if err != nil {
		return nil, err
	}

	return &gqlmodel.User{
		ID:        fmt.Sprintf("%d", user.ID),
		UserID:    user.UserID,
		Name:      user.Name,
		Email:     user.Email,
		Role:      user.Role,
		Status:    user.Status,
		CreatedAt: fmt.Sprintf("%d", user.CreatedAt),
		UpdatedAt: fmt.Sprintf("%d", user.UpdatedAt),
	}, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	numericID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return false, fmt.Errorf("invalid user id: %s", id)
	}

	deleted, err := r.DeleteUserUseCase.Execute(ctx, numericID)
	if err != nil {
		return false, err
	}

	return deleted, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input gqlmodel.UpdateUserInput) (*gqlmodel.User, error) {
	numericID, err := strconv.ParseInt(input.ID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %s", input.ID)
	}

	// Validate that the user exists before updating
	_, err = r.GetUserByIDUseCase.Execute(ctx, numericID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %s", input.ID)
	}

	param := model.UpdateUserParam{
		Name:     input.Name,
		Email:    input.Email,
		Password: input.Password,
	}

	user, err := r.UpdateUserUseCase.Execute(ctx, numericID, param)
	if err != nil {
		return nil, err
	}

	return &gqlmodel.User{
		ID:        fmt.Sprintf("%d", user.ID),
		UserID:    user.UserID,
		Name:      user.Name,
		Email:     user.Email,
		Role:      user.Role,
		Status:    user.Status,
		CreatedAt: fmt.Sprintf("%d", user.CreatedAt),
		UpdatedAt: fmt.Sprintf("%d", user.UpdatedAt),
	}, nil
}

// CreateAdministrator is the resolver for the createAdministrator field.
func (r *mutationResolver) CreateAdministrator(ctx context.Context, input gqlmodel.CreateAdministratorInput) (*gqlmodel.Administrator, error) {
	param := model.CreateAdministratorParam{
		Name:     input.Name,
		Email:    input.Email,
		Password: input.Password,
	}

	administrator, err := r.CreateAdministratorUseCase.Execute(ctx, param)
	if err != nil {
		return nil, err
	}

	return &gqlmodel.Administrator{
		ID:        fmt.Sprintf("%d", administrator.ID),
		Name:      administrator.Name,
		Email:     administrator.Email,
		Password:  administrator.HashedPassword,
		CreatedAt: fmt.Sprintf("%d", administrator.CreatedAt),
		UpdatedAt: fmt.Sprintf("%d", administrator.UpdatedAt),
	}, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*gqlmodel.User, error) {
	users, err := r.ListUsersUseCase.Execute(ctx)
	if err != nil {
		return nil, err
	}

	var gqlUsers []*gqlmodel.User
	for _, user := range users {
		gqlUsers = append(gqlUsers, &gqlmodel.User{
			ID:        fmt.Sprintf("%d", user.ID),
			UserID:    user.UserID,
			Name:      user.Name,
			Email:     user.Email,
			Role:      user.Role,
			Status:    user.Status,
			CreatedAt: fmt.Sprintf("%d", user.CreatedAt),
			UpdatedAt: fmt.Sprintf("%d", user.UpdatedAt),
		})
	}
	return gqlUsers, nil
}

// GetUserByID is the resolver for the getUserByID field.
func (r *queryResolver) GetUserByID(ctx context.Context, id string) (*gqlmodel.User, error) {
	numericID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %s", id)
	}

	user, err := r.GetUserByIDUseCase.Execute(ctx, numericID)
	if err != nil {
		return nil, err
	}

	return &gqlmodel.User{
		ID:        fmt.Sprintf("%d", user.ID),
		UserID:    user.UserID,
		Name:      user.Name,
		Email:     user.Email,
		Role:      user.Role,
		Status:    user.Status,
		CreatedAt: fmt.Sprintf("%d", user.CreatedAt),
		UpdatedAt: fmt.Sprintf("%d", user.UpdatedAt),
	}, nil
}

// SearchUsers is the resolver for the searchUsers field.
func (r *queryResolver) SearchUsers(ctx context.Context, name string) ([]*gqlmodel.User, error) {
	users, err := r.SearchUsersUseCase.Execute(ctx, name)
	if err != nil {
		return nil, err
	}

	var gqlUsers []*gqlmodel.User
	for _, user := range users {
		gqlUsers = append(gqlUsers, &gqlmodel.User{
			ID:        fmt.Sprintf("%d", user.ID),
			UserID:    user.UserID,
			Name:      user.Name,
			Email:     user.Email,
			Role:      user.Role,
			Status:    user.Status,
			CreatedAt: fmt.Sprintf("%d", user.CreatedAt),
			UpdatedAt: fmt.Sprintf("%d", user.UpdatedAt),
		})
	}
	return gqlUsers, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
