package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"
	"strconv"
	"time"

	gqlmodel "github.com/Cityboypenguin/SPACE-server/graph/model"
	"github.com/Cityboypenguin/SPACE-server/model"
	termsuc "github.com/Cityboypenguin/SPACE-server/usecase/terms"
)

// CreateTermsOfService is the resolver for the createTermsOfService field.
func (r *mutationResolver) CreateTermsOfService(ctx context.Context, input gqlmodel.CreateTermsOfServiceInput) (*gqlmodel.TermsOfService, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}

	effectiveDate, err := time.Parse(timeFormat, input.EffectiveDate)
	if err != nil {
		return nil, fmt.Errorf("invalid effectiveDate format: %w", err)
	}

	t, err := r.CreateTermsUseCase.Execute(ctx, termsuc.CreateTermsInput{
		Version:       input.Version,
		ObjectKey:     input.ObjectKey,
		EffectiveDate: effectiveDate,
	})
	if err != nil {
		return nil, err
	}

	r.TermsBroadcastScheduler.Schedule(t.Version, t.EffectiveDate)

	return toGraphTerms(t, r.StorageRepository.PublicURL(t.ObjectKey)), nil
}

// ConsentToTerms is the resolver for the consentToTerms field.
func (r *mutationResolver) ConsentToTerms(ctx context.Context, termsID string) (bool, error) {
	_, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}

	tid, err := decodeGraphID(ctx, "terms", termsID)
	if err != nil {
		return false, fmt.Errorf("invalid terms id")
	}

	if err := r.ConsentToTermsUseCase.Execute(ctx, tid); err != nil {
		return false, err
	}
	return true, nil
}

// CurrentTerms is the resolver for the currentTerms field.
func (r *queryResolver) CurrentTerms(ctx context.Context) (*gqlmodel.TermsOfService, error) {
	t, err := r.GetCurrentTermsUseCase.Execute(ctx)
	if err != nil {
		return nil, err
	}
	if t == nil {
		return nil, nil
	}
	return toGraphTerms(t, r.StorageRepository.PublicURL(t.ObjectKey)), nil
}

// MyTermsConsentStatus is the resolver for the myTermsConsentStatus field.
func (r *queryResolver) MyTermsConsentStatus(ctx context.Context) (*gqlmodel.TermsConsentStatus, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	status, err := r.CheckConsentUseCase.Execute(ctx, claims.ID)
	if err != nil {
		return nil, err
	}

	result := &gqlmodel.TermsConsentStatus{
		IsConsented: status.IsConsented,
	}
	if status.CurrentTerms != nil {
		result.CurrentTerms = toGraphTerms(status.CurrentTerms, r.StorageRepository.PublicURL(status.CurrentTerms.ObjectKey))
	}
	return result, nil
}

// AdminListTerms is the resolver for the adminListTerms field.
func (r *queryResolver) AdminListTerms(ctx context.Context, limit *int32, offset *int32) ([]*gqlmodel.TermsOfService, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}
	list, err := r.ListTermsUseCase.Execute(ctx, resolveUnpagedWindow(limit, offset))
	if err != nil {
		return nil, err
	}
	var result []*gqlmodel.TermsOfService
	for _, t := range list {
		result = append(result, toGraphTerms(t, r.StorageRepository.PublicURL(t.ObjectKey)))
	}
	return result, nil
}

// AdminListConsents is the resolver for the adminListConsents field.
func (r *queryResolver) AdminListConsents(ctx context.Context, termsID string, limit *int32, offset *int32) (*gqlmodel.TermsConsentPage, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}
	tid, err := decodeGraphID(ctx, "terms", termsID)
	if err != nil {
		return nil, fmt.Errorf("invalid terms id")
	}
	consents, total, err := r.ListConsentsUseCase.Execute(ctx, tid, resolvePageQuery(ctx, limit, offset, defaultPageSize))
	if err != nil {
		return nil, err
	}

	userIDs := make([]int64, 0, len(consents))
	for _, c := range consents {
		userIDs = append(userIDs, c.UserID)
	}
	// 同意者台帳は管理者専用（このリゾルバの先頭で requireAdminAuth 済み）なので、
	// 連絡先込みで引く。TermsConsentRecord.user は UserAccount。
	users, err := r.GetUserAccountsByIDsUseCase.Execute(ctx, userIDs)
	if err != nil {
		return nil, err
	}
	userMap := make(map[int64]*model.UserAccount, len(users))
	for _, u := range users {
		userMap[u.ID] = u
	}

	items := make([]*gqlmodel.TermsConsentRecord, 0, len(consents))
	for _, c := range consents {
		u, ok := userMap[c.UserID]
		if !ok {
			continue
		}
		items = append(items, &gqlmodel.TermsConsentRecord{
			ID:          strconv.FormatInt(c.ID, 10),
			User:        toGraphUserAccount(u),
			ConsentedAt: c.ConsentedAt.Format(timeFormat),
		})
	}
	return &gqlmodel.TermsConsentPage{Items: items, Total: int32(total)}, nil
}
