package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"
	"fmt"
	"strconv"
	"time"

	gqlmodel "github.com/Cityboypenguin/SPACE-server/graph/model"
	"github.com/Cityboypenguin/SPACE-server/internal/logger"
	"github.com/Cityboypenguin/SPACE-server/model"
	messageusecase "github.com/Cityboypenguin/SPACE-server/usecase/message"
	notificationuc "github.com/Cityboypenguin/SPACE-server/usecase/notification"
	"github.com/Cityboypenguin/SPACE-server/usecase/profile"
	usersettingsusecase "github.com/Cityboypenguin/SPACE-server/usecase/user_settings"
)

// SendEmailOtp is the resolver for the sendEmailOTP field.
func (r *mutationResolver) SendEmailOtp(ctx context.Context, email string) (bool, error) {
	if err := r.SendEmailOTPUseCase.Execute(ctx, email); err != nil {
		return false, err
	}
	return true, nil
}

// VerifyEmailOtp is the resolver for the verifyEmailOTP field.
func (r *mutationResolver) VerifyEmailOtp(ctx context.Context, email string, otp string) (bool, error) {
	if err := r.VerifyEmailOTPUseCase.Execute(ctx, email, otp); err != nil {
		return false, err
	}
	return true, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input gqlmodel.CreateUserInput) (*gqlmodel.UserAccount, error) {
	param := model.CreateUserParam{
		AccountID: input.AccountID,
		Name:      input.Name,
		Email:     input.Email,
		Password:  input.Password,
	}

	user, err := r.CreateUserUseCase.Execute(ctx, param, input.Otp)
	if err != nil {
		return nil, err
	}

	return toGraphUserAccount(user), nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return false, err
	}

	numericID, err := decodeGraphID(ctx, "user", id)
	if err != nil {
		return false, fmt.Errorf("invalid user id")
	}

	deleted, err := r.DeleteUserUseCase.Execute(ctx, numericID)
	if err != nil {
		return false, err
	}

	return deleted, nil
}

// DeleteMyAccount is the resolver for the deleteMyAccount field.
func (r *mutationResolver) DeleteMyAccount(ctx context.Context) (bool, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}

	numericID := claims.ID

	return r.DeleteUserUseCase.Execute(ctx, numericID)
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input gqlmodel.UpdateUserInput) (*gqlmodel.UserAccount, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// ユーザーは自分の情報のみ更新可能
	numericID := claims.ID

	param := model.UpdateUserParam{
		AccountID: input.AccountID,
		Name:      input.Name,
		Email:     input.Email,
		Password:  input.Password,
	}

	user, err := r.UpdateUserUseCase.Execute(ctx, numericID, param, input.CurrentPassword, true)
	if err != nil {
		return nil, err
	}

	return toGraphUserAccount(user), nil
}

// LoginUser is the resolver for the loginUser field.
func (r *mutationResolver) LoginUser(ctx context.Context, input gqlmodel.LoginInput) (*gqlmodel.UserAuthPayload, error) {
	result, err := r.LoginUserUseCase.Execute(ctx, input.Email, input.Password)
	if err != nil {
		return nil, err
	}

	return &gqlmodel.UserAuthPayload{
		Token:        result.AccessToken,
		RefreshToken: result.RefreshToken,
		User:         toGraphUserAccount(result.User),
	}, nil
}

// RefreshUserToken is the resolver for the refreshUserToken field.
func (r *mutationResolver) RefreshUserToken(ctx context.Context, refreshToken string) (*gqlmodel.UserAuthPayload, error) {
	result, err := r.RefreshUserTokenUseCase.Execute(ctx, refreshToken)
	if err != nil {
		return nil, err
	}

	return &gqlmodel.UserAuthPayload{
		Token:        result.AccessToken,
		RefreshToken: result.RefreshToken,
		User:         toGraphUserAccount(result.User),
	}, nil
}

// LogoutUser is the resolver for the logoutUser field.
func (r *mutationResolver) LogoutUser(ctx context.Context, token string) (bool, error) {
	if err := r.LogoutUserUseCase.Execute(ctx, token); err != nil {
		return false, err
	}
	return true, nil
}

// RequestPasswordReset is the resolver for the requestPasswordReset field.
func (r *mutationResolver) RequestPasswordReset(ctx context.Context, email string) (bool, error) {
	if err := r.RequestPasswordResetUseCase.Execute(ctx, email); err != nil {
		return false, err
	}
	return true, nil
}

// VerifyPasswordResetOtp is the resolver for the verifyPasswordResetOTP field.
func (r *mutationResolver) VerifyPasswordResetOtp(ctx context.Context, email string, otp string) (string, error) {
	return r.VerifyPasswordResetOTPUseCase.Execute(ctx, email, otp)
}

// ResetPassword is the resolver for the resetPassword field.
func (r *mutationResolver) ResetPassword(ctx context.Context, resetToken string, newPassword string) (bool, error) {
	if err := r.ResetPasswordUseCase.Execute(ctx, resetToken, newPassword); err != nil {
		return false, err
	}
	return true, nil
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input gqlmodel.UpdateProfileInput) (*gqlmodel.Profile, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	numericUserID := claims.ID

	if _, err := requireSelfOrAdmin(ctx, numericUserID, "update_profile"); err != nil {
		return nil, err
	}

	param := model.UpdateProfileParam{
		Bio: input.Bio,
	}

	p, err := r.UpdateProfileUseCase.Execute(ctx, numericUserID, param)
	if err != nil {
		return nil, err
	}

	return r.graphProfile(ctx, p)
}

// UpdateMyProfile is the resolver for the updateMyProfile field.
func (r *mutationResolver) UpdateMyProfile(ctx context.Context, input gqlmodel.UpdateMyProfileInput) (*gqlmodel.Profile, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	numericUserID := claims.ID
	if _, err := requireSelfOrAdmin(ctx, numericUserID, "update_my_profile"); err != nil {
		return nil, err
	}

	param := profile.UpdateMyProfileParam{
		User: model.UpdateUserParam{
			AccountID: input.AccountID,
			Name:      input.Name,
		},
		Profile: model.UpdateProfileParam{
			Bio: input.Bio,
		},
	}

	updatedUser, updatedProfile, err := r.UpdateMyProfileUseCase.Execute(ctx, numericUserID, param)
	if err != nil {
		return nil, err
	}

	return toGraphProfile(updatedUser, updatedProfile, r.avatarURLFor(updatedProfile)), nil
}

// SetAvatar is the resolver for the setAvatar field.
func (r *mutationResolver) SetAvatar(ctx context.Context, objectKey string) (*gqlmodel.Profile, error) {
	_, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	p, err := r.SetAvatarUseCase.Execute(ctx, objectKey)
	if err != nil {
		return nil, err
	}

	return r.graphProfile(ctx, p)
}

// DeleteAvatar is the resolver for the deleteAvatar field.
func (r *mutationResolver) DeleteAvatar(ctx context.Context) (*gqlmodel.Profile, error) {
	_, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	p, err := r.DeleteAvatarUseCase.Execute(ctx)
	if err != nil {
		return nil, err
	}

	return r.graphProfile(ctx, p)
}

// CreateFavoriteUser is the resolver for the createFavoriteUser field.
func (r *mutationResolver) CreateFavoriteUser(ctx context.Context, favoriteUserID string) (*gqlmodel.FavoriteUser, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	numericTargetID, err := decodeGraphID(ctx, "user", favoriteUserID)
	if err != nil {
		return nil, fmt.Errorf("invalid favorite user id")
	}

	id, err := r.CreateFavoriteUserUseCase.Execute(ctx, numericTargetID)
	if err != nil {
		return nil, err
	}

	if err := r.NotificationPublisher.Publish(ctx, notificationuc.PublishParams{
		UserID:  numericTargetID,
		Type:    notificationuc.TypeFollow,
		ActorID: &claims.ID,
		Message: notificationuc.MessageFollowed,
	}); err != nil {
		logger.Log.Error().Err(err).Msg("failed to publish follow notification")
	}

	favoriteUserModel := &model.FavoriteUser{
		ID:             id,
		UserID:         claims.ID,
		FavoriteUserID: numericTargetID,
		CreatedAt:      time.Now(),
	}
	return toGraphFavoriteUser(favoriteUserModel), nil
}

// DeleteFavoriteUser is the resolver for the deleteFavoriteUser field.
func (r *mutationResolver) DeleteFavoriteUser(ctx context.Context, favoriteUserID string) (bool, error) {
	_, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	numericTargetID, err := decodeGraphID(ctx, "user", favoriteUserID)
	if err != nil {
		return false, fmt.Errorf("invalid favorite user id")
	}

	return r.DeleteFavoriteUserUseCase.Execute(ctx, numericTargetID)
}

// CreateBlocker is the resolver for the createBlocker field.
func (r *mutationResolver) CreateBlocker(ctx context.Context, blockedUserID string) (*gqlmodel.Blocker, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	numericTargetID, err := decodeGraphID(ctx, "user", blockedUserID)
	if err != nil {
		return nil, fmt.Errorf("invalid blocked user id")
	}

	id, err := r.CreateBlockUseCase.Execute(ctx, numericTargetID)
	if err != nil {
		return nil, err
	}

	blockerModel := &model.Blocker{
		ID:            id,
		UserID:        claims.ID,
		BlockedUserID: numericTargetID,
		CreatedAt:     time.Now(),
	}
	return toGraphBlocker(blockerModel), nil
}

// DeleteBlocker is the resolver for the deleteBlocker field.
func (r *mutationResolver) DeleteBlocker(ctx context.Context, blockedUserID string) (bool, error) {
	_, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	numericTargetID, err := decodeGraphID(ctx, "user", blockedUserID)
	if err != nil {
		return false, fmt.Errorf("invalid blocked user id")
	}

	return r.DeleteBlockUseCase.Execute(ctx, numericTargetID)
}

// SetThemePreference is the resolver for the setThemePreference field.
func (r *mutationResolver) SetThemePreference(ctx context.Context, theme gqlmodel.ThemePreference) (gqlmodel.ThemePreference, error) {
	if err := r.ManageUserSettingUsecase.Set(ctx, "theme", string(theme)); err != nil {
		return "", err
	}
	return theme, nil
}

// SetTimetableProfileVisibility is the resolver for the setTimetableProfileVisibility field.
func (r *mutationResolver) SetTimetableProfileVisibility(ctx context.Context, visible bool) (bool, error) {
	if err := r.ManageUserSettingUsecase.Set(ctx, usersettingsusecase.TimetableProfileVisibilityKey, strconv.FormatBool(visible)); err != nil {
		return false, err
	}
	return visible, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, limit *int32, offset *int32) (*gqlmodel.UserAccountPage, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}

	users, total, err := r.ListUsersUseCase.Execute(ctx, resolvePageQuery(ctx, limit, offset, defaultPageSize))
	if err != nil {
		return nil, err
	}

	items := make([]*gqlmodel.UserAccount, 0, len(users))
	for _, user := range users {
		items = append(items, toGraphUserAccount(user))
	}
	return &gqlmodel.UserAccountPage{Items: items, Total: int32(total)}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*gqlmodel.UserAccount, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// 本人ぶんなので連絡先込みで引く（me は UserAccount）。
	user, err := r.GetUserAccountByIDUseCase.Execute(ctx, claims.ID)
	if err != nil {
		return nil, err
	}

	return toGraphUserAccount(user), nil
}

// ThemePreference is the resolver for the themePreference field.
func (r *queryResolver) ThemePreference(ctx context.Context) (*gqlmodel.ThemePreference, error) {
	value, found, err := r.ManageUserSettingUsecase.Get(ctx, "theme")
	if err != nil {
		return nil, err
	}
	if !found {
		return nil, nil
	}
	t := gqlmodel.ThemePreference(value)
	return &t, nil
}

// TimetableProfileVisibility is the resolver for the timetableProfileVisibility field.
func (r *queryResolver) TimetableProfileVisibility(ctx context.Context) (bool, error) {
	value, found, err := r.ManageUserSettingUsecase.Get(ctx, usersettingsusecase.TimetableProfileVisibilityKey)
	if err != nil {
		return false, err
	}
	if !found {
		return true, nil
	}
	return strconv.ParseBool(value)
}

// GetUserByID is the resolver for the getUserByID field.
func (r *queryResolver) GetUserByID(ctx context.Context, id string) (*gqlmodel.UserAccount, error) {
	if _, err := requireAdminAuth(ctx); err != nil {
		return nil, err
	}

	numericID, err := decodeGraphID(ctx, "user", id)
	if err != nil {
		return nil, fmt.Errorf("invalid user id")
	}

	// 管理者専用の口なので連絡先込みで引く（getUserByID は UserAccount）。
	user, err := r.GetUserAccountByIDUseCase.Execute(ctx, numericID)
	if err != nil {
		return nil, err
	}

	return toGraphUserAccount(user), nil
}

// SearchUsers is the resolver for the searchUsers field.
func (r *queryResolver) SearchUsers(ctx context.Context, keyword string, limit *int32, offset *int32) (*gqlmodel.UserPage, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	users, total, err := r.SearchUsersUseCase.Execute(ctx, keyword, resolvePageQuery(ctx, limit, offset, defaultPageSize))
	if err != nil {
		return nil, err
	}
	items := make([]*gqlmodel.User, 0, len(users))
	for _, user := range users {
		items = append(items, toGraphUser(user))
	}
	return &gqlmodel.UserPage{Items: items, Total: int32(total)}, nil
}

// SuggestUsers is the resolver for the suggestUsers field.
func (r *queryResolver) SuggestUsers(ctx context.Context, prefix string, limit *int32) ([]*gqlmodel.User, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// 既定値・上限はユースケース側（defaultSuggestUsersLimit / maxSuggestUsersLimit）が
	// 持つ。0 以下はそこで既定値に丸められるので、ここでは素通しでよい。
	l := 0
	if limit != nil {
		l = int(*limit)
	}

	users, err := r.SuggestUsersUseCase.Execute(ctx, prefix, l)
	if err != nil {
		return nil, err
	}

	items := make([]*gqlmodel.User, 0, len(users))
	for _, u := range users {
		// 自分自身はメンションできないので候補から外す。
		if u.ID == claims.ID {
			continue
		}
		items = append(items, toGraphUser(u))
	}
	return items, nil
}

// MentionCandidates is the resolver for the mentionCandidates field.
func (r *queryResolver) MentionCandidates(ctx context.Context, roomID string, prefix string, limit *int32) ([]*gqlmodel.User, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	rid, err := decodeGraphID(ctx, "room", roomID)
	if err != nil {
		return nil, fmt.Errorf("invalid room id")
	}

	room, err := r.GetRoomUseCase.Execute(ctx, rid)
	if err != nil {
		return nil, fmt.Errorf("failed to get room")
	}
	// メンションが成立しないルームでは候補を持たせる意味がないので空を返す。
	// 判定は送信時の検証と同じ messageusecase.MentionsSupported を使う。
	if !messageusecase.MentionsSupported(room) {
		return []*gqlmodel.User{}, nil
	}

	// これは閲覧判定ではなく「メンション候補を引けるのはメンバーだけ」という別規則。
	// EnsureReadAccess は非メンバーの管理者にも閲覧を許すので、そこには寄せない。
	role, err := r.GetRoomUserRoleUseCase.Execute(ctx, rid)
	if err != nil {
		return nil, fmt.Errorf("failed to verify room membership")
	}
	if role == "" {
		return nil, errors.New("forbidden: not a member of this room")
	}

	users, err := r.SearchRoomUsersUseCase.Execute(ctx, rid, prefix, resolveLimit(limit, 8, 50))
	if err != nil {
		return nil, fmt.Errorf("failed to search room members")
	}

	// 除外条件は送信時の検証 (message.ResolveMentionsUseCase) と揃える。
	// ここで出した候補がそのまま通るようにするのが、この API を分けている理由。
	blockedSet, err := r.GetBlockRelatedUserIDsUseCase.Execute(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to load block relations")
	}

	candidates := make([]*gqlmodel.User, 0, len(users))
	for _, u := range users {
		if u.ID == claims.ID || u.Status != model.UserStatusActive || blockedSet[u.ID] {
			continue
		}
		candidates = append(candidates, toGraphUser(u))
	}
	return candidates, nil
}

// MyProfile is the resolver for the myProfile field.
func (r *queryResolver) MyProfile(ctx context.Context) (*gqlmodel.Profile, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	u, err := r.GetUserByIDUseCase.Execute(ctx, claims.ID)
	if err != nil || u == nil {
		return nil, fmt.Errorf("user not found")
	}

	return r.buildProfile(ctx, u)
}

// GetProfileByUserID is the resolver for the getProfileByUserID field.
func (r *queryResolver) GetProfileByUserID(ctx context.Context, userID string) (*gqlmodel.Profile, error) {
	if _, userErr := requireAuth(ctx); userErr != nil {
		if _, adminErr := requireAdminAuth(ctx); adminErr != nil {
			return nil, userErr
		}
	}

	numericUserID, err := decodeGraphID(ctx, "user", userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id")
	}

	u, err := r.GetUserByIDUseCase.Execute(ctx, numericUserID)
	if err != nil || u == nil {
		return nil, fmt.Errorf("user not found")
	}

	return r.buildProfile(ctx, u)
}

// ListFavoriteUsers is the resolver for the listFavoriteUsers field.
func (r *queryResolver) ListFavoriteUsers(ctx context.Context, limit *int32, offset *int32) (*gqlmodel.UserPage, error) {
	_, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	favoriteUsers, total, err := r.ListFavoriteUsersUseCase.Execute(ctx, resolvePageQuery(ctx, limit, offset, defaultPageSize))
	if err != nil {
		return nil, err
	}
	items, err := r.favoriteUsersToGQL(ctx, favoriteUsers)
	if err != nil {
		return nil, err
	}
	return &gqlmodel.UserPage{Items: items, Total: int32(total)}, nil
}

// MyFollowers is the resolver for the myFollowers field.
func (r *queryResolver) MyFollowers(ctx context.Context, limit *int32, offset *int32) (*gqlmodel.UserPage, error) {
	_, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	followers, total, err := r.ListFollowersUseCase.Execute(ctx, resolvePageQuery(ctx, limit, offset, defaultPageSize))
	if err != nil {
		return nil, err
	}
	items, err := r.followersToGQL(ctx, followers)
	if err != nil {
		return nil, err
	}
	return &gqlmodel.UserPage{Items: items, Total: int32(total)}, nil
}

// SearchFavoriteUsers is the resolver for the searchFavoriteUsers field.
func (r *queryResolver) SearchFavoriteUsers(ctx context.Context, keyword string, limit *int32, offset *int32) ([]*gqlmodel.User, error) {
	_, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	favoriteUsers, err := r.SearchFavoriteUsersUseCase.Execute(ctx, keyword, resolveUnpagedWindow(limit, offset))
	if err != nil {
		return nil, err
	}
	return r.favoriteUsersToGQL(ctx, favoriteUsers)
}

// GetFavoriteUsersByUserID is the resolver for the GetFavoriteUsersByUserID field.
func (r *queryResolver) GetFavoriteUsersByUserID(ctx context.Context, userID string, limit *int32, offset *int32) ([]*gqlmodel.User, error) {
	if _, err := requireAuth(ctx); err != nil {
		if _, err := requireAdminAuth(ctx); err != nil {
			return nil, err
		}
	}

	numericUserID, err := decodeGraphID(ctx, "user", userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id")
	}
	favoriteUsers, err := r.GetFavoriteUserByUserIDUseCase.Execute(ctx, numericUserID, resolveUnpagedWindow(limit, offset))
	if err != nil {
		return nil, err
	}
	return r.favoriteUsersToGQL(ctx, favoriteUsers)
}

// ListBlockedUsers is the resolver for the listBlockedUsers field.
func (r *queryResolver) ListBlockedUsers(ctx context.Context, limit *int32, offset *int32) (*gqlmodel.UserPage, error) {
	_, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	blockedUsers, total, err := r.ListBlockersUseCase.Execute(ctx, resolvePageQuery(ctx, limit, offset, defaultPageSize))
	if err != nil {
		return nil, err
	}
	items, err := r.blockedUsersToGQL(ctx, blockedUsers)
	if err != nil {
		return nil, err
	}
	return &gqlmodel.UserPage{Items: items, Total: int32(total)}, nil
}

// SearchBlockedUsers is the resolver for the searchBlockedUsers field.
func (r *queryResolver) SearchBlockedUsers(ctx context.Context, keyword string, limit *int32, offset *int32) ([]*gqlmodel.User, error) {
	_, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	blockedUsers, err := r.SearchBlockersUseCase.Execute(ctx, keyword, resolveUnpagedWindow(limit, offset))
	if err != nil {
		return nil, err
	}
	return r.blockedUsersToGQL(ctx, blockedUsers)
}

// GetBlockersByUserID is the resolver for the GetBlockersByUserID field.
func (r *queryResolver) GetBlockersByUserID(ctx context.Context, userID string, limit *int32, offset *int32) ([]*gqlmodel.User, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	numericUserID, err := decodeGraphID(ctx, "user", userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id")
	}
	if claims.ID != numericUserID && !isAdminRole(claims.Role) {
		return nil, errors.New("forbidden: cannot view other users' block list")
	}
	blockedUsers, err := r.GetBlockersByUserIDUseCase.Execute(ctx, numericUserID, resolveUnpagedWindow(limit, offset))
	if err != nil {
		return nil, err
	}
	return r.blockedUsersToGQL(ctx, blockedUsers)
}

// AvatarURL is the resolver for the avatarUrl field.
func (r *userResolver) AvatarURL(ctx context.Context, obj *gqlmodel.User) (*string, error) {
	if obj.AccountID == "deleted-account" {
		return nil, nil
	}
	numericID, err := decodeGraphID(ctx, "user", obj.ID)
	if err != nil {
		return nil, nil
	}
	p, err := r.GetProfileUseCase.Execute(ctx, numericID)
	if err != nil || p == nil {
		return nil, nil
	}
	return r.avatarURLFor(p), nil
}

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
