// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AddUserToRoomInput struct {
	RoomID string `json:"roomID"`
	UserID string `json:"userID"`
}

type Administrator struct {
	ID        string `json:"ID"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type AdministratorAuthPayload struct {
	Token         string         `json:"token"`
	RefreshToken  string         `json:"refreshToken"`
	Administrator *Administrator `json:"administrator"`
}

type Blocker struct {
	ID            string `json:"ID"`
	UserID        string `json:"userID"`
	BlockedUserID string `json:"blockedUserID"`
	CreatedAt     string `json:"createdAt"`
}

type Community struct {
	ID          string `json:"ID"`
	RoomID      string `json:"roomID"`
	Name        string `json:"name"`
	Description string `json:"description"`
	AvatarURL   string `json:"avatarURL"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type CommunityMember struct {
	User *User  `json:"user"`
	Role string `json:"role"`
}

type CreateAdministratorInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type CreateCommunityInput struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	AvatarKey   *string `json:"avatarKey,omitempty"`
}

type CreateFavoriteInput struct {
	PostID string `json:"post_id"`
}

type CreateInquiryInput struct {
	Name    string `json:"name"`
	Email   string `json:"email"`
	Subject string `json:"subject"`
	Content string `json:"content"`
}

type CreatePostInput struct {
	Content     string              `json:"content"`
	ParentID    *string             `json:"parent_id,omitempty"`
	MediaInputs []*MediaUploadInput `json:"mediaInputs,omitempty"`
}

type CreateReportInput struct {
	TargetType   ReportTargetType `json:"targetType"`
	TargetID     string           `json:"targetID"`
	Reason       string           `json:"reason"`
	CustomReason *string          `json:"customReason,omitempty"`
}

type CreateRoomInput struct {
	Name string `json:"name"`
}

type CreateUserInput struct {
	AccountID string `json:"accountID"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}

type DeleteFavoriteInput struct {
	PostID string `json:"post_id"`
}

type Favorite struct {
	ID        string `json:"ID"`
	User      *User  `json:"user"`
	Post      *Post  `json:"post"`
	CreatedAt string `json:"createdAt"`
}

type FavoriteUser struct {
	ID             string `json:"ID"`
	UserID         string `json:"userID"`
	FavoriteUserID string `json:"favoriteUserID"`
	CreatedAt      string `json:"createdAt"`
}

type Inquiry struct {
	ID        string `json:"ID"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	Subject   string `json:"subject"`
	Content   string `json:"content"`
	CreatedAt string `json:"createdAt"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Media struct {
	ID          string `json:"ID"`
	URL         string `json:"url"`
	ContentType string `json:"contentType"`
	CreatedAt   string `json:"createdAt"`
}

type MediaUploadInput struct {
	ObjectKey   string `json:"objectKey"`
	ContentType string `json:"contentType"`
}

type Message struct {
	ID        string   `json:"ID"`
	RoomID    string   `json:"roomID"`
	Room      *Room    `json:"room"`
	UserID    string   `json:"userID"`
	User      *User    `json:"user"`
	Content   string   `json:"content"`
	Media     []*Media `json:"media"`
	CreatedAt string   `json:"createdAt"`
	UpdatedAt string   `json:"updatedAt"`
}

type Mutation struct {
}

type Notification struct {
	ID         string  `json:"ID"`
	Type       string  `json:"type"`
	Actor      *User   `json:"actor,omitempty"`
	TargetType *string `json:"targetType,omitempty"`
	TargetID   *string `json:"targetID,omitempty"`
	Message    string  `json:"message"`
	IsRead     bool    `json:"isRead"`
	CreatedAt  string  `json:"createdAt"`
}

type Post struct {
	ID         string      `json:"ID"`
	Content    string      `json:"content"`
	CreatedAt  string      `json:"createdAt"`
	UpdatedAt  string      `json:"updatedAt"`
	DeletedAt  *string     `json:"deletedAt,omitempty"`
	ReplyCount int32       `json:"replyCount"`
	User       *User       `json:"user"`
	Favorites  []*Favorite `json:"favorites"`
	Parent     *Post       `json:"parent,omitempty"`
	Replies    []*Post     `json:"replies"`
	Media      []*Media    `json:"media"`
}

type PresignedUploadURL struct {
	UploadURL string `json:"uploadUrl"`
	ObjectKey string `json:"objectKey"`
}

type Profile struct {
	User      *User   `json:"user"`
	Username  string  `json:"username"`
	Bio       *string `json:"bio,omitempty"`
	AvatarURL *string `json:"avatarUrl,omitempty"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
}

type Query struct {
}

type RemoveUserFromRoomInput struct {
	RoomID string `json:"roomID"`
	UserID string `json:"userID"`
}

type ReportSearchFilter struct {
	Status     *ReportStatus     `json:"status,omitempty"`
	TargetType *ReportTargetType `json:"targetType,omitempty"`
	ReporterID *string           `json:"reporterID,omitempty"`
}

type Room struct {
	ID                  string  `json:"ID"`
	Content             *string `json:"content,omitempty"`
	Name                string  `json:"name"`
	Type                string  `json:"type"`
	User                []*User `json:"user"`
	CreatedAt           string  `json:"createdAt"`
	UpdatedAt           string  `json:"updatedAt"`
	IsMessagingDisabled bool    `json:"isMessagingDisabled"`
}

type Subscription struct {
}

type UpdateAdministratorInput struct {
	Name     *string `json:"name,omitempty"`
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
}

type UpdateCommunityInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	AvatarKey   *string `json:"avatarKey,omitempty"`
}

type UpdatePostInput struct {
	ID      string `json:"id"`
	Content string `json:"content"`
}

type UpdateProfileInput struct {
	Username *string `json:"username,omitempty"`
	Bio      *string `json:"bio,omitempty"`
}

type UpdateRoomInput struct {
	Name *string `json:"name,omitempty"`
}

type UpdateUserInput struct {
	AccountID *string `json:"accountID,omitempty"`
	Name      *string `json:"name,omitempty"`
	Email     *string `json:"email,omitempty"`
	Password  *string `json:"password,omitempty"`
}

type User struct {
	ID        string      `json:"ID"`
	AccountID string      `json:"accountID"`
	Name      string      `json:"name"`
	Email     string      `json:"email"`
	Role      string      `json:"role"`
	Status    string      `json:"status"`
	AvatarURL *string     `json:"avatarUrl,omitempty"`
	CreatedAt string      `json:"createdAt"`
	UpdatedAt string      `json:"updatedAt"`
	Posts     []*Post     `json:"posts"`
	Favorites []*Favorite `json:"favorites"`
}

type UserAuthPayload struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
	User         *User  `json:"user"`
}

type UserReport struct {
	ID           string           `json:"ID"`
	Reporter     *User            `json:"reporter"`
	TargetType   ReportTargetType `json:"targetType"`
	TargetID     string           `json:"targetID"`
	Reason       string           `json:"reason"`
	CustomReason *string          `json:"customReason,omitempty"`
	Status       ReportStatus     `json:"status"`
	CreatedAt    string           `json:"createdAt"`
	UpdatedAt    string           `json:"updatedAt"`
}

type ReportStatus string

const (
	ReportStatusPending   ReportStatus = "PENDING"
	ReportStatusReviewing ReportStatus = "REVIEWING"
	ReportStatusResolved  ReportStatus = "RESOLVED"
	ReportStatusDismissed ReportStatus = "DISMISSED"
)

var AllReportStatus = []ReportStatus{
	ReportStatusPending,
	ReportStatusReviewing,
	ReportStatusResolved,
	ReportStatusDismissed,
}

func (e ReportStatus) IsValid() bool {
	switch e {
	case ReportStatusPending, ReportStatusReviewing, ReportStatusResolved, ReportStatusDismissed:
		return true
	}
	return false
}

func (e ReportStatus) String() string {
	return string(e)
}

func (e *ReportStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReportStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReportStatus", str)
	}
	return nil
}

func (e ReportStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReportStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReportStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ReportTargetType string

const (
	ReportTargetTypePost      ReportTargetType = "POST"
	ReportTargetTypeComment   ReportTargetType = "COMMENT"
	ReportTargetTypePromotion ReportTargetType = "PROMOTION"
	ReportTargetTypeCommunity ReportTargetType = "COMMUNITY"
)

var AllReportTargetType = []ReportTargetType{
	ReportTargetTypePost,
	ReportTargetTypeComment,
	ReportTargetTypePromotion,
	ReportTargetTypeCommunity,
}

func (e ReportTargetType) IsValid() bool {
	switch e {
	case ReportTargetTypePost, ReportTargetTypeComment, ReportTargetTypePromotion, ReportTargetTypeCommunity:
		return true
	}
	return false
}

func (e ReportTargetType) String() string {
	return string(e)
}

func (e *ReportTargetType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReportTargetType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReportTargetType", str)
	}
	return nil
}

func (e ReportTargetType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReportTargetType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReportTargetType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
