// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AddUserToRoomInput struct {
	RoomID string `json:"roomID"`
	UserID string `json:"userID"`
}

type Administrator struct {
	ID        string `json:"ID"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type AdministratorAuthPayload struct {
	Token         string         `json:"token"`
	RefreshToken  string         `json:"refreshToken"`
	Administrator *Administrator `json:"administrator"`
}

type AdministratorPage struct {
	Items []*Administrator `json:"items"`
	Total int32            `json:"total"`
}

type AnalyticsSummary struct {
	TotalUsers                  int32           `json:"totalUsers"`
	NewUsersToday               int32           `json:"newUsersToday"`
	NewUsersThisWeek            int32           `json:"newUsersThisWeek"`
	NewUsersThisMonth           int32           `json:"newUsersThisMonth"`
	FrozenUsersCount            int32           `json:"frozenUsersCount"`
	TotalPosts                  int32           `json:"totalPosts"`
	TotalComments               int32           `json:"totalComments"`
	TotalDeletedPosts           int32           `json:"totalDeletedPosts"`
	TotalLikes                  int32           `json:"totalLikes"`
	TotalCommunities            int32           `json:"totalCommunities"`
	TotalMessages               int32           `json:"totalMessages"`
	TotalReports                int32           `json:"totalReports"`
	TotalBlocks                 int32           `json:"totalBlocks"`
	TotalInquiries              int32           `json:"totalInquiries"`
	CurrentActiveUsers          int32           `json:"currentActiveUsers"`
	Dau                         int32           `json:"dau"`
	Wau                         int32           `json:"wau"`
	Mau                         int32           `json:"mau"`
	DauMauRatio                 float64         `json:"dauMauRatio"`
	PostsToday                  int32           `json:"postsToday"`
	CommentsToday               int32           `json:"commentsToday"`
	MessagesToday               int32           `json:"messagesToday"`
	AvgLikesPerPost             float64         `json:"avgLikesPerPost"`
	AvgCommentsPerPost          float64         `json:"avgCommentsPerPost"`
	PostsTextOnly               int32           `json:"postsTextOnly"`
	PostsWithImage              int32           `json:"postsWithImage"`
	PostsWithVideo              int32           `json:"postsWithVideo"`
	UniqueDMSenders             int32           `json:"uniqueDMSenders"`
	ActiveCommunitiesLast30Days int32           `json:"activeCommunitiesLast30Days"`
	AvgCommunityMembers         float64         `json:"avgCommunityMembers"`
	AvgCommunitiesPerUser       float64         `json:"avgCommunitiesPerUser"`
	TotalFollows                int32           `json:"totalFollows"`
	AvgFollowersPerUser         float64         `json:"avgFollowersPerUser"`
	AvgFollowingPerUser         float64         `json:"avgFollowingPerUser"`
	UsersWithProfile            int32           `json:"usersWithProfile"`
	UsersWithAvatar             int32           `json:"usersWithAvatar"`
	UsersWithPost               int32           `json:"usersWithPost"`
	OnboardingCompleteRate      float64         `json:"onboardingCompleteRate"`
	AvgTimeToFirstPostMinutes   float64         `json:"avgTimeToFirstPostMinutes"`
	TotalNotifications          int32           `json:"totalNotifications"`
	ReadNotifications           int32           `json:"readNotifications"`
	NotificationReadRate        float64         `json:"notificationReadRate"`
	PendingReports              int32           `json:"pendingReports"`
	ResolvedReports             int32           `json:"resolvedReports"`
	WebSocketConnections        int32           `json:"webSocketConnections"`
	SseConnections              int32           `json:"sseConnections"`
	ErrorRate5xx                float64         `json:"errorRate5xx"`
	P50ResponseTimeMs           float64         `json:"p50ResponseTimeMs"`
	P95ResponseTimeMs           float64         `json:"p95ResponseTimeMs"`
	P99ResponseTimeMs           float64         `json:"p99ResponseTimeMs"`
	AvgSessionDurationSeconds   float64         `json:"avgSessionDurationSeconds"`
	AvgSessionsPerDay           float64         `json:"avgSessionsPerDay"`
	AvgScrollDepth              float64         `json:"avgScrollDepth"`
	PageViewStats               []*PageViewStat `json:"pageViewStats"`
}

type Announcement struct {
	ID        string `json:"ID"`
	Title     string `json:"title"`
	Body      string `json:"body"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type AnnouncementPage struct {
	Items []*Announcement `json:"items"`
	Total int32           `json:"total"`
}

type Answer struct {
	ID         string `json:"ID"`
	QuestionID string `json:"questionID"`
	User       *User  `json:"user"`
	Body       string `json:"body"`
	CreatedAt  string `json:"createdAt"`
	UpdatedAt  string `json:"updatedAt"`
	IsMine     bool   `json:"isMine"`
	LikeCount  int32  `json:"likeCount"`
	LikedByMe  bool   `json:"likedByMe"`
}

type Blocker struct {
	ID            string `json:"ID"`
	UserID        string `json:"userID"`
	BlockedUserID string `json:"blockedUserID"`
	CreatedAt     string `json:"createdAt"`
}

type Community struct {
	ID          string  `json:"ID"`
	RoomID      string  `json:"roomID"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	AvatarURL   string  `json:"avatarURL"`
	MemberCount int32   `json:"memberCount"`
	IsMember    bool    `json:"isMember"`
	UnreadCount int32   `json:"unreadCount"`
	LastMessage *string `json:"lastMessage,omitempty"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
}

type CommunityMember struct {
	User *User  `json:"user"`
	Role string `json:"role"`
}

type CommunityMemberUpdateInput struct {
	UserID string                `json:"userID"`
	Action CommunityMemberAction `json:"action"`
}

type CommunityPage struct {
	Items []*Community `json:"items"`
	Total int32        `json:"total"`
}

type CommunityStatItem struct {
	CommunityID  string `json:"communityID"`
	Name         string `json:"name"`
	MemberCount  int32  `json:"memberCount"`
	MessageCount int32  `json:"messageCount"`
}

type CommunityStatsPage struct {
	Items []*CommunityStatItem `json:"items"`
	Total int32                `json:"total"`
}

type Course struct {
	ID          string `json:"ID"`
	RoomID      string `json:"roomID"`
	DayOfWeek   string `json:"dayOfWeek"`
	Period      int32  `json:"period"`
	TeacherName string `json:"teacherName"`
	CourseName  string `json:"courseName"`
	Year        int32  `json:"year"`
	Semester    string `json:"semester"`
	CreatedAt   string `json:"createdAt"`
}

type CourseImportStatus struct {
	State        CourseImportState `json:"state"`
	Year         *int32            `json:"year,omitempty"`
	Imported     *int32            `json:"imported,omitempty"`
	Skipped      *int32            `json:"skipped,omitempty"`
	ErrorMessage *string           `json:"errorMessage,omitempty"`
	StartedAt    *string           `json:"startedAt,omitempty"`
	FinishedAt   *string           `json:"finishedAt,omitempty"`
}

type CoursePage struct {
	Items []*Course `json:"items"`
	Total int32     `json:"total"`
}

type CreateAdministratorInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type CreateAnnouncementInput struct {
	Title string `json:"title"`
	Body  string `json:"body"`
}

type CreateCommunityInput struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	AvatarKey   *string `json:"avatarKey,omitempty"`
}

type CreateFavoriteInput struct {
	PostID string `json:"post_id"`
}

type CreateInquiryInput struct {
	Name     string          `json:"name"`
	Email    string          `json:"email"`
	Category InquiryCategory `json:"category"`
	Subject  string          `json:"subject"`
	Content  string          `json:"content"`
}

type CreatePostInput struct {
	Content     string              `json:"content"`
	ParentID    *string             `json:"parent_id,omitempty"`
	MediaInputs []*MediaUploadInput `json:"mediaInputs,omitempty"`
}

type CreateReportInput struct {
	TargetType   ReportTargetType `json:"targetType"`
	TargetID     string           `json:"targetID"`
	Reason       string           `json:"reason"`
	CustomReason *string          `json:"customReason,omitempty"`
}

type CreateRoomInput struct {
	Name string `json:"name"`
}

type CreateTermsOfServiceInput struct {
	Version       string `json:"version"`
	ObjectKey     string `json:"objectKey"`
	EffectiveDate string `json:"effectiveDate"`
}

type CreateUserInput struct {
	AccountID string `json:"accountID"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	Password  string `json:"password"`
	Otp       string `json:"otp"`
}

type CurrentSemester struct {
	Year     int32  `json:"year"`
	Semester string `json:"semester"`
}

type DeleteFavoriteInput struct {
	PostID string `json:"post_id"`
}

type Favorite struct {
	ID        string `json:"ID"`
	User      *User  `json:"user"`
	Post      *Post  `json:"post"`
	CreatedAt string `json:"createdAt"`
}

type FavoriteUser struct {
	ID             string `json:"ID"`
	UserID         string `json:"userID"`
	FavoriteUserID string `json:"favoriteUserID"`
	CreatedAt      string `json:"createdAt"`
}

type HashtagSuggestion struct {
	Tag   string `json:"tag"`
	Count int32  `json:"count"`
}

type HashtagSuggestionPage struct {
	Items []*HashtagSuggestion `json:"items"`
	Total int32                `json:"total"`
}

type Inquiry struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Email     string          `json:"email"`
	Category  InquiryCategory `json:"category"`
	Subject   string          `json:"subject"`
	Content   string          `json:"content"`
	Status    InquiryStatus   `json:"status"`
	CreatedAt string          `json:"createdAt"`
	UpdatedAt string          `json:"updatedAt"`
}

type InquiryPage struct {
	Items []*Inquiry `json:"items"`
	Total int32      `json:"total"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Media struct {
	ID          string `json:"ID"`
	URL         string `json:"url"`
	ContentType string `json:"contentType"`
	CreatedAt   string `json:"createdAt"`
}

type MediaUploadInput struct {
	ObjectKey   string `json:"objectKey"`
	ContentType string `json:"contentType"`
}

type Message struct {
	ID        string   `json:"ID"`
	RoomID    string   `json:"roomID"`
	Room      *Room    `json:"room"`
	UserID    string   `json:"userID"`
	User      *User    `json:"user"`
	Content   string   `json:"content"`
	Media     []*Media `json:"media"`
	CreatedAt string   `json:"createdAt"`
	UpdatedAt string   `json:"updatedAt"`
	IsMine    bool     `json:"isMine"`
}

type MessagePage struct {
	Items         []*Message `json:"items"`
	HasMoreBefore bool       `json:"hasMoreBefore"`
	HasMoreAfter  bool       `json:"hasMoreAfter"`
}

type Mutation struct {
}

type Notification struct {
	ID         string  `json:"ID"`
	Type       string  `json:"type"`
	Actor      *User   `json:"actor,omitempty"`
	TargetType *string `json:"targetType,omitempty"`
	TargetID   *string `json:"targetID,omitempty"`
	TargetPost *Post   `json:"targetPost,omitempty"`
	Message    string  `json:"message"`
	IsRead     bool    `json:"isRead"`
	CreatedAt  string  `json:"createdAt"`
}

type NotificationGroup struct {
	Key         string  `json:"key"`
	Type        string  `json:"type"`
	Actor       *User   `json:"actor,omitempty"`
	TargetType  *string `json:"targetType,omitempty"`
	TargetID    *string `json:"targetID,omitempty"`
	TargetPost  *Post   `json:"targetPost,omitempty"`
	Message     string  `json:"message"`
	CreatedAt   string  `json:"createdAt"`
	Count       int32   `json:"count"`
	UnreadCount int32   `json:"unreadCount"`
	LatestID    string  `json:"latestID"`
}

type NotificationGroupPage struct {
	Items []*NotificationGroup `json:"items"`
	Total int32                `json:"total"`
}

type NotificationPage struct {
	Items []*Notification `json:"items"`
	Total int32           `json:"total"`
}

type PageViewInput struct {
	Path            string `json:"path"`
	DurationSeconds int32  `json:"durationSeconds"`
	MaxScrollDepth  int32  `json:"maxScrollDepth"`
}

type PageViewStat struct {
	PagePath           string  `json:"pagePath"`
	AvgDurationSeconds float64 `json:"avgDurationSeconds"`
	AvgMaxScrollDepth  float64 `json:"avgMaxScrollDepth"`
	TotalViews         int32   `json:"totalViews"`
}

type Poll struct {
	ID                  string        `json:"ID"`
	RoomID              string        `json:"roomID"`
	User                *User         `json:"user"`
	Question            string        `json:"question"`
	AllowMultipleChoice bool          `json:"allowMultipleChoice"`
	Options             []*PollOption `json:"options"`
	Deadline            *string       `json:"deadline,omitempty"`
	CreatedAt           string        `json:"createdAt"`
	IsMine              bool          `json:"isMine"`
}

type PollOption struct {
	ID        string `json:"ID"`
	Label     string `json:"label"`
	VoteCount int32  `json:"voteCount"`
	VotedByMe bool   `json:"votedByMe"`
}

type PollPage struct {
	Items []*Poll `json:"items"`
	Total int32   `json:"total"`
}

type Post struct {
	ID         string      `json:"ID"`
	Content    string      `json:"content"`
	CreatedAt  string      `json:"createdAt"`
	UpdatedAt  string      `json:"updatedAt"`
	DeletedAt  *string     `json:"deletedAt,omitempty"`
	ReplyCount int32       `json:"replyCount"`
	User       *User       `json:"user"`
	RootPost   *Post       `json:"rootPost,omitempty"`
	Favorites  []*Favorite `json:"favorites"`
	Parent     *Post       `json:"parent,omitempty"`
	Replies    []*Post     `json:"replies"`
	Media      []*Media    `json:"media"`
}

type PostPage struct {
	Items []*Post `json:"items"`
	Total int32   `json:"total"`
}

type PresignedUploadURL struct {
	UploadURL string `json:"uploadUrl"`
	ObjectKey string `json:"objectKey"`
}

type Profile struct {
	User      *User   `json:"user"`
	Username  string  `json:"username"`
	Bio       *string `json:"bio,omitempty"`
	AvatarURL *string `json:"avatarUrl,omitempty"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
}

type Query struct {
}

type Question struct {
	ID         string    `json:"ID"`
	RoomID     string    `json:"roomID"`
	User       *User     `json:"user"`
	Body       string    `json:"body"`
	IsAnswered bool      `json:"isAnswered"`
	BestAnswer *Answer   `json:"bestAnswer,omitempty"`
	Answers    []*Answer `json:"answers"`
	CreatedAt  string    `json:"createdAt"`
	UpdatedAt  string    `json:"updatedAt"`
	IsMine     bool      `json:"isMine"`
}

type QuestionPage struct {
	Items []*Question `json:"items"`
	Total int32       `json:"total"`
}

type RecordSessionDataInput struct {
	SessionDurationSeconds int32            `json:"sessionDurationSeconds"`
	PageViews              []*PageViewInput `json:"pageViews"`
}

type RemoveUserFromRoomInput struct {
	RoomID string `json:"roomID"`
	UserID string `json:"userID"`
}

type ReportPage struct {
	Items []*UserReport `json:"items"`
	Total int32         `json:"total"`
}

type ReportSearchFilter struct {
	Status     *ReportStatus     `json:"status,omitempty"`
	TargetType *ReportTargetType `json:"targetType,omitempty"`
	ReporterID *string           `json:"reporterID,omitempty"`
}

type Room struct {
	ID                  string  `json:"ID"`
	Content             *string `json:"content,omitempty"`
	Name                string  `json:"name"`
	Type                string  `json:"type"`
	User                []*User `json:"user"`
	CreatedAt           string  `json:"createdAt"`
	UpdatedAt           string  `json:"updatedAt"`
	IsMessagingDisabled bool    `json:"isMessagingDisabled"`
	LastReadAt          *string `json:"lastReadAt,omitempty"`
	UnreadCount         int32   `json:"unreadCount"`
	PartnerLastReadAt   *string `json:"partnerLastReadAt,omitempty"`
}

type RoomPage struct {
	Items []*Room `json:"items"`
	Total int32   `json:"total"`
}

type RoomReadStatusUpdate struct {
	UserID     string `json:"userID"`
	LastReadAt string `json:"lastReadAt"`
}

type Subscription struct {
}

type TermsConsentPage struct {
	Items []*TermsConsentRecord `json:"items"`
	Total int32                 `json:"total"`
}

type TermsConsentRecord struct {
	ID          string `json:"ID"`
	User        *User  `json:"user"`
	ConsentedAt string `json:"consentedAt"`
}

type TermsConsentStatus struct {
	IsConsented  bool            `json:"isConsented"`
	CurrentTerms *TermsOfService `json:"currentTerms,omitempty"`
}

type TermsOfService struct {
	ID            string `json:"ID"`
	Version       string `json:"version"`
	DocumentURL   string `json:"documentUrl"`
	EffectiveDate string `json:"effectiveDate"`
	CreatedAt     string `json:"createdAt"`
}

type TimeSeriesData struct {
	Points []*TimeSeriesPoint `json:"points"`
}

type TimeSeriesPoint struct {
	Label       string `json:"label"`
	Posts       int32  `json:"posts"`
	Comments    int32  `json:"comments"`
	Messages    int32  `json:"messages"`
	NewUsers    int32  `json:"newUsers"`
	Likes       int32  `json:"likes"`
	ActiveUsers int32  `json:"activeUsers"`
}

type TimetableEntry struct {
	ID        string              `json:"ID"`
	Course    *Course             `json:"course"`
	Color     TimetableEntryColor `json:"color"`
	CreatedAt string              `json:"createdAt"`
}

type UpdateAdministratorInput struct {
	Name     *string `json:"name,omitempty"`
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
}

type UpdateAnnouncementInput struct {
	Title string `json:"title"`
	Body  string `json:"body"`
}

type UpdateCommunityInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	AvatarKey   *string `json:"avatarKey,omitempty"`
}

type UpdatePostInput struct {
	ID              string              `json:"id"`
	Content         string              `json:"content"`
	NewMediaInputs  []*MediaUploadInput `json:"newMediaInputs,omitempty"`
	DeletedMediaIDs []string            `json:"deletedMediaIDs,omitempty"`
}

type UpdateProfileInput struct {
	Username *string `json:"username,omitempty"`
	Bio      *string `json:"bio,omitempty"`
}

type UpdateRoomInput struct {
	Name *string `json:"name,omitempty"`
}

type UpdateUserInput struct {
	AccountID       *string `json:"accountID,omitempty"`
	Name            *string `json:"name,omitempty"`
	Email           *string `json:"email,omitempty"`
	Password        *string `json:"password,omitempty"`
	CurrentPassword *string `json:"currentPassword,omitempty"`
}

type User struct {
	ID        string      `json:"ID"`
	AccountID string      `json:"accountID"`
	Name      string      `json:"name"`
	Email     string      `json:"email"`
	Role      string      `json:"role"`
	Status    string      `json:"status"`
	AvatarURL *string     `json:"avatarUrl,omitempty"`
	CreatedAt string      `json:"createdAt"`
	UpdatedAt string      `json:"updatedAt"`
	Posts     []*Post     `json:"posts"`
	Favorites []*Favorite `json:"favorites"`
}

type UserAuthPayload struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
	User         *User  `json:"user"`
}

type UserPage struct {
	Items []*User `json:"items"`
	Total int32   `json:"total"`
}

type UserReport struct {
	ID           string           `json:"ID"`
	Reporter     *User            `json:"reporter"`
	TargetType   ReportTargetType `json:"targetType"`
	TargetID     string           `json:"targetID"`
	Reason       string           `json:"reason"`
	CustomReason *string          `json:"customReason,omitempty"`
	Status       ReportStatus     `json:"status"`
	CreatedAt    string           `json:"createdAt"`
	UpdatedAt    string           `json:"updatedAt"`
	Content      *string          `json:"content,omitempty"`
}

type CommunityMemberAction string

const (
	CommunityMemberActionPromote CommunityMemberAction = "PROMOTE"
	CommunityMemberActionDemote  CommunityMemberAction = "DEMOTE"
	CommunityMemberActionKick    CommunityMemberAction = "KICK"
)

var AllCommunityMemberAction = []CommunityMemberAction{
	CommunityMemberActionPromote,
	CommunityMemberActionDemote,
	CommunityMemberActionKick,
}

func (e CommunityMemberAction) IsValid() bool {
	switch e {
	case CommunityMemberActionPromote, CommunityMemberActionDemote, CommunityMemberActionKick:
		return true
	}
	return false
}

func (e CommunityMemberAction) String() string {
	return string(e)
}

func (e *CommunityMemberAction) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CommunityMemberAction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CommunityMemberAction", str)
	}
	return nil
}

func (e CommunityMemberAction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CommunityMemberAction) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CommunityMemberAction) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CourseImportState string

const (
	CourseImportStateIdle      CourseImportState = "IDLE"
	CourseImportStateRunning   CourseImportState = "RUNNING"
	CourseImportStateSucceeded CourseImportState = "SUCCEEDED"
	CourseImportStateFailed    CourseImportState = "FAILED"
)

var AllCourseImportState = []CourseImportState{
	CourseImportStateIdle,
	CourseImportStateRunning,
	CourseImportStateSucceeded,
	CourseImportStateFailed,
}

func (e CourseImportState) IsValid() bool {
	switch e {
	case CourseImportStateIdle, CourseImportStateRunning, CourseImportStateSucceeded, CourseImportStateFailed:
		return true
	}
	return false
}

func (e CourseImportState) String() string {
	return string(e)
}

func (e *CourseImportState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CourseImportState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CourseImportState", str)
	}
	return nil
}

func (e CourseImportState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CourseImportState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CourseImportState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type InquiryCategory string

const (
	InquiryCategoryDm        InquiryCategory = "DM"
	InquiryCategoryPost      InquiryCategory = "POST"
	InquiryCategoryCommunity InquiryCategory = "COMMUNITY"
	InquiryCategoryPassword  InquiryCategory = "PASSWORD"
	InquiryCategoryLogin     InquiryCategory = "LOGIN"
	InquiryCategoryOther     InquiryCategory = "OTHER"
)

var AllInquiryCategory = []InquiryCategory{
	InquiryCategoryDm,
	InquiryCategoryPost,
	InquiryCategoryCommunity,
	InquiryCategoryPassword,
	InquiryCategoryLogin,
	InquiryCategoryOther,
}

func (e InquiryCategory) IsValid() bool {
	switch e {
	case InquiryCategoryDm, InquiryCategoryPost, InquiryCategoryCommunity, InquiryCategoryPassword, InquiryCategoryLogin, InquiryCategoryOther:
		return true
	}
	return false
}

func (e InquiryCategory) String() string {
	return string(e)
}

func (e *InquiryCategory) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InquiryCategory(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InquiryCategory", str)
	}
	return nil
}

func (e InquiryCategory) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InquiryCategory) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InquiryCategory) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type InquiryStatus string

const (
	InquiryStatusPending    InquiryStatus = "PENDING"
	InquiryStatusInProgress InquiryStatus = "IN_PROGRESS"
	InquiryStatusResolved   InquiryStatus = "RESOLVED"
)

var AllInquiryStatus = []InquiryStatus{
	InquiryStatusPending,
	InquiryStatusInProgress,
	InquiryStatusResolved,
}

func (e InquiryStatus) IsValid() bool {
	switch e {
	case InquiryStatusPending, InquiryStatusInProgress, InquiryStatusResolved:
		return true
	}
	return false
}

func (e InquiryStatus) String() string {
	return string(e)
}

func (e *InquiryStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InquiryStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InquiryStatus", str)
	}
	return nil
}

func (e InquiryStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InquiryStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InquiryStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ReportStatus string

const (
	ReportStatusPending   ReportStatus = "PENDING"
	ReportStatusReviewing ReportStatus = "REVIEWING"
	ReportStatusResolved  ReportStatus = "RESOLVED"
	ReportStatusDismissed ReportStatus = "DISMISSED"
)

var AllReportStatus = []ReportStatus{
	ReportStatusPending,
	ReportStatusReviewing,
	ReportStatusResolved,
	ReportStatusDismissed,
}

func (e ReportStatus) IsValid() bool {
	switch e {
	case ReportStatusPending, ReportStatusReviewing, ReportStatusResolved, ReportStatusDismissed:
		return true
	}
	return false
}

func (e ReportStatus) String() string {
	return string(e)
}

func (e *ReportStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReportStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReportStatus", str)
	}
	return nil
}

func (e ReportStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReportStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReportStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ReportTargetType string

const (
	ReportTargetTypePost      ReportTargetType = "POST"
	ReportTargetTypeUser      ReportTargetType = "USER"
	ReportTargetTypeCommunity ReportTargetType = "COMMUNITY"
)

var AllReportTargetType = []ReportTargetType{
	ReportTargetTypePost,
	ReportTargetTypeUser,
	ReportTargetTypeCommunity,
}

func (e ReportTargetType) IsValid() bool {
	switch e {
	case ReportTargetTypePost, ReportTargetTypeUser, ReportTargetTypeCommunity:
		return true
	}
	return false
}

func (e ReportTargetType) String() string {
	return string(e)
}

func (e *ReportTargetType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReportTargetType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReportTargetType", str)
	}
	return nil
}

func (e ReportTargetType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReportTargetType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReportTargetType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ThemePreference string

const (
	ThemePreferenceLight ThemePreference = "LIGHT"
	ThemePreferenceDark  ThemePreference = "DARK"
)

var AllThemePreference = []ThemePreference{
	ThemePreferenceLight,
	ThemePreferenceDark,
}

func (e ThemePreference) IsValid() bool {
	switch e {
	case ThemePreferenceLight, ThemePreferenceDark:
		return true
	}
	return false
}

func (e ThemePreference) String() string {
	return string(e)
}

func (e *ThemePreference) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ThemePreference(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ThemePreference", str)
	}
	return nil
}

func (e ThemePreference) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ThemePreference) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ThemePreference) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TimeSeriesGranularity string

const (
	TimeSeriesGranularityDay  TimeSeriesGranularity = "day"
	TimeSeriesGranularityHour TimeSeriesGranularity = "hour"
)

var AllTimeSeriesGranularity = []TimeSeriesGranularity{
	TimeSeriesGranularityDay,
	TimeSeriesGranularityHour,
}

func (e TimeSeriesGranularity) IsValid() bool {
	switch e {
	case TimeSeriesGranularityDay, TimeSeriesGranularityHour:
		return true
	}
	return false
}

func (e TimeSeriesGranularity) String() string {
	return string(e)
}

func (e *TimeSeriesGranularity) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TimeSeriesGranularity(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TimeSeriesGranularity", str)
	}
	return nil
}

func (e TimeSeriesGranularity) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TimeSeriesGranularity) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TimeSeriesGranularity) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TimetableEntryColor string

const (
	TimetableEntryColorRedVivid     TimetableEntryColor = "RED_VIVID"
	TimetableEntryColorOrangeVivid  TimetableEntryColor = "ORANGE_VIVID"
	TimetableEntryColorYellowVivid  TimetableEntryColor = "YELLOW_VIVID"
	TimetableEntryColorGreenVivid   TimetableEntryColor = "GREEN_VIVID"
	TimetableEntryColorCyanVivid    TimetableEntryColor = "CYAN_VIVID"
	TimetableEntryColorBlueVivid    TimetableEntryColor = "BLUE_VIVID"
	TimetableEntryColorIndigoVivid  TimetableEntryColor = "INDIGO_VIVID"
	TimetableEntryColorPurpleVivid  TimetableEntryColor = "PURPLE_VIVID"
	TimetableEntryColorMagentaVivid TimetableEntryColor = "MAGENTA_VIVID"
	TimetableEntryColorRed          TimetableEntryColor = "RED"
	TimetableEntryColorOrange       TimetableEntryColor = "ORANGE"
	TimetableEntryColorYellow       TimetableEntryColor = "YELLOW"
	TimetableEntryColorGreen        TimetableEntryColor = "GREEN"
	TimetableEntryColorCyan         TimetableEntryColor = "CYAN"
	TimetableEntryColorBlue         TimetableEntryColor = "BLUE"
	TimetableEntryColorIndigo       TimetableEntryColor = "INDIGO"
	TimetableEntryColorPurple       TimetableEntryColor = "PURPLE"
	TimetableEntryColorMagenta      TimetableEntryColor = "MAGENTA"
	TimetableEntryColorRedLight     TimetableEntryColor = "RED_LIGHT"
	TimetableEntryColorOrangeLight  TimetableEntryColor = "ORANGE_LIGHT"
	TimetableEntryColorYellowLight  TimetableEntryColor = "YELLOW_LIGHT"
	TimetableEntryColorGreenLight   TimetableEntryColor = "GREEN_LIGHT"
	TimetableEntryColorCyanLight    TimetableEntryColor = "CYAN_LIGHT"
	TimetableEntryColorBlueLight    TimetableEntryColor = "BLUE_LIGHT"
	TimetableEntryColorIndigoLight  TimetableEntryColor = "INDIGO_LIGHT"
	TimetableEntryColorPurpleLight  TimetableEntryColor = "PURPLE_LIGHT"
	TimetableEntryColorMagentaLight TimetableEntryColor = "MAGENTA_LIGHT"
	TimetableEntryColorRedMuted     TimetableEntryColor = "RED_MUTED"
	TimetableEntryColorOrangeMuted  TimetableEntryColor = "ORANGE_MUTED"
	TimetableEntryColorYellowMuted  TimetableEntryColor = "YELLOW_MUTED"
	TimetableEntryColorGreenMuted   TimetableEntryColor = "GREEN_MUTED"
	TimetableEntryColorCyanMuted    TimetableEntryColor = "CYAN_MUTED"
	TimetableEntryColorBlueMuted    TimetableEntryColor = "BLUE_MUTED"
	TimetableEntryColorIndigoMuted  TimetableEntryColor = "INDIGO_MUTED"
	TimetableEntryColorPurpleMuted  TimetableEntryColor = "PURPLE_MUTED"
	TimetableEntryColorMagentaMuted TimetableEntryColor = "MAGENTA_MUTED"
)

var AllTimetableEntryColor = []TimetableEntryColor{
	TimetableEntryColorRedVivid,
	TimetableEntryColorOrangeVivid,
	TimetableEntryColorYellowVivid,
	TimetableEntryColorGreenVivid,
	TimetableEntryColorCyanVivid,
	TimetableEntryColorBlueVivid,
	TimetableEntryColorIndigoVivid,
	TimetableEntryColorPurpleVivid,
	TimetableEntryColorMagentaVivid,
	TimetableEntryColorRed,
	TimetableEntryColorOrange,
	TimetableEntryColorYellow,
	TimetableEntryColorGreen,
	TimetableEntryColorCyan,
	TimetableEntryColorBlue,
	TimetableEntryColorIndigo,
	TimetableEntryColorPurple,
	TimetableEntryColorMagenta,
	TimetableEntryColorRedLight,
	TimetableEntryColorOrangeLight,
	TimetableEntryColorYellowLight,
	TimetableEntryColorGreenLight,
	TimetableEntryColorCyanLight,
	TimetableEntryColorBlueLight,
	TimetableEntryColorIndigoLight,
	TimetableEntryColorPurpleLight,
	TimetableEntryColorMagentaLight,
	TimetableEntryColorRedMuted,
	TimetableEntryColorOrangeMuted,
	TimetableEntryColorYellowMuted,
	TimetableEntryColorGreenMuted,
	TimetableEntryColorCyanMuted,
	TimetableEntryColorBlueMuted,
	TimetableEntryColorIndigoMuted,
	TimetableEntryColorPurpleMuted,
	TimetableEntryColorMagentaMuted,
}

func (e TimetableEntryColor) IsValid() bool {
	switch e {
	case TimetableEntryColorRedVivid, TimetableEntryColorOrangeVivid, TimetableEntryColorYellowVivid, TimetableEntryColorGreenVivid, TimetableEntryColorCyanVivid, TimetableEntryColorBlueVivid, TimetableEntryColorIndigoVivid, TimetableEntryColorPurpleVivid, TimetableEntryColorMagentaVivid, TimetableEntryColorRed, TimetableEntryColorOrange, TimetableEntryColorYellow, TimetableEntryColorGreen, TimetableEntryColorCyan, TimetableEntryColorBlue, TimetableEntryColorIndigo, TimetableEntryColorPurple, TimetableEntryColorMagenta, TimetableEntryColorRedLight, TimetableEntryColorOrangeLight, TimetableEntryColorYellowLight, TimetableEntryColorGreenLight, TimetableEntryColorCyanLight, TimetableEntryColorBlueLight, TimetableEntryColorIndigoLight, TimetableEntryColorPurpleLight, TimetableEntryColorMagentaLight, TimetableEntryColorRedMuted, TimetableEntryColorOrangeMuted, TimetableEntryColorYellowMuted, TimetableEntryColorGreenMuted, TimetableEntryColorCyanMuted, TimetableEntryColorBlueMuted, TimetableEntryColorIndigoMuted, TimetableEntryColorPurpleMuted, TimetableEntryColorMagentaMuted:
		return true
	}
	return false
}

func (e TimetableEntryColor) String() string {
	return string(e)
}

func (e *TimetableEntryColor) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TimetableEntryColor(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TimetableEntryColor", str)
	}
	return nil
}

func (e TimetableEntryColor) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TimetableEntryColor) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TimetableEntryColor) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
